import assert from 'node:assert/strict';
import fs from 'node:fs';
const home=fs.readFileSync('src/google-home.ts','utf8'),app=fs.readFileSync('src/app.ts','utf8'),docs=fs.readFileSync('docs/GOOGLE_HOME_VOICE_SETUP.md','utf8');
assert.match(home,/SCENE_NAME_MAX=60/);assert.match(home,/Array\.from/);assert.match(home,/\.slice\(0,4\)/);
for(const value of ["ft:log:${detail}:${s.id}:now","ft:log:${detail}:${s.id}:m60",'DIAPER','TOILET','MINUS_60',"subject_kind IN ('BABY','CHILD')",'enabled_types_json','action.devices.types.SCENE','action.devices.traits.Scene'])assert.ok(home.includes(value),value);
for(const value of ['recordExternalFamilyLogDomain','addWallClockMinutes(current,-60)','created_by','detail_code',"['NOW','MINUS_60']","['WET','DIRTY']",'familyNow'])assert.ok(app.includes(value),value);
const singleExpression=home.match(/single=([^;]+);/)?.[1]||'';
assert.match(singleExpression,/filter/);assert.match(singleExpression,/subject_kind/);assert.match(singleExpression,/PET/);
const isSingleChildCount=subjects=>subjects.filter(s=>s.subject_kind!=='PET').length===1;
assert.equal(isSingleChildCount([{subject_kind:'BABY'},{subject_kind:'PET'},{subject_kind:'PET'}]),true);
assert.equal(isSingleChildCount([{subject_kind:'BABY'},{subject_kind:'CHILD'},{subject_kind:'PET'}]),false);
assert.ok(home.includes("single?'':String(s.name)"));assert.ok(home.includes("1時間前の${possessive}${word}記録"));
assert.doesNotMatch(home,/m99999/);assert.match(docs,/自由な音声文/);assert.match(docs,/Computer \/ Speaker \/ Tablet \/ Window/);
console.log('wave114 google home family log scene smoke: ok');
