import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync('public/assets/family-log-import.js','utf8');
const status={textContent:''}, repair={dataset:{id:'98'},listeners:{},addEventListener(k,v){this.listeners[k]=v}};
const elements={familyLogImportPayload:{textContent:JSON.stringify({csrf:'token',subjects:{},types:{},maxBytes:100})},importFile:{files:[]},importSubject:{value:''},importStatus:status,importPreviewOut:{replaceChildren(){},appendChild(){}},importPreview:{},};
let request;
const document={getElementById:id=>elements[id],querySelectorAll:s=>s==='.import-time-repair'?[repair]:[],createElement:()=>({append(){},appendChild(){}})};
const fetch=async(_url,options)=>{request=JSON.parse(options.body);return {ok:true,json:async()=>({ok:true,total_count:1,target_count:0,skipped_edited_count:1,offset_minutes:540,timezone:'Asia/Tokyo',samples:[]})}};
vm.runInNewContext(source,{document,fetch,confirm:()=>false,alert(){},location:{reload(){}},setTimeout,URL,console});
assert.equal(typeof repair.listeners.click,'function','repair click listener is registered');
await repair.listeners.click();
assert.equal(request.action,'repair_preview','click posts repair_preview through scoped call');
assert.match(status.textContent,/対象はありません/);
const calendar=fs.readFileSync('src/google-calendar.ts','utf8'),index=fs.readFileSync('src/index.ts','utf8'),app=fs.readFileSync('src/app.ts','utf8'),page=fs.readFileSync('src/family-log-import.ts','utf8');
for(const text of ['queueCalendarProjectionAfterMutation','link?\'UPDATE\':\'CREATE\'','if(link)return enqueueCalendarSync','calendarBackfill','pending_before','pending_after','変更はありません'])assert.ok(calendar.includes(text),text);
assert.ok(index.includes("'/api/google-calendar/backfill'"));
assert.ok((index.match(/queueCalendarProjectionAfterMutation/g)||[]).length>=3);
assert.ok((app.match(/queueCalendarProjectionAfterMutation/g)||[]).length>=4);
assert.ok(page.includes('12.121.0-wave102'));
console.log('wave102 smoke: ok');
