import assert from 'node:assert/strict';
import fs from 'node:fs';
import {generateKeyPairSync,webcrypto} from 'node:crypto';
import ts from 'typescript';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const js=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const data=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const timezone=await import(data(js('src/timezone.ts')));
let request=js('src/google-home-request-sync.ts').replace("from './timezone'",`from '${data(js('src/timezone.ts'))}'`);
const sync=await import(data(request));
const {privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});
const pem=privateKey.export({type:'pkcs8',format:'pem'}).toString();
const credential={type:'service_account',client_email:'synthetic-wave126@example.invalid',private_key:pem,token_uri:'https://oauth2.googleapis.com/token'};
const parse=x=>sync.parseGoogleHomeServiceAccountSecret(x);
assert.equal(parse(JSON.stringify(credential)).category,'VALID');
assert.equal(parse(` \n ${JSON.stringify(credential)} \n `).ok,true);
assert.equal(parse('\uFEFF'+JSON.stringify(credential)).ok,true);
assert.equal(parse(JSON.stringify(JSON.stringify(credential))).category,'JSON_WRAPPED_STRING_ACCEPTED');
assert.equal(parse(JSON.stringify({...credential,client_email:''})).category,'MISSING_CLIENT_EMAIL');
assert.equal(parse(JSON.stringify({...credential,private_key:''})).category,'MISSING_PRIVATE_KEY');
assert.equal(parse(JSON.stringify({...credential,private_key:'not a key'})).category,'INVALID_PRIVATE_KEY_PEM');
assert.equal(parse(JSON.stringify({...credential,private_key:pem.replaceAll('\n','\\n')})).credential.private_key,pem);
assert.equal((await sync.validateGoogleHomeServiceAccountSecret(JSON.stringify(credential))).ok,true);
const jwt=await sync.createHomeGraphJwt({GOOGLE_HOME_SERVICE_ACCOUNT_JSON:JSON.stringify(credential)},1_777_000_000);
assert.equal(jwt.split('.').length,3);assert.ok(jwt.length>200);
assert.equal(timezone.formatStoredUtcForFamily('2026-08-28 18:03:42','Asia/Tokyo'),'2026-08-29 03:03:42');
assert.equal(timezone.formatStoredUtcForFamily('2026-08-28 18:03:42','America/Los_Angeles'),'2026-08-28 11:03:42');
assert.equal(timezone.formatStoredUtcForFamily('2026-01-01 02:03:42','America/Los_Angeles'),'2025-12-31 18:03:42');
assert.equal(timezone.formatStoredUtcForFamily(null,'Asia/Tokyo'),'—');
assert.equal(timezone.formatStoredUtcForFamily('invalid','Asia/Tokyo'),'invalid');
for(const file of ['src/google-home.ts','src/google-tasks.ts','src/index.ts'])assert.ok(fs.readFileSync(file,'utf8').includes('formatStoredUtcForFamily'),file);
const calendar=fs.readFileSync('src/google-calendar.ts','utf8')+fs.readFileSync('src/google-calendar-core.ts','utf8');
assert.ok(calendar.includes('formatStoredUtcForFamily'),'src/google-calendar.ts/core');
console.log('wave126 credential parser, PKCS8/JWT crypto, and UTC family display smoke ok');
