import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const read=p=>fs.readFileSync(p,'utf8');
const ai=read('src/family-ai.ts'),home=read('src/google-home.ts'),docs=read('docs/GOOGLE_HOME_VOICE_SETUP.md');
assert.ok(!ai.includes('generateContent?key='));
assert.match(ai,/'x-goog-api-key':key/);assert.ok((ai.match(/geminiFetch\(/g)||[]).length>=2);
for(const x of ['API_KEY_INVALID','PERMISSION_DENIED','INVALID_REQUEST','FAILED_PRECONDITION','MODEL_NOT_FOUND','RATE_LIMIT_RPM','UPSTREAM_UNAVAILABLE'])assert.ok(ai.includes(x));
assert.ok(!ai.includes('error.message'));assert.ok(ai.includes('family_statistics'));
for(const x of ['oauth-redirect.googleusercontent.com','oauth-redirect-sandbox.googleusercontent.com','GOOGLE_HOME_PROJECT_ID','action.devices.types.SCENE','action.devices.commands.ActivateScene','external_command_receipts','GoogleとFamily TODO'])assert.ok(home.includes(x));
const source=read('src/liff-target.ts');
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const url='data:text/javascript;base64,'+Buffer.from(js).toString('base64');
const {validateLiffNext}=await import(url);
for(const target of ['/app/calendar.php','/app/tasks.php'])assert.equal(validateLiffNext(target),target);
for(const target of ['https://evil.example','//evil.example','javascript:alert(1)','/app/tasks.php\r\nX: y','/app\\tasks.php','/oauth/google/token'])assert.equal(validateLiffNext(target),null);
const resume=('a'.repeat(24))+'.'+('b'.repeat(24));
assert.equal(validateLiffNext('/oauth/google/continue?resume='+resume),'/oauth/google/continue?resume='+resume);
assert.equal(validateLiffNext('/oauth/google/continue?resume=bad'),null);
assert.ok(docs.includes('架空device type/traitは追加しません'));assert.ok(docs.includes('Report State非対応'));
console.log('wave104 smoke: ok');
