import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8'),app=read('src/app.ts'),index=read('src/index.ts'),cal=read('src/google-calendar.ts')+read('src/google-calendar-core.ts'),js=read('public/assets/calendar.js'),css=read('public/assets/family.css'),migration=read('migrations/0042_wave128_calendar_digest_private_event.sql');
for(const x of ['recurrence_rule_id','recurrence_occurrence_id','occurrence_date'])assert.ok(app.includes(x)&&js.includes(x),x);
assert.ok(js.includes("new URLSearchParams({edit:")&&!js.includes("href=\"/task/view.php?id='+encodeURIComponent(t.id)+'\""));
for(const x of ["view==='family'","view==='assigned'","view==='private'","taskVisibilitySql('t')"])assert.ok(app.includes(x),x);
assert.ok(read('public/assets/task-new.js').includes('if(isPrivate)isPrivate.disabled=false'));
assert.ok(cal.includes("visibility_scope='FAMILY'")&&cal.includes("task_kind='EVENT'")&&cal.includes("event_history")&&cal.includes("upper(COALESCE(task_kind,'TASK'))='EVENT'"));
assert.ok(cal.includes("source:'GOOGLE_CALENDAR'")&&cal.includes("String(task.task_kind||'TASK').toUpperCase()==='EVENT'")&&cal.includes('calendar_visible=0'));
assert.ok(cal.includes("ON CONFLICT(provider,task_id)")&&cal.includes("link?'UPDATE':'CREATE'"));
for(const x of ['text-overflow:clip','-webkit-line-clamp:2','repeat(4'])assert.ok(css.includes(x),x);assert.ok(!app.includes('その他のタイマー'));
assert.ok(index.includes("const channel='WEB_PUSH'")&&!index.slice(index.indexOf('async function processNotifications'),index.indexOf('async function taskDelete')).includes('pushLineMessage'));
for(const x of ['UNIQUE(family_id,member_id,local_date)','line_daily_digest_receipts','line_daily_digest_recipients'])assert.ok(migration.includes(x),x);
assert.ok(index.includes("visibility_scope='PRIVATE' AND private_owner_id=?")&&index.includes("current>target+9"));
for(const x of ['active channel count','fallback polling active','DB_SCHEMA_MIGRATION_REQUIRED'])assert.ok((cal+index).includes(x),x);
console.log('wave128 smoke ok');
