import assert from 'node:assert/strict';
import fs from 'node:fs';
const source=fs.readFileSync('src/calendar-ics-import.ts','utf8'),app=fs.readFileSync('src/app.ts','utf8'),ui=fs.readFileSync('public/assets/calendar-import.js','utf8'),css=fs.readFileSync('public/assets/calendar.css','utf8'),pkg=JSON.parse(fs.readFileSync('package.json'));
assert.match(pkg.version,/^12\.(?:129\.0-wave110|130\.0-wave111|131\.0-wave112|132\.0-wave113|133\.0-wave114|134\.0-wave115|135\.0-wave116|136\.0-wave117|136\.1-wave117-hotfix|137\.0-wave118|138\.0-wave119|139\.0-wave120|140\.0-wave121)$/);
assert.match(source,/MAX_D1_QUERY_BUDGET=40/);assert.doesNotMatch(source,/query_budget_max:(?:67|64)/);
const applyCost=e=>2+(e.recurring?1+e.exdates:0),pack=(events,reserve=6)=>{let q=reserve,n=0;for(const e of events){const c=applyCost(e);if(n&&q+c>40)break;q+=c;n++;}return {q,n};};
const worst=Array.from({length:10},()=>({recurring:true,exdates:4})),first=pack(worst);assert.ok(first.q<50);assert.equal(first.q,34);assert.equal(first.n,4);
let remaining=634,invocations=0;while(remaining){const x=pack(Array.from({length:Math.min(remaining,20)},()=>({recurring:false,exdates:0})));assert.ok(x.q<=40);remaining-=x.n;invocations++;}assert.ok(invocations>0&&remaining===0);
const rollbackPack=costs=>{let q=3,n=0;for(const c of costs){if(n&&q+c>40)break;q+=c;n++;}return {q,n};};const rollback=rollbackPack(Array(10).fill(4));assert.equal(rollback.q,39);assert.equal(rollback.n,9);assert.ok(rollback.q<50);
for(const title of ['14:00 美容院','14:00美容院','14:00- 美容院','7:00〜 出産準備','15:00-17:00 見守り','１５：００～１７：００　見守り','19:00-21:00'])assert.ok(title.normalize('NFKC').match(/^\s*\d{1,2}:\d{2}/));
assert.match(source,/if\(!duration\)return s\.start_time/);assert.match(source,/cleaned\|\|title/);assert.match(source,/if\(!e\.allDay\|\|e\.rrule\)continue/);
assert.ok(ui.includes('終了時刻なし（推奨）'));assert.ok(ui.includes('変更しない'));
for(const token of ['calendarDisplayLabel','calendar-item-time','a===r.start','aria-label'])assert.ok(app.includes(token)||css.includes(token),token);
assert.match(app,/display\.time\?display\.time\+' ':''}\$\{icon/);assert.match(app,/same&&.*===time/);
console.log('wave110 smoke: dynamic D1 budgets, 634-event completion, normalization, and calendar labels ok');
