import fs from 'node:fs';import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8'),app=read('src/app.ts'),oauth=read('src/oauth-continuation.ts'),liff=read('public/assets/liff-auth.js'),css=read('public/assets/calendar.css'),log=read('public/assets/family-log.js'),pkg=JSON.parse(read('package.json')),inventory=JSON.parse(read('source_inventory.json'));
assert.ok(['12.143.0-wave124','12.139.0-wave120','12.140.0-wave121','12.141.0-wave122','12.142.0-wave123'].includes(pkg.version));assert.equal(inventory.version,pkg.version);
assert.ok(oauth.includes("stage:'LIFF_PRIMARY_RECEIVED'"));assert.ok(!oauth.slice(oauth.indexOf('export async function normalLiff'),oauth.indexOf('export async function liffDispatcher')).includes('ctx.member)return go'));
assert.ok(liff.indexOf('await window.liff.init')<liff.indexOf('const current=resolve()'));assert.ok(liff.includes("url.searchParams.get('next')"));assert.ok(liff.includes('return valid(payload.next)'));
for(const path of ['/app/tasks.php','/app/calendar.php','/app/shopping.php','/app/family_log.php','/app/messages.php','/app/settings.php'])assert.ok(app.includes(path));
for(const unsafe of ['^(?!//)','\\r\\n','\\\\'])assert.ok(read('src/liff-target.ts').includes(unsafe)||read('src/liff-target.ts').includes('validateLiffNext'));
assert.ok(liff.includes("fetch('/__cf/auth-health'"));assert.ok(oauth.includes('SESSION_COMMIT_FAILED'));assert.ok(oauth.includes('LINE_WEB_AUTH_STARTED'));
assert.ok(css.includes('--calendar-no-band-content-top:29px'));assert.ok(css.includes('[data-band-rows="0"]'));assert.ok(css.includes('var(--calendar-day-band-rows) * var(--calendar-band-step)'));assert.ok(app.match(/>移動<\/button>/g)?.length===2);assert.ok(css.includes('min-height:40px'));assert.ok(css.includes('width:min(292px,calc(100vw - 20px))'));
for(const marker of ["action==='quick_record'",'BABY_FOOD',"VOMIT",'family_log_milk_amount_presets',"subject_kind)!=='BABY'",'linked_task_id,linked_occurrence_id'])assert.ok(app.includes(marker));
for(const marker of ['family-log-quick-action',"action:'execute_quick_action'","action:'sleep_start'","action:'sleep_stop'",'family-log-form-action'])assert.ok(log.includes(marker)||app.includes(marker));
for(const key of ['WET','DIRTY','BABY_FOOD','BATH','VOMIT','MILK'])assert.ok(app.includes(key));assert.ok(app.includes('milkAmountPresets.map'));
for(const asset of ['liff-auth.js','calendar.css','calendar.js','family-log.js','family.css'])assert.ok(app.includes(asset+'?v='+pkg.version));
console.log('wave119 smoke: ok');
