import assert from 'node:assert/strict';
import fs from 'node:fs';
const ai=fs.readFileSync('src/family-ai.ts','utf8'),home=fs.readFileSync('src/google-home.ts','utf8'),app=fs.readFileSync('src/app.ts','utf8'),docs=fs.readFileSync('docs/GOOGLE_HOME_VOICE_SETUP.md','utf8');
assert.ok(!ai.includes('generateContent?key='));
assert.match(ai,/'x-goog-api-key':key/);assert.equal((ai.match(/geminiFetch\(ctx\.env/g)||[]).length,2);
for(const x of ['API_KEY_INVALID','PERMISSION_DENIED','INVALID_REQUEST','FAILED_PRECONDITION','MODEL_NOT_FOUND','RATE_LIMITED','UPSTREAM_UNAVAILABLE'])assert.ok(ai.includes(x));
assert.ok(!ai.includes('error.message'));assert.ok(ai.includes('family_statistics'));
for(const x of ['oauth-redirect.googleusercontent.com','oauth-redirect-sandbox.googleusercontent.com','GOOGLE_HOME_PROJECT_ID','action.devices.types.SCENE','action.devices.commands.ActivateScene','external_command_receipts','GoogleとFamily TODO'])assert.ok(home.includes(x));
assert.match(app,/safeNext=.*\^\\\\\/|safeNext=.*\^\\\//);assert.ok(docs.includes('架空device type/traitは追加しません'));assert.ok(docs.includes('Report State非対応'));
console.log('wave104 smoke: ok');
