import { html, json } from './response';
import { layout, AuthRequired, BadRequest, Forbidden } from './app';
import type { AppContext } from './app';
import { DEFAULT_FAMILY_TIMEZONE, familyDate, familyNow, formatFamilyDateTime, validateTimezone } from './timezone';
type Row=Record<string,unknown>;
type ParsedProperty={name:string;params:Record<string,string>;value:string};
type RawEvent={props:(ParsedProperty|null)[];alarms:number};

export const ICS_MAX_BYTES=2*1024*1024, ICS_MAX_EVENTS=5000, ICS_APPLY_CHUNK=50, ICS_MAX_LINE=64*1024;
const esc=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const admin=(m:Row)=>['OWNER','ADMIN'].includes(String(m.role||'').toUpperCase());
const text=(v:string)=>v.replace(/\\[nN]/g,'\n').replace(/\\,/g,',').replace(/\\;/g,';').replace(/\\\\/g,'\\');
const sha=async(v:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const dateOk=(v:string)=>{if(!/^\d{8}$/.test(v))return false;const d=new Date(Date.UTC(+v.slice(0,4),+v.slice(4,6)-1,+v.slice(6,8)));return d.toISOString().slice(0,10).replaceAll('-','')===v;};
const isoDate=(v:string)=>`${v.slice(0,4)}-${v.slice(4,6)}-${v.slice(6,8)}`;
const addDays=(v:string,n:number)=>{const d=new Date(`${v}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};

export type IcsEvent={uid:string;recurrenceId:string;summary:string;description:string;location:string;color:string|null;startAt:string;endAt:string;startDate:string;allDay:boolean;rrule:ReturnType<typeof parseRrule>|null;exdates:string[];relatedTo:string|null;created:string|null;lastModified:string|null;alarmCount:number;sourceHash:string;warnings:string[]};
export type IcsDocument={name:string;timezone:string|null;events:IcsEvent[];errors:string[];alarmCount:number;allDayCount:number;timedCount:number;recurringCount:number;exdateEventCount:number;relatedCount:number;recurrenceIdCount:number;firstDate:string|null;lastDate:string|null};

function parseProperty(line:string){let split=-1,quoted=false;for(let i=0;i<line.length;i++){if(line[i]==='"')quoted=!quoted;else if(line[i]===':'&&!quoted){split=i;break;}}if(split<1)return null;const left=line.slice(0,split).split(';'),name=left.shift()!.toUpperCase(),params:Record<string,string>={};for(const item of left){const p=item.indexOf('=');if(p>0)params[item.slice(0,p).toUpperCase()]=item.slice(p+1).replace(/^"|"$/g,'');}return {name,params,value:line.slice(split+1)};}
function localInZoneToInstant(raw:string,zone:string){const m=raw.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})$/);if(!m)throw new Error('日時形式が不正です');const wall=Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+m[6]);let guess=wall;for(let i=0;i<3;i++){const shown=formatFamilyDateTime(new Date(guess),zone),asUtc=Date.parse(shown.replace(' ','T')+'Z');guess+=wall-asUtc;}return new Date(guess);}
function parseDateValue(value:string,params:Record<string,string>,familyZone:string){const dateOnly=params.VALUE?.toUpperCase()==='DATE'||/^\d{8}$/.test(value);if(dateOnly){if(!dateOk(value))throw new Error('日付が不正です');return {allDay:true,local:`${isoDate(value)} 00:00:00`,date:isoDate(value)};}const zulu=value.endsWith('Z'),raw=zulu?value.slice(0,-1):value;if(!/^\d{8}T\d{6}$/.test(raw))throw new Error('日時が不正です');let instant:Date|null=null;if(zulu)instant=new Date(`${isoDate(raw)}T${raw.slice(9,11)}:${raw.slice(11,13)}:${raw.slice(13,15)}Z`);else if(params.TZID){if(!validateTimezone(params.TZID))throw new Error(`未対応のタイムゾーンです: ${params.TZID}`);instant=localInZoneToInstant(raw,params.TZID);}const local=instant?formatFamilyDateTime(instant,familyZone):`${isoDate(raw)} ${raw.slice(9,11)}:${raw.slice(11,13)}:${raw.slice(13,15)}`;return {allDay:false,local,date:local.slice(0,10)};}
export function parseRrule(raw:string){const parts=Object.fromEntries(raw.toUpperCase().split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),x.slice(i+1)];}));const freq=parts.FREQ||'',interval=Math.max(1,Number(parts.INTERVAL||1));if(!['WEEKLY','MONTHLY','YEARLY'].includes(freq)||!Number.isInteger(interval))throw new Error(`未対応のRRULEです: ${freq||raw}`);const weekdays=(parts.BYDAY||'').split(',').filter(Boolean).map(x=>({SU:0,MO:1,TU:2,WE:3,TH:4,FR:5,SA:6} as Record<string,number>)[x]).filter(x=>x!==undefined);const monthdays=(parts.BYMONTHDAY||'').split(',').filter(Boolean).map(Number).filter(x=>x>=1&&x<=31);if(freq==='MONTHLY'&&!monthdays.length)throw new Error('MONTHLYにはBYMONTHDAYが必要です');return {freq,interval,weekdays,monthdays,until:parts.UNTIL||null,wkst:parts.WKST||null};}

export async function parseIcs(raw:string,familyZone=DEFAULT_FAMILY_TIMEZONE):Promise<IcsDocument>{
  if(new TextEncoder().encode(raw).byteLength>ICS_MAX_BYTES)throw new Error('ICSファイルは2 MiB以下にしてください。');if(raw.includes('\0'))throw new Error('ICSにNUL文字を含めることはできません。');
  const physical=raw.replace(/^\uFEFF/,'').split(/\r\n|\n|\r/),lines:string[]=[];for(const line of physical){if(line.length>ICS_MAX_LINE)throw new Error('ICSの行が長すぎます。');if(/^[ \t]/.test(line)&&lines.length)lines[lines.length-1]+=line.slice(1);else lines.push(line);}if(!lines.some(x=>x.trim().toUpperCase()==='BEGIN:VCALENDAR')||!lines.some(x=>x.trim().toUpperCase()==='END:VCALENDAR'))throw new Error('VCALENDARが見つかりません。');
  let calendarName='ICSカレンダー',calendarZone:string|null=null,inEvent=false,depth=0,current:RawEvent|null=null;const rawEvents:RawEvent[]=[];
  for(const line of lines){const p=parseProperty(line);if(!p)continue;if(!inEvent){if(p.name==='X-WR-CALNAME')calendarName=text(p.value).slice(0,255);if(p.name==='TZID'&&validateTimezone(p.value))calendarZone=p.value;if(p.name==='BEGIN'&&p.value.toUpperCase()==='VEVENT'){inEvent=true;depth=1;current={props:[],alarms:0};}continue;}if(p.name==='BEGIN'){depth++;if(p.value.toUpperCase()==='VALARM')current!.alarms++;continue;}if(p.name==='END'){depth--;if(p.value.toUpperCase()==='VEVENT'&&depth===0){rawEvents.push(current!);current=null;inEvent=false;}continue;}if(depth===1)current!.props.push(p);
  }
  if(rawEvents.length>ICS_MAX_EVENTS)throw new Error('VEVENTは5,000件以下にしてください。');const errors:string[]=[],events:IcsEvent[]=[];
  for(let i=0;i<rawEvents.length;i++){try{const r=rawEvents[i],get=(n:string)=>r.props.find(p=>p?.name===n)||null,all=(n:string)=>r.props.filter(p=>p?.name===n),uid=text(get('UID')?.value||'').trim();if(!uid)throw new Error('UIDがありません');if(uid.length>1024)throw new Error('UIDが長すぎます');const ds=get('DTSTART');if(!ds)throw new Error('DTSTARTがありません');const start=parseDateValue(ds.value,ds.params,familyZone),de=get('DTEND');let end=start;if(de)end=parseDateValue(de.value,de.params,familyZone);else if(start.allDay)end={...start,local:`${start.date} 23:59:59`};if(start.allDay!==end.allDay)throw new Error('DTSTARTとDTENDの型が一致しません');let endAt=end.local;if(start.allDay&&de)endAt=`${addDays(end.date,-1)} 23:59:59`;if(endAt<start.local)throw new Error('DTENDがDTSTARTより前です');const ruleProp=get('RRULE'),rule=ruleProp?parseRrule(ruleProp.value):null;const exdates=all('EXDATE').flatMap(p=>p!.value.split(',').map(v=>parseDateValue(v,p!.params,familyZone).date));const recurrenceId=get('RECURRENCE-ID');const summary=text(get('SUMMARY')?.value||'（無題）').slice(0,255),warnings:string[]=[];if(recurrenceId)warnings.push('RECURRENCE-IDは安全な単発予定として取り込みます。series例外へは統合しません。');if(start.allDay&&/(?:^|\s)\d{1,2}:\d{2}(?:\s|$)/.test(summary))warnings.push('タイトルに時刻らしき文字がありますが、DTSTARTに従い終日として扱います。');const canonical=JSON.stringify(r.props.map(p=>[p?.name,p?.params,p?.value]));events.push({uid,recurrenceId:recurrenceId?.value||'',summary,description:text(get('DESCRIPTION')?.value||'').slice(0,10000),location:text(get('LOCATION')?.value||'').slice(0,1000),color:/^#[0-9a-f]{6}$/i.test(get('COLOR')?.value||'')?String(get('COLOR')!.value).toLowerCase():null,startAt:start.local,endAt, startDate:start.date,allDay:start.allDay,rrule:rule,exdates,relatedTo:get('RELATED-TO')?.value||null,created:get('CREATED')?.value||null,lastModified:get('LAST-MODIFIED')?.value||null,alarmCount:r.alarms,sourceHash:await sha(canonical),warnings});}catch(e){errors.push(`VEVENT ${i+1}: ${String((e as Error).message||e)}`);}}
  const seen=new Set<string>();for(const e of events){const key=eventKey(e);if(seen.has(key))errors.push(`重複したUID / RECURRENCE-IDです: ${e.uid}`);seen.add(key);}const dates=events.flatMap(e=>[e.startAt.slice(0,10),e.endAt.slice(0,10)]).sort();return {name:calendarName,timezone:calendarZone,events,errors,alarmCount:events.reduce((n,e)=>n+e.alarmCount,0),allDayCount:events.filter(e=>e.allDay).length,timedCount:events.filter(e=>!e.allDay).length,recurringCount:events.filter(e=>e.rrule).length,exdateEventCount:events.filter(e=>e.exdates.length).length,relatedCount:events.filter(e=>e.relatedTo).length,recurrenceIdCount:events.filter(e=>e.recurrenceId).length,firstDate:dates[0]||null,lastDate:dates.at(-1)||null};
}

async function body(request:Request){if(request.method!=='POST')throw new BadRequest('POST only');const size=Number(request.headers.get('content-length')||0);if(size>ICS_MAX_BYTES+200000)throw new BadRequest('リクエストが大きすぎます。');const b=await request.json().catch(()=>null) as any;if(!b)throw new BadRequest('JSONが不正です。');return b;}
function auth(ctx:AppContext,b:any){if(!ctx.member)throw new AuthRequired();if(!admin(ctx.member))throw new Forbidden('カレンダーインポートはOWNER / ADMINのみ行えます。');if(String(b.csrf||'')!==String(ctx.session.csrfToken||''))throw new Forbidden('CSRF tokenが不正です。');return ctx.member;}
function filtered(doc:IcsDocument,b:any,zone:string){const mode=String(b.range_mode||'all'),today=familyDate(zone),from=mode==='future'?today:mode==='date'?String(b.from_date||''):'' ,to=mode==='date'?String(b.to_date||''):'';if(mode==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to))throw new BadRequest('日付範囲が不正です。');return doc.events.filter(e=>(!from||e.endAt.slice(0,10)>=from)&&(!to||e.startDate<=to));}
async function existing(db:D1Database,fid:number,events:IcsEvent[]){const out=new Map<string,Row>();for(let i=0;i<events.length;i+=80){const part=events.slice(i,i+80),clauses=part.map(()=>'(source_uid=? AND source_recurrence_key=?)').join(' OR '),args=part.flatMap(e=>[e.uid,e.recurrenceId]);const rows=await db.prepare(`SELECT * FROM calendar_import_entries WHERE family_id=? AND source_format='ICS' AND (${clauses})`).bind(fid,...args).all<Row>();for(const r of rows.results)out.set(`${r.source_uid}\0${r.source_recurrence_key}`,r);}return out;}
const eventKey=(e:IcsEvent)=>`${e.uid}\0${e.recurrenceId}`;
export async function calendarImportPreview(request:Request,ctx:AppContext){const b=await body(request),m=auth(ctx,b),family=await ctx.env.DB.prepare('SELECT timezone FROM families WHERE id=?').bind(m.family_id).first<Row>(),zone=String(family?.timezone||DEFAULT_FAMILY_TIMEZONE);let doc;try{doc=await parseIcs(String(b.ics||''),zone);}catch(e){throw new BadRequest(String((e as Error).message||e));}const events=filtered(doc,b,zone),known=await existing(ctx.env.DB,m.family_id,events);let fresh=0,same=0,changed=0;const samples=events.slice(0,20).map(e=>{const old=known.get(eventKey(e)),classification=!old?'new':old.source_hash===e.sourceHash?'same':'changed';if(classification==='new')fresh++;else if(classification==='same')same++;else changed++;return {title:e.summary,date:e.startDate,all_day:e.allDay,classification,warnings:e.warnings};});for(const e of events.slice(20)){const old=known.get(eventKey(e));if(!old)fresh++;else if(old.source_hash===e.sourceHash)same++;else changed++;}return json({ok:true,name:doc.name,timezone:doc.timezone,family_timezone:zone,total:events.length,source_total:doc.events.length,all_day:events.filter(e=>e.allDay).length,timed:events.filter(e=>!e.allDay).length,recurring:events.filter(e=>e.rrule).length,exdate_events:events.filter(e=>e.exdates.length).length,related:events.filter(e=>e.relatedTo).length,recurrence_id:events.filter(e=>e.recurrenceId).length,alarms:events.reduce((n,e)=>n+e.alarmCount,0),period:{from:doc.firstDate,to:doc.lastDate},classification:{new:fresh,same,changed,unsupported:doc.errors.length},errors:doc.errors.slice(0,50),warnings:events.flatMap(e=>e.warnings.map(w=>`${e.summary}: ${w}`)).slice(0,50),samples});}

export async function calendarImportApply(request:Request,ctx:AppContext){const b=await body(request),m=auth(ctx,b),family=await ctx.env.DB.prepare('SELECT timezone FROM families WHERE id=?').bind(m.family_id).first<Row>(),zone=String(family?.timezone||DEFAULT_FAMILY_TIMEZONE),doc=await parseIcs(String(b.ics||''),zone),events=filtered(doc,b,zone);if(doc.errors.length)throw new BadRequest(`不正なVEVENTが${doc.errors.length}件あります。修正してから再実行してください。`);const fileHash=await sha(String(b.ics||'')),now=familyNow(zone);let batchId=Number(b.batch_id||0),offset=Number(b.offset||0);if(!batchId){const r=await ctx.env.DB.prepare("INSERT INTO calendar_import_batches(family_id,source_format,source_name,file_sha256,timezone,status,total_count,created_count,updated_count,skipped_count,error_count,processed_count,created_by,created_at) VALUES(?,'ICS',?,?,?,'IMPORTING',?,0,0,0,0,0,?,?)").bind(m.family_id,String(b.source_name||doc.name).slice(0,255),fileHash,doc.timezone||zone,events.length,m.id,now).run();batchId=Number(r.meta.last_row_id);offset=0;}const batch=await ctx.env.DB.prepare('SELECT * FROM calendar_import_batches WHERE id=? AND family_id=?').bind(batchId,m.family_id).first<Row>();if(!batch||String(batch.file_sha256)!==fileHash||String(batch.status)!=='IMPORTING'||Number(batch.processed_count)!==offset)throw new BadRequest('インポートbatchまたはoffsetが一致しません。');const part=events.slice(offset,offset+ICS_APPLY_CHUNK),known=await existing(ctx.env.DB,m.family_id,part);let created=0,skipped=0;
  for(const e of part){const old=known.get(eventKey(e));if(old){skipped++;continue;}const task=await ctx.env.DB.prepare("INSERT INTO tasks(family_id,title,description,due_at,status,completion_mode,created_by,created_at,updated_at,start_at,end_at,location,all_day,calendar_visible,calendar_color,task_kind,sort_order,visibility_scope,private_owner_id) VALUES(?,?,?,NULL,'pending','ANY',?,?,?,?,?,?,?,1,?,'EVENT',0,'FAMILY',NULL)").bind(m.family_id,e.summary,e.description||null,m.id,now,now,e.startAt,e.endAt,e.location||null,e.allDay?1:0,e.color).run();const taskId=Number(task.meta.last_row_id);let ruleId:null|number=null;if(e.rrule){const rr=e.rrule,type=rr.freq==='WEEKLY'?(rr.interval===1?'WEEKLY':'INTERVAL_WEEKS'):rr.freq==='MONTHLY'?'MONTHLY_DAY':'YEARLY';let until:string|null=null;if(rr.until){try{until=parseDateValue(rr.until,{},zone).date;}catch{throw new BadRequest(`UNTILが不正です: ${e.summary}`);}}const rule=await ctx.env.DB.prepare('INSERT INTO recurrence_rules(family_id,task_id,name,recurrence_type,interval_value,weekday,monthday,start_date,end_date,active,created_at,updated_at,week_number,business_day_ordinal,weekdays_json,monthdays_json,week_numbers_json) VALUES(?,?,?,?,?,?,?,?,?,1,?,?,?,?,?,?,?)').bind(m.family_id,taskId,e.summary,type,rr.interval,rr.weekdays[0]??null,rr.monthdays[0]??null,e.startDate,until,now,now,null,null,JSON.stringify(rr.weekdays),JSON.stringify(rr.monthdays),JSON.stringify([])).run();ruleId=Number(rule.meta.last_row_id);if(e.exdates.length)await ctx.env.DB.batch(e.exdates.map(d=>ctx.env.DB.prepare("INSERT OR IGNORE INTO recurrence_occurrences(family_id,recurrence_rule_id,occurrence_date,status,created_at,updated_at) VALUES(?,?,?,'excluded',?,?)").bind(m.family_id,ruleId,d,now,now)));}await ctx.env.DB.prepare("INSERT INTO calendar_import_entries(batch_id,family_id,source_format,source_uid,source_recurrence_id,source_recurrence_key,source_hash,task_id,recurrence_rule_id,related_to_uid,source_created,source_last_modified,imported_task_updated_at,imported_rule_updated_at,imported_at,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'ACTIVE')").bind(batchId,m.family_id,'ICS',e.uid,e.recurrenceId||null,e.recurrenceId,e.sourceHash,taskId,ruleId,e.relatedTo,e.created,e.lastModified,now,ruleId?now:null,now).run();created++;}
  const next=offset+part.length,done=next>=events.length;await ctx.env.DB.prepare(`UPDATE calendar_import_batches SET processed_count=?,created_count=created_count+?,skipped_count=skipped_count+?,status=?,applied_at=CASE WHEN ? THEN ? ELSE applied_at END WHERE id=? AND family_id=?`).bind(next,created,skipped,done?'COMPLETED':'IMPORTING',done?1:0,now,batchId,m.family_id).run();if(done)await ctx.env.DB.prepare("INSERT INTO activity_logs(family_id,member_id,action,target_type,target_id,metadata,occurred_at) VALUES(?,?,'CALENDAR_IMPORT','calendar_import_batch',?,?,?)").bind(m.family_id,m.id,batchId,JSON.stringify({batch_id:batchId,created_count:Number(batch.created_count||0)+created}),now).run();return json({ok:true,batch_id:batchId,processed_count:next,total_count:events.length,created_count:Number(batch.created_count||0)+created,skipped_count:Number(batch.skipped_count||0)+skipped,done,chunk_size:ICS_APPLY_CHUNK,google_projection:'not_enqueued',recurring_google_projection:'unsupported'});}

export async function calendarImportRollback(request:Request,ctx:AppContext){const b=await body(request),m=auth(ctx,b),id=Number(b.batch_id||0),batch=await ctx.env.DB.prepare('SELECT * FROM calendar_import_batches WHERE id=? AND family_id=?').bind(id,m.family_id).first<Row>();if(!batch)throw new BadRequest('batchが見つかりません。');const rows=await ctx.env.DB.prepare(`SELECT e.*,t.updated_at task_updated,r.updated_at rule_updated FROM calendar_import_entries e LEFT JOIN tasks t ON t.id=e.task_id AND t.family_id=e.family_id LEFT JOIN recurrence_rules r ON r.id=e.recurrence_rule_id AND r.family_id=e.family_id WHERE e.batch_id=? AND e.family_id=? AND e.status='ACTIVE'`).bind(id,m.family_id).all<Row>();const counts={deletable:0,edited:0,missing:0};for(const e of rows.results){if(!e.task_updated)counts.missing++;else if(String(e.task_updated)!==String(e.imported_task_updated_at)||(e.recurrence_rule_id&&String(e.rule_updated)!==String(e.imported_rule_updated_at)))counts.edited++;else counts.deletable++;}if(String(b.action||'preview')==='preview')return json({ok:true,...counts});const now=familyNow(String(m.family_timezone||DEFAULT_FAMILY_TIMEZONE));for(const e of rows.results){if(!e.task_updated){await ctx.env.DB.prepare("UPDATE calendar_import_entries SET status='MISSING' WHERE id=?").bind(e.id).run();continue;}if(String(e.task_updated)!==String(e.imported_task_updated_at)||(e.recurrence_rule_id&&String(e.rule_updated)!==String(e.imported_rule_updated_at))){await ctx.env.DB.prepare("UPDATE calendar_import_entries SET status='EDITED_KEPT' WHERE id=?").bind(e.id).run();continue;}if(e.recurrence_rule_id)await ctx.env.DB.batch([ctx.env.DB.prepare('DELETE FROM recurrence_occurrences WHERE family_id=? AND recurrence_rule_id=?').bind(m.family_id,e.recurrence_rule_id),ctx.env.DB.prepare('DELETE FROM recurrence_rules WHERE family_id=? AND id=?').bind(m.family_id,e.recurrence_rule_id)]);await ctx.env.DB.prepare('DELETE FROM tasks WHERE family_id=? AND id=?').bind(m.family_id,e.task_id).run();await ctx.env.DB.prepare("UPDATE calendar_import_entries SET status='ROLLED_BACK',task_id=NULL,recurrence_rule_id=NULL WHERE id=?").bind(e.id).run();}await ctx.env.DB.prepare("UPDATE calendar_import_batches SET status='ROLLED_BACK',rolled_back_at=? WHERE id=? AND family_id=?").bind(now,id,m.family_id).run();return json({ok:true,...counts});}

export async function calendarImportPage(ctx:AppContext){if(!ctx.member)throw new AuthRequired();if(!admin(ctx.member))throw new Forbidden('カレンダーインポートはOWNER / ADMINのみ行えます。');const batches=await ctx.env.DB.prepare('SELECT * FROM calendar_import_batches WHERE family_id=? ORDER BY id DESC LIMIT 30').bind(ctx.member.family_id).all<Row>(),history=batches.results.map(b=>`<div class="import-history-row"><div><strong>${esc(b.source_name)}</strong><div class="small">${esc(b.status)} ・ 全${b.total_count} ・ 新規${b.created_count} ・ スキップ${b.skipped_count}</div><div class="meta">${esc(b.created_at)}</div></div>${b.status==='COMPLETED'?`<button class="btn danger small calendar-import-rollback" data-id="${b.id}">取り消す</button>`:''}</div>`).join('')||'<p class="empty">履歴はありません。</p>';const payload=JSON.stringify({csrf:ctx.session.csrfToken||'',maxBytes:ICS_MAX_BYTES,chunkSize:ICS_APPLY_CHUNK}).replaceAll('<','\\u003c');const bodyHtml=`<div class="page-head"><div><div class="eyebrow">管理</div><h1>📅 ICSカレンダーをインポート</h1></div><a class="btn gray" href="/app/settings.php">戻る</a></div><div class="notice">ICS → Family TODO D1 が正規ルートです。原本ファイルとVALARM通知は保存・作成しません（最大2 MiB / 5,000予定）。</div><div class="card import-wizard"><label>.icsファイル</label><input id="calendarImportFile" type="file" accept="text/calendar,.ics"><label>期間</label><select id="calendarImportRange"><option value="all">全期間</option><option value="future">今日以降のみ</option><option value="date">日付指定</option></select><div id="calendarImportDates" class="date-grid" hidden><input id="calendarImportFrom" type="date"><input id="calendarImportTo" type="date"></div><button id="calendarImportPreview" type="button">内容を確認</button><div id="calendarImportStatus" aria-live="polite" class="small"></div><div id="calendarImportOutput"></div></div><div class="card"><h2>インポート履歴</h2>${history}</div><script type="application/json" id="calendarImportPayload">${payload}</script><script src="/assets/calendar-import.js?v=12.127.0-wave108"></script>`;return html(layout('ICSカレンダーをインポート',bodyHtml,'/app/settings.php'));}
