import { toggle } from './toggle-api';
import { createFamily } from './family-create-api';
import { joinFamily } from './family-join-api';
import { inviteCreate } from './family-invite-api';
import { apiMe } from './api-me';
import { taskApi } from './task-api';
import { taskChildrenApi } from './task-children-api';
import { taskRoughInputApi } from './task-rough-input-api';
import { itemApi } from './item-api';
import { childJournalApi } from './child-journal';
import { calendarStampReadApi } from './calendar-stamp-api';
import { calendarStampOptionsApi,calendarStampPlacementApi } from './calendar-stamp-placement-api';
import { calendarStampAdminAssetsApi,calendarStampPngSequenceAdminApi } from './calendar-stamp-admin-api';
import { calendarStampMediaReadApi,calendarStampMediaUploadApi } from './calendar-stamp-media-api';
import { calendarSharedStampCatalogAdminApi } from './calendar-shared-stamp-api';
import { calendarSharedStampPublishAdminApi } from './calendar-shared-stamp-publish-api';
import { messageStampApi } from './message-stamp-api';
import { familyAiQuery, familyAiPlan, familyAiExecute, familyAiConnectionTest, familyAiModelProbe, familyAiModelCatalog, familyAiModelCompatibility, familyAiModelSelect, familyAiModelReset } from './family-ai';
import { googleTasksAction } from './google-tasks';
import { calendarBackfill, calendarDisconnect, calendarRetryFailed } from './google-calendar';
import { calendarSyncOutboundOnly } from './google-calendar-one-way';
import { familyLogImportMediaBoundary as familyLogImportApi } from './family-log-import-media-boundary';
import { familyLogMutationBoundary } from './family-log-mutation-boundary';
import { familyLogMediaApi } from './family-log-media-api';
import { recordOccurrenceFamilyLog } from './family-log-occurrence-api';
import { calendarImportPreview, calendarImportNormalizationPreview, calendarImportPrepare, calendarImportStatus, calendarImportApply, calendarImportRollback } from './calendar-ics-import';
import { settingsDiagnosticsDetail } from './settings-diagnostics';
import { webPushApi } from './web-push-api';
import { messages } from './messages-api';
import { settings } from './settings-root';
import { shopping } from './shopping-root';
import { shoppingCategoryApi } from './shopping-category-api';
import { locationDeviceApi } from './location-device-api';
import { locationLatestApi } from './location-latest-api';
import { locationRouteEtaApi } from './location-route-api';
import { locationHomeApi } from './location-home-api';

export async function dispatchContextApiRoute(request:Request,context:any,url:URL):Promise<Response|null>{
  if(url.pathname==='/api/family/create') return await createFamily(request,context);
  if(url.pathname==='/api/family/join') return await joinFamily(request,context);
  if(url.pathname==='/api/family/invite') return await inviteCreate(request,context);
  if(url.pathname==='/api/me') return await apiMe(context);
  if(url.pathname==='/api/toggle') return await toggle(request,context);
  if(url.pathname==='/api/task') return await taskApi(request,context);
  if(url.pathname==='/api/task-children') return await taskChildrenApi(request,context);
  if(url.pathname==='/api/task-rough-input') return await taskRoughInputApi(request,context);
  if(url.pathname==='/api/item') return await itemApi(request,context);
  if(url.pathname==='/api/messages') return await messages(request,context);
  if(url.pathname==='/api/message-stamps') return await messageStampApi(request,context);
  if(url.pathname==='/api/shopping') return await shopping(request,context);
  if(url.pathname==='/api/shopping-categories') return await shoppingCategoryApi(request,context);
  if(url.pathname==='/api/location/devices') return await locationDeviceApi(request,context);
  if(url.pathname==='/api/location/latest') return await locationLatestApi(request,context);
  if(url.pathname==='/api/location/eta') return await locationRouteEtaApi(request,context);
  if(url.pathname==='/api/location/home') return await locationHomeApi(request,context);
  if(url.pathname==='/api/family-log') return await familyLogMutationBoundary(request,context);
  if(url.pathname==='/api/family-log-media') return await familyLogMediaApi(request,context);
  if(url.pathname==='/api/child-journal') return await childJournalApi(request,context);
  if(url.pathname==='/api/calendar-stamps') return await calendarStampReadApi(request,context.env,{familyId:Number(context.member?.family_id||0),memberId:Number(context.member?.id||0)});
  if(url.pathname==='/api/calendar-stamp-options') return await calendarStampOptionsApi(request,context);
  if(url.pathname==='/api/calendar-stamp-placement') return await calendarStampPlacementApi(request,context);
  if(url.pathname==='/api/calendar-stamp-media') return await calendarStampMediaReadApi(request,context);
  if(url.pathname==='/api/calendar-stamp-admin/assets') return await calendarStampAdminAssetsApi(request,context);
  if(url.pathname==='/api/calendar-stamp-admin/shared-catalog') return await calendarSharedStampCatalogAdminApi(request,context);
  if(url.pathname==='/api/calendar-stamp-admin/shared-publish') return await calendarSharedStampPublishAdminApi(request,context);
  if(url.pathname==='/api/calendar-stamp-admin/upload') return await calendarStampMediaUploadApi(request,context);
  if(url.pathname==='/api/calendar-stamp-admin/png-sequence') return await calendarStampPngSequenceAdminApi(request,context);
  if(url.pathname==='/api/family-ai/query') return await familyAiQuery(request,context);
  if(url.pathname==='/api/family-ai/plan') return await familyAiPlan(request,context);
  if(url.pathname==='/api/family-ai/execute') return await familyAiExecute(request,context);
  if(url.pathname==='/api/family-ai/connection-test') return await familyAiConnectionTest(request,context);
  if(url.pathname==='/api/family-ai/model-probe') return await familyAiModelProbe(request,context);
  if(url.pathname==='/api/family-ai/model-catalog') return await familyAiModelCatalog(request,context);
  if(url.pathname==='/api/family-ai/model-compatibility') return await familyAiModelCompatibility(request,context);
  if(url.pathname==='/api/family-ai/model-select') return await familyAiModelSelect(request,context);
  if(url.pathname==='/api/family-ai/model-reset') return await familyAiModelReset(request,context);
  if(url.pathname==='/api/settings/diagnostics-detail') return await settingsDiagnosticsDetail(request,context);
  if(url.pathname==='/api/google-tasks/action') return await googleTasksAction(request,context);
  if(url.pathname==='/api/google-calendar/sync') return await calendarSyncOutboundOnly(request,context);
  if(url.pathname==='/api/google-calendar/backfill') return await calendarBackfill(request,context);
  if(url.pathname==='/api/google-calendar/disconnect') return await calendarDisconnect(request,context);
  if(url.pathname==='/api/google-calendar/retry-failed') return await calendarRetryFailed(request,context);
  if(url.pathname==='/api/family-log-import') return await familyLogImportApi(request,context);
  if(url.pathname==='/api/calendar-import/preview') return await calendarImportPreview(request,context);
  if(url.pathname==='/api/calendar-import/normalization-preview') return await calendarImportNormalizationPreview(request,context);
  if(url.pathname==='/api/calendar-import/prepare') return await calendarImportPrepare(request,context);
  if(url.pathname==='/api/calendar-import/status') return await calendarImportStatus(request,context);
  if(url.pathname==='/api/calendar-import/apply') return await calendarImportApply(request,context);
  if(url.pathname==='/api/calendar-import/rollback') return await calendarImportRollback(request,context);
  if(url.pathname==='/api/recurrence/family-log-complete') return await recordOccurrenceFamilyLog(request,context);
  if(url.pathname==='/api/settings') return await settings(request,context);
  if(url.pathname==='/api/push/subscribe'||url.pathname==='/api/push/unsubscribe'||url.pathname==='/api/push/test') return await webPushApi(request,context);
  return null;
}
