import type { AppContext } from './app-context';
import { BadRequest, Forbidden } from './errors';
import { normalizeMilkAmountPresets, recordQuickChoreDomain, startDedicatedSleepDomain, stopDedicatedSleepDomain } from './family-external-domain';
import { bodyJson as parseBody, RequestBodyParseError } from './request-body';
import { json } from './response';
import { logActivity } from './activity-log';
import { completeLinkedTargetFromFamilyLog } from './family-log-linked-completion';
import { FAMILY_LOG_TYPE_META } from './family-log-type-meta';
import { requestGoogleHomeSyncForFamily } from './google-home-request-sync';

async function legacyFamilyLog(request:Request,ctx:AppContext):Promise<Response>{
  const { familyLogPage }=await import('./family-log-page');
  return familyLogPage(request,ctx);
}

type Row=Record<string,unknown>;
const FAMILY_LOG_TYPES=Object.keys(FAMILY_LOG_TYPE_META);
const FAMILY_LOG_SUBJECT_TYPES=FAMILY_LOG_TYPES.filter(type=>type!=='HOUSEWORK'&&type!=='TIMER');
const FAMILY_LOG_SUBJECT_META:Record<string,{icon:string;label:string}>={
  BABY:{icon:'👶',label:'赤ちゃん'},CHILD:{icon:'🧒',label:'子ども'},ADULT:{icon:'👤',label:'大人'},PET:{icon:'🐾',label:'ペット'},OTHER:{icon:'⭐',label:'その他'}
};
const FAMILY_LOG_DEFAULT_TYPES:Record<string,string[]>={
  BABY:['MILK','BREASTFEED','MEAL','DIAPER','SLEEP','BATH','TEMPERATURE','MEDICINE','VACCINE','HEIGHT','WEIGHT','CONDITION','MEMO'],
  CHILD:['MEAL','TOILET','SLEEP','BATH','TEMPERATURE','MEDICINE','VACCINE','HEIGHT','WEIGHT','CONDITION','EXERCISE','MEMO'],
  ADULT:['CONDITION','SLEEP','EXERCISE','WEIGHT','BLOOD_PRESSURE','TEMPERATURE','MEDICINE','MEAL','BATH','MEMO'],
  PET:['MEAL','WATER','TOILET','WALK','SLEEP','BATH','WEIGHT','MEDICINE','CONDITION','MEMO'],
  OTHER:['MEMO','CONDITION','TEMPERATURE','MEDICINE','SLEEP','WEIGHT']
};
const SLEEP_TIMER_MAX_ADJUST_MINUTES=48*60;
const nowJst=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date());
function familyLogSubjectKind(value:unknown){const kind=String(value||'ADULT').toUpperCase();return Object.prototype.hasOwnProperty.call(FAMILY_LOG_SUBJECT_META,kind)?kind:'OTHER';}
function familyLogDefaultTypes(kind:unknown){return [...(FAMILY_LOG_DEFAULT_TYPES[familyLogSubjectKind(kind)]||FAMILY_LOG_DEFAULT_TYPES.OTHER)];}
function familyLogEnabledTypes(subject:Row|undefined|null){
  if(!subject)return [...FAMILY_LOG_TYPES];
  const raw=String(subject.enabled_types_json||'').trim();
  if(raw){try{const parsed=JSON.parse(raw);if(Array.isArray(parsed)){const out=[...new Set(parsed.map(x=>String(x||'').toUpperCase()).filter(x=>FAMILY_LOG_SUBJECT_TYPES.includes(x)))];if(out.length)return out;}}catch{}}
  return familyLogDefaultTypes(subject.subject_kind);
}
function familyLogDefaultAutoComplete(kind:unknown){return ['BABY','CHILD','PET'].includes(familyLogSubjectKind(kind))?1:0;}
function familyLogTruthy(value:unknown,fallback=false){if(value===undefined||value===null||value==='')return fallback;if(typeof value==='boolean')return value;return ['1','true','on','yes'].includes(String(value).toLowerCase());}
function familyQuickChoreWeekdayMask(value:unknown){const mask=Number(value??127);if(!Number.isInteger(mask)||mask<0||mask>127)throw new BadRequest('表示曜日が不正です。');return mask;}
function familyLogDateTime(value:unknown){const raw=String(value??'').trim().replace('T',' ');if(!/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}(?::\d{2})?$/.test(raw))throw new BadRequest('記録日時が不正です。');return raw.length===16?`${raw}:00`:raw;}
function familyLogJstMs(value:unknown){const normalized=familyLogDateTime(value);return Date.parse(`${normalized.replace(' ','T')}+09:00`);}
async function bodyJson(request:Request){try{return await parseBody(request);}catch(error){if(error instanceof RequestBodyParseError)throw new BadRequest(error.message);throw error;}}
async function ensureCsrf(ctx:AppContext,token:unknown){if(!ctx.session.csrfToken)ctx.session.csrfToken=crypto.randomUUID();if(typeof token!=='string'||token!==ctx.session.csrfToken)throw new Forbidden('CSRF検証に失敗しました。');}

export async function familyLogApi(request:Request,ctx:AppContext):Promise<Response>{
  // Preserve the historical GET compatibility until the server-rendered Family Log page is extracted.
  if(request.method!=='POST'||!ctx.member)return legacyFamilyLog(request,ctx);
  const m=ctx.member;
  const role=String(m.role||'').toUpperCase();
  const delegated=await ctx.env.DB.prepare("SELECT 1 ok FROM member_permissions WHERE family_id=? AND member_id=? AND permission_key='MANAGE_QUICK_CHORES'").bind(m.family_id,m.id).first<Row>();
  const isAdmin=role==='OWNER'||role==='ADMIN',canManageQuickChores=isAdmin||Boolean(delegated);
  const b=await bodyJson(request);await ensureCsrf(ctx,b.csrf);const action=String(b.action||'save');

  if(action==='settings_update'){
    if(!isAdmin)return json({ok:false,error:'表示設定はOWNER / ADMINのみ変更できます。'},403);
    const showAdultLogs=familyLogTruthy(b.show_adult_logs,true)?1:0,now=nowJst(),milkPresets=normalizeMilkAmountPresets(b.milk_amount_presets);
    await ctx.env.DB.batch([
      ctx.env.DB.prepare(`INSERT INTO family_log_settings(family_id,show_adult_logs,created_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(family_id) DO UPDATE SET show_adult_logs=excluded.show_adult_logs,updated_at=excluded.updated_at`).bind(m.family_id,showAdultLogs,now,now),
      ctx.env.DB.prepare(`INSERT INTO family_settings(family_id,setting_key,setting_value,updated_at) VALUES(?,?,?,?) ON CONFLICT(family_id,setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_at=excluded.updated_at`).bind(m.family_id,'family_log_milk_amount_presets',JSON.stringify(milkPresets),now)
    ]);
    await logActivity(ctx,'UPDATED','family_log_settings',m.family_id,{show_adult_logs:showAdultLogs,milk_amount_presets:milkPresets});
    return json({ok:true,show_adult_logs:Boolean(showAdultLogs),milk_amount_presets:milkPresets});
  }

  const quickChoreManagement=['quick_chore_add','quick_chore_update','quick_chore_remove','quick_chore_restore','quick_chore_reorder'];
  if(quickChoreManagement.includes(action)&&!canManageQuickChores)return json({ok:false,error:'ちょこっと家事の項目編集権限が必要です。'},403);
  if(action==='quick_chore_add'){
    const name=String(b.name||'').trim();if(!name||Array.from(name).length>8)throw new BadRequest('家事の名前は8文字以内がおすすめです。');
    const icon=String(b.icon||'✨').trim().slice(0,8)||'✨',weekdayMask=familyQuickChoreWeekdayMask(b.weekday_mask),now=nowJst();
    const order=await ctx.env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+1 n FROM family_quick_chores WHERE family_id=?').bind(m.family_id).first<Row>();
    const r=await ctx.env.DB.prepare('INSERT INTO family_quick_chores(family_id,name,icon,sort_order,active,created_by,created_at,updated_at,weekday_mask) VALUES(?,?,?,?,1,?,?,?,?)').bind(m.family_id,name,icon,Number(order?.n||1),m.id,now,now,weekdayMask).run();
    const id=Number(r.meta.last_row_id);await logActivity(ctx,'CREATED','family_quick_chore',id,{name,icon,weekday_mask:weekdayMask});return json({ok:true,id});
  }
  if(action==='quick_chore_update'){
    const id=Number(b.id||0),name=String(b.name||'').trim(),icon=String(b.icon||'✨').trim().slice(0,8)||'✨',weekdayMask=familyQuickChoreWeekdayMask(b.weekday_mask);if(!id)throw new BadRequest('家事項目が不正です。');if(!name||Array.from(name).length>8)throw new BadRequest('家事の名前は8文字以内がおすすめです。');
    const result=await ctx.env.DB.prepare('UPDATE family_quick_chores SET name=?,icon=?,weekday_mask=?,updated_at=? WHERE id=? AND family_id=?').bind(name,icon,weekdayMask,nowJst(),id,m.family_id).run();if(!result.meta.changes)return json({ok:false,error:'家事項目が見つかりません。'},404);await logActivity(ctx,'UPDATED','family_quick_chore',id,{name,icon,weekday_mask:weekdayMask});return json({ok:true,id});
  }
  if(action==='quick_chore_restore'){
    const id=Number(b.id||0);if(!id)throw new BadRequest('家事項目が不正です。');const result=await ctx.env.DB.prepare('UPDATE family_quick_chores SET active=1,sort_order=(SELECT COALESCE(MAX(sort_order),0)+1 FROM family_quick_chores WHERE family_id=? AND active=1),updated_at=? WHERE id=? AND family_id=? AND active=0').bind(m.family_id,nowJst(),id,m.family_id).run();if(!result.meta.changes)return json({ok:false,error:'非表示の家事項目が見つかりません。'},404);await logActivity(ctx,'RESTORED','family_quick_chore',id,{});return json({ok:true,id});
  }
  if(action==='quick_chore_reorder'){
    const ids=Array.isArray(b.ids)?(b.ids as unknown[]).map(Number).filter(id=>id>0):[],rows=await ctx.env.DB.prepare('SELECT id FROM family_quick_chores WHERE family_id=? AND active=1 ORDER BY sort_order,id').bind(m.family_id).all<Row>(),current=rows.results.map(x=>Number(x.id));if(ids.length!==current.length||new Set(ids).size!==ids.length||ids.some(id=>!current.includes(id)))throw new BadRequest('並べ替え対象が最新ではありません。画面を再読み込みしてください。');const now=nowJst();await ctx.env.DB.batch(ids.map((id,index)=>ctx.env.DB.prepare('UPDATE family_quick_chores SET sort_order=?,updated_at=? WHERE id=? AND family_id=?').bind(index+1,now,id,m.family_id)));await logActivity(ctx,'UPDATED','family_quick_chore',null,{operation:'reorder',ids});return json({ok:true});
  }
  if(action==='quick_chore_remove'){
    const id=Number(b.id||0);if(!id)throw new BadRequest('家事項目が不正です。');const now=nowJst(),row=await ctx.env.DB.prepare('SELECT id,name FROM family_quick_chores WHERE id=? AND family_id=? AND active=1').bind(id,m.family_id).first<Row>();if(!row)return json({ok:false,error:'家事項目が見つかりません。'},404);await ctx.env.DB.prepare('UPDATE family_quick_chores SET active=0,updated_at=? WHERE id=? AND family_id=?').bind(now,id,m.family_id).run();await logActivity(ctx,'DISABLED','family_quick_chore',id,{name:String(row.name||'')});return json({ok:true});
  }
  if(action==='quick_chore_record'){
    const result=await recordQuickChoreDomain(ctx.env,m,Number(b.id||0));return result.ok?json(result):json({ok:false,error:'家事項目が見つかりません。'},404);
  }

  if(action==='subject_create'||action==='subject_update'){
    const id=action==='subject_update'?Number(b.id||0):0,name=String(b.name||'').trim();if(!name||name.length>80)throw new BadRequest('対象の名前を80文字以内で入力してください。');const kind=familyLogSubjectKind(b.subject_kind||'BABY'),birth=String(b.birth_date||'').trim()||null;if(birth&&!/^\d{4}-\d{2}-\d{2}$/.test(birth))throw new BadRequest('生年月日が不正です。');
    const enabledInput=Array.isArray(b.enabled_types)?b.enabled_types as unknown[]:familyLogDefaultTypes(kind),enabled=[...new Set(enabledInput.map(x=>String(x||'').toUpperCase()).filter(x=>FAMILY_LOG_SUBJECT_TYPES.includes(x)))];if(!enabled.length)throw new BadRequest('表示する記録項目を1つ以上選択してください。');const enabledJson=JSON.stringify(enabled),showOnOverview=familyLogTruthy(b.show_on_family_overview,false)?1:0,overviewInput=Array.isArray(b.overview_quick_types)?b.overview_quick_types as unknown[]:[],overviewTypes=[...new Set(overviewInput.map(x=>String(x||'').toUpperCase()).filter(x=>enabled.includes(x)))],overviewJson=showOnOverview?JSON.stringify(overviewTypes):null,autoComplete=familyLogTruthy(b.auto_complete_linked_task,familyLogDefaultAutoComplete(kind)===1)?1:0,now=nowJst();
    if(id){const current=await ctx.env.DB.prepare('SELECT id,member_id FROM family_log_subjects WHERE id=? AND family_id=? AND active=1').bind(id,m.family_id).first<Row>();if(!current)return json({ok:false,error:'記録対象が見つかりません。'},404);await ctx.env.DB.prepare('UPDATE family_log_subjects SET name=?,subject_kind=?,birth_date=?,enabled_types_json=?,auto_complete_linked_task=?,show_on_family_overview=?,overview_quick_types_json=?,updated_at=? WHERE id=? AND family_id=? AND active=1').bind(name,kind,birth,enabledJson,autoComplete,showOnOverview,overviewJson,now,id,m.family_id).run();const linkedMemberId=Number(current.member_id||0);if(linkedMemberId){const linkedMemberType=['BABY','CHILD'].includes(kind)?'CHILD':'ADULT';await ctx.env.DB.prepare('UPDATE members SET member_type=?,updated_at=? WHERE id=? AND family_id=? AND deleted_at IS NULL').bind(linkedMemberType,now,linkedMemberId,m.family_id).run();}await logActivity(ctx,'UPDATED','family_log_subject',id,{name,subject_kind:kind,enabled_types:enabled,show_on_family_overview:showOnOverview,overview_quick_types:overviewTypes,auto_complete_linked_task:autoComplete,linked_member_id:linkedMemberId||null});return json({ok:true,id});}
    const memberId=Number(b.member_id||0)||null;if(memberId){const member=await ctx.env.DB.prepare('SELECT id FROM members WHERE id=? AND family_id=? AND active=1').bind(memberId,m.family_id).first<Row>();if(!member)throw new BadRequest('連携するメンバーが見つかりません。');const existing=await ctx.env.DB.prepare('SELECT id FROM family_log_subjects WHERE family_id=? AND member_id=? LIMIT 1').bind(m.family_id,memberId).first<Row>();if(existing)throw new BadRequest('この家族メンバーはすでに家族ログ対象として表示されています。');}
    const r=await ctx.env.DB.prepare('INSERT INTO family_log_subjects(family_id,member_id,name,subject_kind,birth_date,icon,active,created_by,created_at,updated_at,enabled_types_json,auto_complete_linked_task,show_on_family_overview,overview_quick_types_json) VALUES(?,?,?,?,?,?,1,?,?,?,?,?,?,?)').bind(m.family_id,memberId,name,kind,birth,null,m.id,now,now,enabledJson,autoComplete,showOnOverview,overviewJson).run();const newId=Number(r.meta.last_row_id);await logActivity(ctx,'CREATED','family_log_subject',newId,{name,subject_kind:kind,enabled_types:enabled,auto_complete_linked_task:autoComplete});return json({ok:true,id:newId});
  }
  if(action==='subject_disable'){
    const id=Number(b.id||0);if(!id)throw new BadRequest('記録対象が不正です。');const current=await ctx.env.DB.prepare('SELECT id,member_id FROM family_log_subjects WHERE id=? AND family_id=? AND active=1').bind(id,m.family_id).first<Row>();if(!current)return json({ok:false,error:'記録対象が見つかりません。'},404);if(Number(current.member_id||0)>0)throw new BadRequest('家族メンバー連携の対象は非表示にできません。メンバー管理で停止してください。');const now=nowJst();await ctx.env.DB.prepare('UPDATE family_log_subjects SET active=0,updated_at=? WHERE id=? AND family_id=?').bind(now,id,m.family_id).run();await ctx.env.DB.prepare("UPDATE family_log_timers SET status='cancelled',updated_at=? WHERE subject_id=? AND family_id=? AND status='running'").bind(now,id,m.family_id).run();await logActivity(ctx,'DISABLED','family_log_subject',id,{});return json({ok:true});
  }

  if(action==='execute_quick_action'){
    const quickActionId=Number(b.quick_action_id||0);if(!quickActionId)throw new BadRequest('クイック記録が不正です。');const qa=await ctx.env.DB.prepare(`SELECT q.*,s.enabled_types_json,s.subject_kind FROM family_log_quick_actions q JOIN family_log_subjects s ON s.id=q.subject_id AND s.family_id=q.family_id AND s.active=1 WHERE q.id=? AND q.family_id=? AND q.active=1 LIMIT 1`).bind(quickActionId,m.family_id).first<Row>();if(!qa)throw new BadRequest('クイック記録が見つかりません。');const mode=String(qa.mode),type=String(qa.log_type||'');if(mode!=='QUICK')throw new BadRequest('このクイック記録は直接実行できません。');if(!FAMILY_LOG_TYPES.includes(type)||!familyLogEnabledTypes(qa).includes(type))throw new BadRequest('記録種類を利用できません。');const allowed:Record<string,string[]>={DIAPER:['WET','DIRTY','BOTH'],MEAL:['BREAKFAST','LUNCH','DINNER','SNACK','BABY_FOOD','OTHER'],BATH:['BATH','SHOWER'],CONDITION:['GOOD','NORMAL','TIRED','SICK','VOMIT']},detail=String(qa.detail_code||'')||null;if(detail&&allowed[type]&&!allowed[type].includes(detail))throw new BadRequest('詳細区分が不正です。');const amount=qa.amount===null?null:Number(qa.amount);if(amount!==null&&(!Number.isFinite(amount)||amount<-100000||amount>100000))throw new BadRequest('値が不正です。');const now=nowJst(),inserted=await ctx.env.DB.prepare('INSERT INTO family_logs(family_id,subject_id,log_type,occurred_at,detail_code,amount,unit,duration_minutes,value_text,note,linked_task_id,linked_occurrence_id,created_by,created_at,updated_at,deleted_at) VALUES(?,?,?,?,?,?,?,NULL,?,NULL,NULL,NULL,?,?,?,NULL)').bind(m.family_id,Number(qa.subject_id),type,now,detail,amount,qa.unit||null,qa.value_text||null,m.id,now,now).run(),id=Number(inserted.meta.last_row_id);await logActivity(ctx,'CREATED','family_log',id,{quick_action_id:quickActionId,log_type:type,subject_id:Number(qa.subject_id)});return json({ok:true,id,message:`${String(qa.name)}を記録しました`});
  }
  if(action==='quick_action_save'){
    if(!isAdmin)throw new Forbidden('管理者権限が必要です。');const id=Number(b.id||0),subjectId=Number(b.subject_id||0),mode=String(b.mode||'QUICK').toUpperCase(),type=String(b.log_type||'').toUpperCase(),name=String(b.name||'').trim().slice(0,40),icon=String(b.icon||'').trim().slice(0,16);if(!name||!['QUICK','FORM','SLEEP_TOGGLE'].includes(mode))throw new BadRequest('クイック記録の設定が不正です。');const subject=await ctx.env.DB.prepare('SELECT id,enabled_types_json FROM family_log_subjects WHERE id=? AND family_id=? AND active=1').bind(subjectId,m.family_id).first<Row>();if(!subject)throw new BadRequest('対象が見つかりません。');if(mode!=='SLEEP_TOGGLE'&&(!FAMILY_LOG_TYPES.includes(type)||!familyLogEnabledTypes(subject).includes(type)))throw new BadRequest('記録種類が不正です。');const detail=String(b.detail_code||'').trim().toUpperCase()||null,amount=String(b.amount??'').trim()===''?null:Number(b.amount),unit=String(b.unit||'').trim().slice(0,16)||null,value=String(b.value_text||'').trim().slice(0,255)||null,now=nowJst();if(amount!==null&&(!Number.isFinite(amount)||amount<-100000||amount>100000))throw new BadRequest('値が不正です。');
    if(id){const old=await ctx.env.DB.prepare('SELECT id FROM family_log_quick_actions WHERE id=? AND family_id=?').bind(id,m.family_id).first<Row>();if(!old)throw new BadRequest('クイック記録が見つかりません。');await ctx.env.DB.prepare('UPDATE family_log_quick_actions SET name=?,icon=?,mode=?,log_type=?,detail_code=?,amount=?,unit=?,value_text=?,active=?,updated_at=? WHERE id=? AND family_id=?').bind(name,icon||null,mode,mode==='SLEEP_TOGGLE'?'SLEEP':type,detail,amount,unit,value,b.active===false?0:1,now,id,m.family_id).run();await requestGoogleHomeSyncForFamily(ctx.env,m.family_id);return json({ok:true,id,message:'Google Homeの操作一覧も更新します'});}
    const order=Number((await ctx.env.DB.prepare('SELECT COALESCE(MAX(sort_order),-1)+1 n FROM family_log_quick_actions WHERE family_id=? AND subject_id=?').bind(m.family_id,subjectId).first<Row>())?.n||0),r=await ctx.env.DB.prepare('INSERT INTO family_log_quick_actions(family_id,subject_id,name,icon,mode,log_type,detail_code,amount,unit,value_text,sort_order,active,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,1,?,?,?)').bind(m.family_id,subjectId,name,icon||null,mode,mode==='SLEEP_TOGGLE'?'SLEEP':type,detail,amount,unit,value,order,m.id,now,now).run();await requestGoogleHomeSyncForFamily(ctx.env,m.family_id);return json({ok:true,id:Number(r.meta.last_row_id),message:'Google Homeの操作一覧も更新します'});
  }
  if(action==='quick_action_reorder'){
    if(!isAdmin)throw new Forbidden('管理者権限が必要です。');const id=Number(b.id||0),direction=String(b.direction||''),current=await ctx.env.DB.prepare('SELECT id,subject_id,sort_order FROM family_log_quick_actions WHERE id=? AND family_id=? AND active=1').bind(id,m.family_id).first<Row>();if(!current||!['up','down'].includes(direction))throw new BadRequest('並べ替えが不正です。');const op=direction==='up'?'<':'>',order=direction==='up'?'DESC':'ASC',neighbor=await ctx.env.DB.prepare(`SELECT id,sort_order FROM family_log_quick_actions WHERE family_id=? AND subject_id=? AND active=1 AND sort_order ${op} ? ORDER BY sort_order ${order},id ${order} LIMIT 1`).bind(m.family_id,current.subject_id,current.sort_order).first<Row>();if(neighbor)await ctx.env.DB.batch([ctx.env.DB.prepare('UPDATE family_log_quick_actions SET sort_order=?,updated_at=? WHERE id=? AND family_id=?').bind(neighbor.sort_order,nowJst(),current.id,m.family_id),ctx.env.DB.prepare('UPDATE family_log_quick_actions SET sort_order=?,updated_at=? WHERE id=? AND family_id=?').bind(current.sort_order,nowJst(),neighbor.id,m.family_id)]);await requestGoogleHomeSyncForFamily(ctx.env,m.family_id);return json({ok:true});
  }
  if(action==='quick_action_disable'){
    if(!isAdmin)throw new Forbidden('管理者権限が必要です。');await ctx.env.DB.prepare('UPDATE family_log_quick_actions SET active=0,updated_at=? WHERE id=? AND family_id=?').bind(nowJst(),Number(b.id||0),m.family_id).run();await requestGoogleHomeSyncForFamily(ctx.env,m.family_id);return json({ok:true});
  }

  if(action==='quick_record'){
    const subjectId=Number(b.subject_id||0),quickKey=String(b.quick_key||'').toUpperCase(),subject=await ctx.env.DB.prepare('SELECT id,name,subject_kind,enabled_types_json FROM family_log_subjects WHERE id=? AND family_id=? AND active=1').bind(subjectId,m.family_id).first<Row>();if(!subject||familyLogSubjectKind(subject.subject_kind)!=='BABY')throw new BadRequest('有効な赤ちゃんの記録対象を選択してください。');const mapping:Record<string,{type:string;detail:string|null;label:string}>={PEE:{type:'DIAPER',detail:'WET',label:'おしっこ'},POOP:{type:'DIAPER',detail:'DIRTY',label:'うんち'},BABY_FOOD:{type:'MEAL',detail:'BABY_FOOD',label:'離乳食'},BATH:{type:'BATH',detail:'BATH',label:'お風呂'},VOMIT:{type:'CONDITION',detail:'VOMIT',label:'吐いた'},MILK:{type:'MILK',detail:null,label:'ミルク'}},mapped=mapping[quickKey];if(!mapped)throw new BadRequest('クイック記録の種類が不正です。');if(!familyLogEnabledTypes(subject).includes(mapped.type))throw new BadRequest('この対象では記録種類が有効ではありません。');let amount:number|null=null,unit:string|null=null;if(quickKey==='MILK'){amount=Number(b.milk_amount);const setting=await ctx.env.DB.prepare("SELECT setting_value FROM family_settings WHERE family_id=? AND setting_key='family_log_milk_amount_presets'").bind(m.family_id).first<Row>();let presets=[160,240];if(setting?.setting_value){try{presets=normalizeMilkAmountPresets(JSON.parse(String(setting.setting_value)));}catch{}}if(!Number.isInteger(amount)||!presets.includes(amount))throw new BadRequest('設定されていないミルク量です。');unit='ml';}const now=nowJst(),inserted=await ctx.env.DB.prepare('INSERT INTO family_logs(family_id,subject_id,log_type,occurred_at,detail_code,amount,unit,duration_minutes,value_text,note,linked_task_id,linked_occurrence_id,created_by,created_at,updated_at,deleted_at) VALUES(?,?,?,?,?,?,?,NULL,NULL,NULL,NULL,NULL,?,?,?,NULL)').bind(m.family_id,subjectId,mapped.type,now,mapped.detail,amount,unit,m.id,now,now).run(),id=Number(inserted.meta.last_row_id);await logActivity(ctx,'CREATED','family_log',id,{quick_record:true,log_type:mapped.type,detail_code:mapped.detail,amount,unit,subject_id:subjectId});return json({ok:true,id,message:quickKey==='MILK'?`ミルク ${amount}ml を記録しました`:`${mapped.label}を記録しました`});
  }

  if(action==='save'){
    const id=Number(b.id||0)||0;let subjectId=Number(b.subject_id||0)||null;const type=String(b.log_type||'').toUpperCase();if(!FAMILY_LOG_TYPES.includes(type))throw new BadRequest('記録種類が不正です。');if(type==='HOUSEWORK')subjectId=null;else if(!subjectId)throw new BadRequest('記録対象を選択してください。');let subjectRow:Row|undefined;if(subjectId){subjectRow=await ctx.env.DB.prepare('SELECT id,name,subject_kind,auto_complete_linked_task,enabled_types_json FROM family_log_subjects WHERE id=? AND family_id=? AND active=1').bind(subjectId,m.family_id).first<Row>()||undefined;if(!subjectRow)throw new BadRequest('記録対象が見つかりません。');if(!familyLogEnabledTypes(subjectRow).includes(type))throw new BadRequest('この対象では記録種類が有効ではありません。');}
    const occurredAt=familyLogDateTime(b.occurred_at),detail=String(b.detail_code||'').trim().toUpperCase()||null;if(detail&&detail.length>32)throw new BadRequest('詳細区分が長すぎます。');const amountRaw=String(b.amount??'').trim(),amount=amountRaw===''?null:Number(amountRaw);if(amount!==null&&(!Number.isFinite(amount)||amount<-100000||amount>100000))throw new BadRequest('数値が不正です。');const durationRaw=String(b.duration_minutes??'').trim(),duration=durationRaw===''?null:Number(durationRaw);if(duration!==null&&(!Number.isFinite(duration)||duration<0||duration>10080))throw new BadRequest('時間が不正です。');const unit=String(b.unit||'').trim().slice(0,16)||null,valueText=String(b.value_text||'').trim();if(valueText.length>255)throw new BadRequest('内容は255文字以内にしてください。');const note=String(b.note||'').trim();if(note.length>2000)throw new BadRequest('メモは2000文字以内にしてください。');let linkedTaskId:number|null=null,linkedOccurrenceId:number|null=null,linked=String(b.linked_target||'').trim();if(linked.startsWith('task:')){linkedTaskId=Number(linked.slice(5))||null;if(linkedTaskId&&!await ctx.env.DB.prepare('SELECT id FROM tasks WHERE id=? AND family_id=?').bind(linkedTaskId,m.family_id).first<Row>())throw new BadRequest('関連タスク・イベントが見つかりません。');}else if(linked.startsWith('occ:')){linkedOccurrenceId=Number(linked.slice(4))||null;if(linkedOccurrenceId&&!await ctx.env.DB.prepare('SELECT id FROM recurrence_occurrences WHERE id=? AND family_id=?').bind(linkedOccurrenceId,m.family_id).first<Row>())throw new BadRequest('関連する定期タスク発生日が見つかりません。');}
    const now=nowJst(),activityBase={log_type:type,occurred_at:occurredAt,subject_id:subjectId,subject_name:String(subjectRow?.name||''),detail_code:detail,amount,unit,duration_minutes:duration,value_text:valueText||null,linked_task_id:linkedTaskId,linked_occurrence_id:linkedOccurrenceId};
    if(id){const current=await ctx.env.DB.prepare('SELECT id,linked_task_id,linked_occurrence_id,quick_chore_id FROM family_logs WHERE id=? AND family_id=? AND deleted_at IS NULL').bind(id,m.family_id).first<Row>();if(!current)return json({ok:false,error:'記録が見つかりません。'},404);const quickChoreId=type==='HOUSEWORK'?(Number(current.quick_chore_id||0)||null):null;await ctx.env.DB.prepare('UPDATE family_logs SET subject_id=?,log_type=?,occurred_at=?,detail_code=?,amount=?,unit=?,duration_minutes=?,value_text=?,note=?,linked_task_id=?,linked_occurrence_id=?,quick_chore_id=?,updated_at=? WHERE id=? AND family_id=? AND deleted_at IS NULL').bind(subjectId,type,occurredAt,detail,amount,unit,duration,valueText||null,note||null,linkedTaskId,linkedOccurrenceId,quickChoreId,now,id,m.family_id).run();const completion=subjectRow&&Number(subjectRow.auto_complete_linked_task||0)===1&&(linkedTaskId||linkedOccurrenceId)?await completeLinkedTargetFromFamilyLog(ctx,linkedTaskId,linkedOccurrenceId,id):null;await logActivity(ctx,'UPDATED','family_log',id,{...activityBase,linked_completion:completion});return json({ok:true,id,linked_completion:completion});}
    const r=await ctx.env.DB.prepare('INSERT INTO family_logs(family_id,subject_id,log_type,occurred_at,detail_code,amount,unit,duration_minutes,value_text,note,linked_task_id,linked_occurrence_id,created_by,created_at,updated_at,deleted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NULL)').bind(m.family_id,subjectId,type,occurredAt,detail,amount,unit,duration,valueText||null,note||null,linkedTaskId,linkedOccurrenceId,m.id,now,now).run(),logId=Number(r.meta.last_row_id),completion=subjectRow&&Number(subjectRow.auto_complete_linked_task||0)===1&&(linkedTaskId||linkedOccurrenceId)?await completeLinkedTargetFromFamilyLog(ctx,linkedTaskId,linkedOccurrenceId,logId):null;await logActivity(ctx,'CREATED','family_log',logId,{...activityBase,linked_completion:completion});return json({ok:true,id:logId,linked_completion:completion});
  }

  if(action==='delete'){
    const id=Number(b.id||0);if(!id)throw new BadRequest('記録が不正です。');const now=nowJst(),current=await ctx.env.DB.prepare('SELECT l.id,l.log_type,l.occurred_at,l.detail_code,l.amount,l.unit,l.duration_minutes,l.value_text,l.subject_id,s.name subject_name FROM family_logs l LEFT JOIN family_log_subjects s ON s.id=l.subject_id WHERE l.id=? AND l.family_id=? AND l.deleted_at IS NULL').bind(id,m.family_id).first<Row>();if(!current)return json({ok:false,error:'記録が見つかりません。'},404);const result=await ctx.env.DB.prepare('UPDATE family_logs SET deleted_at=?,updated_at=? WHERE id=? AND family_id=? AND deleted_at IS NULL').bind(now,now,id,m.family_id).run();if(!result.meta.changes)return json({ok:false,error:'記録が見つかりません。'},404);await logActivity(ctx,'DELETED','family_log',id,{log_type:String(current.log_type||''),occurred_at:String(current.occurred_at||''),subject_id:Number(current.subject_id||0)||null,subject_name:String(current.subject_name||''),detail_code:current.detail_code||null,amount:current.amount??null,unit:current.unit||null,duration_minutes:current.duration_minutes??null,value_text:current.value_text||null});return json({ok:true});
  }

  if(action==='timer_start'){
    const type=String(b.log_type||'TIMER').toUpperCase();if(type!=='TIMER')throw new BadRequest('新しいタイマーは汎用タイマーとして開始してください。');const timerLabel=String(b.timer_label||'').trim();if(!timerLabel||timerLabel.length>80)throw new BadRequest('タイマー名を1〜80文字で入力してください。');const subjectId=Number(b.subject_id||0)||null;if(subjectId&&!await ctx.env.DB.prepare('SELECT id FROM family_log_subjects WHERE id=? AND family_id=? AND active=1').bind(subjectId,m.family_id).first<Row>())throw new BadRequest('記録対象が見つかりません。');const existing=await ctx.env.DB.prepare("SELECT id FROM family_log_timers WHERE family_id=? AND status='running' AND log_type=? AND COALESCE(subject_id,0)=?").bind(m.family_id,type,subjectId||0).first<Row>();if(existing)throw new BadRequest('同じ種類のタイマーが既に動いています。');const now=nowJst(),r=await ctx.env.DB.prepare("INSERT INTO family_log_timers(family_id,subject_id,log_type,started_at,started_at_ms,status,note,created_by,created_at,updated_at,timer_label) VALUES(?,?,?,?,?,'running',NULL,?,?,?,?,?)").bind(m.family_id,subjectId,type,now,Date.now(),m.id,now,now,timerLabel).run(),id=Number(r.meta.last_row_id);await logActivity(ctx,'STARTED','family_log_timer',id,{log_type:type,timer_label:timerLabel});return json({ok:true,id});
  }
  if(action==='sleep_start'){
    const subjectId=Number(b.subject_id||0);if(!subjectId)throw new BadRequest('睡眠対象を選択してください。');const result=await startDedicatedSleepDomain(ctx.env,m,subjectId);if(!result.ok)throw new BadRequest('赤ちゃん・子どもの対象だけ睡眠タイマーを開始できます。');return json(result);
  }
  if(action==='sleep_adjust'){
    const timerId=Number(b.timer_id||0),startedAt=familyLogDateTime(b.started_at),startedMs=familyLogJstMs(startedAt),nowMs=Date.now();if(!Number.isFinite(startedMs)||startedMs>nowMs)throw new BadRequest('開始時刻に未来は指定できません。');if(nowMs-startedMs>SLEEP_TIMER_MAX_ADJUST_MINUTES*60000)throw new BadRequest('開始時刻は48時間以内で指定してください。');const result=await ctx.env.DB.prepare("UPDATE family_log_timers SET started_at=?,started_at_ms=?,updated_at=? WHERE id=? AND family_id=? AND log_type='SLEEP' AND status='running' AND EXISTS(SELECT 1 FROM family_log_subjects s WHERE s.id=family_log_timers.subject_id AND s.family_id=family_log_timers.family_id AND s.subject_kind IN ('BABY','CHILD') AND s.active=1)").bind(startedAt,startedMs,nowJst(),timerId,m.family_id).run();if(!result.meta.changes)return json({ok:false,error:'実行中の子ども睡眠タイマーが見つかりません。'},404);return json({ok:true});
  }
  if(action==='sleep_stop'){
    const timerId=Number(b.timer_id||0),wakeAt=familyLogDateTime(b.wake_at||nowJst()),wakeMs=familyLogJstMs(wakeAt),timer=await ctx.env.DB.prepare("SELECT x.*,s.name subject_name,s.subject_kind FROM family_log_timers x JOIN family_log_subjects s ON s.id=x.subject_id AND s.family_id=x.family_id AND s.active=1 AND s.subject_kind IN ('BABY','CHILD') WHERE x.id=? AND x.family_id=? AND x.log_type='SLEEP' AND x.status='running' LIMIT 1").bind(timerId,m.family_id).first<Row>();if(!timer)return json({ok:false,error:'実行中の子ども睡眠タイマーが見つかりません。'},404);void wakeMs;return json(await stopDedicatedSleepDomain(ctx.env,m,Number(timer.subject_id),timerId,wakeAt));
  }
  if(action==='timer_stop'){
    const timerId=Number(b.timer_id||0);if(!timerId)throw new BadRequest('タイマーが不正です。');const timer=await ctx.env.DB.prepare("SELECT * FROM family_log_timers WHERE id=? AND family_id=? AND status='running' LIMIT 1").bind(timerId,m.family_id).first<Row>();if(!timer)return json({ok:false,error:'実行中のタイマーが見つかりません。'},404);const duration=Math.max(0,Math.min(10080,Math.round((Date.now()-Number(timer.started_at_ms||Date.now()))/60000))),now=nowJst(),r=await ctx.env.DB.prepare('INSERT INTO family_logs(family_id,subject_id,log_type,occurred_at,detail_code,amount,unit,duration_minutes,value_text,note,linked_task_id,linked_occurrence_id,created_by,created_at,updated_at,deleted_at) VALUES(?,?,?,?,NULL,NULL,NULL,?,?,?,NULL,NULL,?,?,?,NULL)').bind(m.family_id,timer.subject_id||null,String(timer.log_type||'SLEEP'),String(timer.started_at||now),duration,String(timer.timer_label||'')||null,timer.note||null,m.id,now,now).run();await ctx.env.DB.prepare("UPDATE family_log_timers SET status='stopped',updated_at=? WHERE id=? AND family_id=? AND status='running'").bind(now,timerId,m.family_id).run();const logId=Number(r.meta.last_row_id),subject=timer.subject_id?await ctx.env.DB.prepare('SELECT name FROM family_log_subjects WHERE id=? AND family_id=?').bind(Number(timer.subject_id),m.family_id).first<Row>():null;await logActivity(ctx,'CREATED','family_log',logId,{log_type:String(timer.log_type||'SLEEP'),occurred_at:String(timer.started_at||now),subject_id:Number(timer.subject_id||0)||null,subject_name:String(subject?.name||''),duration_minutes:duration,source:'timer'});await logActivity(ctx,'STOPPED','family_log_timer',timerId,{family_log_id:logId,duration_minutes:duration});return json({ok:true,log_id:logId});
  }
  if(action==='timer_cancel'){
    const timerId=Number(b.timer_id||0);if(!timerId)throw new BadRequest('タイマーが不正です。');const now=nowJst(),result=await ctx.env.DB.prepare("UPDATE family_log_timers SET status='cancelled',updated_at=? WHERE id=? AND family_id=? AND status='running'").bind(now,timerId,m.family_id).run();if(!result.meta.changes)return json({ok:false,error:'実行中のタイマーが見つかりません。'},404);await logActivity(ctx,'CANCELLED','family_log_timer',timerId,{});return json({ok:true});
  }
  throw new BadRequest('操作が不正です。');
}
