import { json } from './response';
import type { AppContext } from './app';
import { DEFAULT_FAMILY_TIMEZONE, familyNow } from './timezone';

export const GEMINI_MODEL_DEFAULT='gemini-2.0-flash-lite';
const FAILURE='AI解析を利用できません';
const LOG_TYPES=['MILK','SLEEP','DIAPER','HOUSEWORK','TIMER','VACCINE','MEAL','MEDICINE','TEMPERATURE','WEIGHT','HEIGHT','MEMO'] as const;
const LEGACY_TOOLS=['daily_family_log_aggregate','quick_chore_stats','task_stats','schedule_lookup','family_log_latest'] as const;
const TOOLS=[...LEGACY_TOOLS,'family_statistics'] as const;
const DOMAINS=['FAMILY_LOG','QUICK_CHORE','TASK','SCHEDULE'] as const;
const METRICS=['COUNT','SUM_AMOUNT','AVG_AMOUNT','MIN_AMOUNT','MAX_AMOUNT','SUM_DURATION','AVG_DURATION','MIN_DURATION','MAX_DURATION','LATEST_AMOUNT'] as const;
const GROUPS=['NONE','DAY','WEEK','MONTH','MEMBER','SUBJECT','CHORE','LOG_TYPE'] as const;
const COMPARISONS=['GTE','GT','LTE','LT','EQ'] as const;
const ORDERS=['DATE','VALUE'] as const;
type Args=Record<string,unknown>; type Row=Record<string,unknown>;
type Tokenized={question:string;refs:Map<string,number>;names:Map<string,string>;clarification?:string};
const dateOk=(v:unknown)=>v===undefined||/^\d{4}-\d{2}-\d{2}$/.test(String(v));
const enumOk=(value:unknown,allowed:readonly string[])=>allowed.includes(String(value));

const statisticQueryProperties={domain:{type:'STRING',enum:[...DOMAINS]},metric:{type:'STRING',enum:[...METRICS]},group_by:{type:'STRING',enum:[...GROUPS]},comparison:{type:'STRING',enum:[...COMPARISONS]},order_by:{type:'STRING',enum:[...ORDERS]},direction:{type:'STRING',enum:['ASC','DESC']},limit:{type:'INTEGER'},subject_ref:{type:'STRING'},member_ref:{type:'STRING'},log_type:{type:'STRING',enum:[...LOG_TYPES]},date_from:{type:'STRING'},date_to:{type:'STRING'},threshold:{type:'NUMBER'}};
export const FAMILY_AI_FUNCTIONS=[
 {name:'daily_family_log_aggregate',description:'Family Logを家族タイムゾーンの日単位で集計',parameters:{type:'OBJECT',properties:{subject_ref:{type:'STRING'},log_type:{type:'STRING',enum:[...LOG_TYPES]},date_from:{type:'STRING'},date_to:{type:'STRING'},metric:{type:'STRING',enum:['SUM_AMOUNT','COUNT','SUM_DURATION','AVG_AMOUNT']},threshold:{type:'NUMBER'},comparison:{type:'STRING',enum:[...COMPARISONS]},order:{type:'STRING',enum:['ASC','DESC']},limit:{type:'INTEGER'}},required:['log_type','metric']}},
 {name:'quick_chore_stats',description:'ちょこっと家事を実行者(created_by)で集計',parameters:{type:'OBJECT',properties:{member_ref:{type:'STRING'},chore_id:{type:'INTEGER'},date_from:{type:'STRING'},date_to:{type:'STRING'},group_by:{type:'STRING',enum:['NONE','DAY','CHORE','MEMBER']}},required:['date_from','date_to','group_by']}},
 {name:'task_stats',description:'共有タスクの件数または一覧',parameters:{type:'OBJECT',properties:{member_ref:{type:'STRING'},date_from:{type:'STRING'},date_to:{type:'STRING'},status:{type:'STRING',enum:['PENDING','COMPLETED','ALL']},task_kind:{type:'STRING',enum:['TASK','EVENT','ALL']},count_only:{type:'BOOLEAN'}},required:['status','task_kind','count_only']}},
 {name:'schedule_lookup',description:'共有予定を期間検索',parameters:{type:'OBJECT',properties:{date_from:{type:'STRING'},date_to:{type:'STRING'},member_ref:{type:'STRING'}},required:['date_from','date_to']}},
 {name:'family_log_latest',description:'指定対象・種類の最新Family Log',parameters:{type:'OBJECT',properties:{subject_ref:{type:'STRING'},log_type:{type:'STRING',enum:[...LOG_TYPES]},date_from:{type:'STRING'},date_to:{type:'STRING'}},required:['subject_ref','log_type']}},
 {name:'family_statistics',description:'allowlist済み統計queryを最大3件実行。比較は2件の結果をWorkerで決定する',parameters:{type:'OBJECT',properties:{operation:{type:'STRING',enum:['QUERY','COMPARE']},queries:{type:'ARRAY',maxItems:3,items:{type:'OBJECT',properties:statisticQueryProperties,required:['domain','metric','group_by','order_by','direction','limit']}}},required:['operation','queries']}}
];

async function tokenize(db:D1Database,familyId:number,question:string):Promise<Tokenized>{
 const [members,subjects]=await Promise.all([db.prepare('SELECT id,name FROM members WHERE family_id=? AND active=1 AND deleted_at IS NULL ORDER BY id').bind(familyId).all<Row>(),db.prepare('SELECT id,name FROM family_log_subjects WHERE family_id=? AND active=1 ORDER BY id').bind(familyId).all<Row>()]);
 const refs=new Map<string,number>(),names=new Map<string,string>(),byName=new Map<string,{member:Row[];subject:Row[]}>();
 for(const r of members.results){const x=byName.get(String(r.name))||{member:[],subject:[]};x.member.push(r);byName.set(String(r.name),x);}
 for(const r of subjects.results){const x=byName.get(String(r.name))||{member:[],subject:[]};x.subject.push(r);byName.set(String(r.name),x);}
 let q=question,mi=0,si=0;const logContext=/ミルク|睡眠|寝|体重|身長|体温|おむつ|ログ/,memberContext=/家事|タスク|予定|担当/;
 for(const [name,x] of [...byName.entries()].sort((a,b)=>b[0].length-a[0].length)){if(!q.includes(name))continue;let kind:'MEMBER'|'SUBJECT';let rows:Row[];
  if(x.member.length&&x.subject.length){if(logContext.test(question)&&!memberContext.test(question)){kind='SUBJECT';rows=x.subject;}else if(memberContext.test(question)&&!logContext.test(question)){kind='MEMBER';rows=x.member;}else return {question:q,refs,names,clarification:`${name}はメンバーと記録対象の両方にあります。どちらについての質問ですか？`};}
  else if(x.member.length){kind='MEMBER';rows=x.member;}else{kind='SUBJECT';rows=x.subject;}
  if(rows.length!==1)return {question:q,refs,names,clarification:`${name}が${rows.length}件あります。どちらですか？`};
  const ref=`${kind}_${kind==='MEMBER'?++mi:++si}`;refs.set(ref,Number(rows[0].id));names.set(ref,name);q=q.split(name).join(ref);
 }
 return {question:q,refs,names};
}
function rejectSql(args:unknown){if(typeof args==='string'&&/\b(SELECT|INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|PRAGMA)\b/i.test(args))throw new Error('SQL is forbidden');if(Array.isArray(args))args.forEach(rejectSql);else if(args&&typeof args==='object')Object.values(args).forEach(rejectSql);}
function validateQuery(a:Args){
 if(!enumOk(a.domain,DOMAINS)||!enumOk(a.metric,METRICS)||!enumOk(a.group_by,GROUPS)||!enumOk(a.order_by,ORDERS)||!enumOk(a.direction,['ASC','DESC']))throw new Error('invalid statistics enum');
 if(a.comparison!==undefined&&!enumOk(a.comparison,COMPARISONS))throw new Error('invalid comparison');if(!dateOk(a.date_from)||!dateOk(a.date_to))throw new Error('invalid date');if(a.date_from&&a.date_to&&String(a.date_from)>String(a.date_to))throw new Error('invalid range');
 if(a.log_type!==undefined&&!enumOk(a.log_type,LOG_TYPES))throw new Error('invalid log type');const limit=Number(a.limit);if(!Number.isInteger(limit)||limit<1||limit>100)throw new Error('invalid limit');
 const domain=String(a.domain),metric=String(a.metric),group=String(a.group_by);if(domain==='QUICK_CHORE'&&(metric!=='COUNT'||!['NONE','DAY','WEEK','MONTH','MEMBER','CHORE'].includes(group)))throw new Error('invalid chore query');
 if(['TASK','SCHEDULE'].includes(domain)&&(metric!=='COUNT'||!['NONE','DAY','WEEK','MONTH'].includes(group)))throw new Error('invalid task query');
 if(domain==='FAMILY_LOG'&&['MEMBER','CHORE'].includes(group))throw new Error('invalid log grouping');if(metric==='LATEST_AMOUNT'&&group!=='NONE')throw new Error('latest cannot group');
}
function validate(name:string,args:Args){if(!TOOLS.includes(name as any))throw new Error('invalid tool');rejectSql(args);if(!dateOk(args.date_from)||!dateOk(args.date_to))throw new Error('invalid date');if(args.log_type&&!enumOk(args.log_type,LOG_TYPES))throw new Error('invalid log type');if(name==='family_statistics'){if(!enumOk(args.operation,['QUERY','COMPARE'])||!Array.isArray(args.queries)||args.queries.length<1||args.queries.length>3)throw new Error('invalid plan');if(args.operation==='COMPARE'&&args.queries.length!==2)throw new Error('comparison requires two queries');args.queries.forEach(x=>validateQuery(x as Args));}}
function resolve(refs:Map<string,number>,ref:unknown,kind:'MEMBER'|'SUBJECT'){if(ref===undefined)return null;const key=String(ref);if(!key.startsWith(kind+'_')||!refs.has(key))throw new Error('invalid reference');return refs.get(key)!;}
const range=(a:Args)=>({from:String(a.date_from||'0001-01-01'),to:String(a.date_to||'9999-12-31')});
const cmpSql=(v:unknown)=>({GTE:'>=',GT:'>',LTE:'<=',LT:'<',EQ:'='}[String(v||'GTE')]||'');

async function executeStatisticsQuery(db:D1Database,familyId:number,a:Args,refs:Map<string,number>){
 const {from,to}=range(a),domain=String(a.domain),metric=String(a.metric),group=String(a.group_by),direction=String(a.direction),order=String(a.order_by),limit=Number(a.limit),sid=resolve(refs,a.subject_ref,'SUBJECT'),mid=resolve(refs,a.member_ref,'MEMBER');
 if(domain==='FAMILY_LOG'){
  const expressions:Record<string,string>={COUNT:'COUNT(*)',SUM_AMOUNT:'COALESCE(SUM(amount),0)',AVG_AMOUNT:'ROUND(AVG(amount),2)',MIN_AMOUNT:'MIN(amount)',MAX_AMOUNT:'MAX(amount)',SUM_DURATION:'COALESCE(SUM(duration_minutes),0)',AVG_DURATION:'ROUND(AVG(duration_minutes),2)',MIN_DURATION:'MIN(duration_minutes)',MAX_DURATION:'MAX(duration_minutes)'};
  if(metric==='LATEST_AMOUNT'){const binds:any[]=[familyId];let extra='';if(sid){extra+=' AND subject_id=?';binds.push(sid);}if(a.log_type){extra+=' AND log_type=?';binds.push(String(a.log_type));}binds.push(from,to);return (await db.prepare(`SELECT substr(occurred_at,1,10) label,amount value,occurred_at FROM family_logs WHERE family_id=?${extra} AND deleted_at IS NULL AND substr(occurred_at,1,10) BETWEEN ? AND ? AND amount IS NOT NULL ORDER BY occurred_at DESC LIMIT 1`).bind(...binds).all<Row>()).results;}
  const labels:Record<string,string>={NONE:"'合計'",DAY:'substr(occurred_at,1,10)',WEEK:"strftime('%Y-W%W',occurred_at)",MONTH:'substr(occurred_at,1,7)',SUBJECT:"CAST(subject_id AS TEXT)",LOG_TYPE:'log_type'},label=labels[group],expr=expressions[metric];if(!label||!expr)throw new Error('invalid log expression');
  const binds:any[]=[familyId];let extra='';if(sid){extra+=' AND subject_id=?';binds.push(sid);}if(a.log_type){extra+=' AND log_type=?';binds.push(String(a.log_type));}binds.push(from,to);const having=a.threshold===undefined?'':` HAVING ${expr} ${cmpSql(a.comparison)} ?`;if(a.threshold!==undefined)binds.push(Number(a.threshold));binds.push(limit);
  const orderExpr=order==='DATE'?'label':'value';return (await db.prepare(`SELECT ${label} label,${expr} value FROM family_logs WHERE family_id=?${extra} AND deleted_at IS NULL AND substr(occurred_at,1,10) BETWEEN ? AND ? GROUP BY ${label}${having} ORDER BY ${orderExpr} ${direction} LIMIT ?`).bind(...binds).all<Row>()).results;
 }
 if(domain==='QUICK_CHORE'){
  const labels:Record<string,string>={NONE:"'合計'",DAY:'substr(l.occurred_at,1,10)',WEEK:"strftime('%Y-W%W',l.occurred_at)",MONTH:'substr(l.occurred_at,1,7)',MEMBER:"COALESCE(m.name,'不明')",CHORE:"COALESCE(c.name,'未設定')"},label=labels[group],binds:any[]=[familyId];let extra='';if(mid){extra=' AND l.created_by=?';binds.push(mid);}binds.push(from,to);const having=a.threshold===undefined?'':` HAVING COUNT(*) ${cmpSql(a.comparison)} ?`;if(a.threshold!==undefined)binds.push(Number(a.threshold));binds.push(limit);return (await db.prepare(`SELECT ${label} label,COUNT(*) value FROM family_logs l LEFT JOIN family_quick_chores c ON c.id=l.quick_chore_id AND c.family_id=l.family_id LEFT JOIN members m ON m.id=l.created_by AND m.family_id=l.family_id WHERE l.family_id=?${extra} AND l.log_type='HOUSEWORK' AND l.deleted_at IS NULL AND substr(l.occurred_at,1,10) BETWEEN ? AND ? GROUP BY ${label}${having} ORDER BY ${order==='DATE'?'label':'value'} ${direction} LIMIT ?`).bind(...binds).all<Row>()).results;
 }
 const field=domain==='SCHEDULE'?'COALESCE(t.start_at,t.due_at)':'t.due_at',labels:Record<string,string>={NONE:"'合計'",DAY:`substr(${field},1,10)`,WEEK:`strftime('%Y-W%W',${field})`,MONTH:`substr(${field},1,7)`},label=labels[group],binds:any[]=[familyId,from,to];return (await db.prepare(`SELECT ${label} label,COUNT(*) value FROM tasks t WHERE t.family_id=? AND COALESCE(t.visibility_scope,'FAMILY')='FAMILY' AND ${field} IS NOT NULL AND substr(${field},1,10) BETWEEN ? AND ?${domain==='SCHEDULE'?" AND t.task_kind='EVENT'":""} GROUP BY ${label} ORDER BY ${order==='DATE'?'label':'value'} ${direction} LIMIT ${limit}`).bind(...binds).all<Row>()).results;
}

export async function executeFamilyAiTool(db:D1Database,familyId:number,name:string,a:Args,refs=new Map<string,number>()){
 validate(name,a);const {from,to}=range(a);
 if(name==='family_statistics'){const results=[];for(const query of a.queries as Args[])results.push(await executeStatisticsQuery(db,familyId,query,refs));return results as unknown as Row[];}
 if(name==='daily_family_log_aggregate'){const q:Args={domain:'FAMILY_LOG',metric:a.metric,group_by:'DAY',comparison:a.comparison,order_by:'DATE',direction:a.order||'DESC',limit:Math.min(100,Math.max(1,Number(a.limit||31))),subject_ref:a.subject_ref,log_type:a.log_type,date_from:a.date_from,date_to:a.date_to,threshold:a.threshold};return executeStatisticsQuery(db,familyId,q,refs);}
 if(name==='quick_chore_stats'){const q:Args={domain:'QUICK_CHORE',metric:'COUNT',group_by:a.group_by,order_by:'VALUE',direction:'DESC',limit:100,member_ref:a.member_ref,date_from:a.date_from,date_to:a.date_to};return executeStatisticsQuery(db,familyId,q,refs);}
 const mid=resolve(refs,a.member_ref,'MEMBER'),binds:any[]=[familyId,from,to];if(mid)binds.push(mid);const conditions=`t.family_id=? AND COALESCE(t.visibility_scope,'FAMILY')='FAMILY' AND substr(COALESCE(t.start_at,t.due_at),1,10) BETWEEN ? AND ? ${mid?'AND EXISTS(SELECT 1 FROM task_assignees ta WHERE ta.task_id=t.id AND ta.member_id=?)':''}`;
 if(name==='schedule_lookup')return (await db.prepare(`SELECT t.title,t.task_kind,t.start_at,t.end_at,t.due_at,t.location FROM tasks t WHERE ${conditions} AND t.calendar_visible=1 ORDER BY COALESCE(t.start_at,t.due_at) LIMIT 50`).bind(...binds).all<Row>()).results;
 if(name==='task_stats'){const status=String(a.status||'ALL'),kind=String(a.task_kind||'ALL'),extra=`${status==='ALL'?'':' AND t.status=?'}${kind==='ALL'?'':' AND upper(t.task_kind)=?'}`;if(status!=='ALL')binds.push(status.toLowerCase());if(kind!=='ALL')binds.push(kind);const cols=a.count_only?'COUNT(*) value':'t.title,t.status,t.task_kind,t.due_at,t.start_at';return (await db.prepare(`SELECT ${cols} FROM tasks t WHERE ${conditions}${extra}${a.count_only?'':' ORDER BY COALESCE(t.start_at,t.due_at) LIMIT 50'}`).bind(...binds).all<Row>()).results;}
 const sid=resolve(refs,a.subject_ref,'SUBJECT');return (await db.prepare('SELECT occurred_at,amount,unit,duration_minutes,value_text FROM family_logs WHERE family_id=? AND subject_id=? AND log_type=? AND deleted_at IS NULL AND substr(occurred_at,1,10) BETWEEN ? AND ? ORDER BY occurred_at DESC LIMIT 1').bind(familyId,sid,String(a.log_type),from,to).all<Row>()).results;
}
const unitFor=(a:Args)=>a.metric==='COUNT'?'件':String(a.metric).includes('DURATION')?'分':a.log_type==='MILK'?'ml':a.log_type==='TEMPERATURE'?'℃':a.log_type==='WEIGHT'?'kg':a.log_type==='HEIGHT'?'cm':'';
const num=(v:unknown)=>Number(v||0).toLocaleString('ja-JP',{maximumFractionDigits:2});
function statisticsAnswer(args:Args,result:Row[][],names:Map<string,string>){const queries=args.queries as Args[],q=queries[0],target=names.get(String(q.subject_ref||q.member_ref||''))||'家族全体',period=`${String(q.date_from||'全期間')}〜${String(q.date_to||'現在')}`,unit=unitFor(q);if(args.operation==='COMPARE'){const left=Number(result[0]?.[0]?.value||0),right=Number(result[1]?.[0]?.value||0),diff=left-right;return `比較結果: ${left===right?'同じです':left>right?'前の期間の方が多いです':'後の期間の方が多いです'}\n前: ${num(left)}${unit} / 後: ${num(right)}${unit} / 差: ${diff>=0?'+':''}${num(diff)}${unit}\n対象: ${target}\n集計: 期間比較`;}
 const rows=result[0]||[];if(!rows.length)return `該当する記録はありません。\n対象: ${target}\n期間: ${period}`;const lines=rows.map(r=>`${r.label||'合計'}: ${num(r.value)}${unit}`);return `${lines.join('\n')}\n対象: ${target}\n期間: ${period}\n集計: ${String(q.group_by)} / ${String(q.metric)}`;}
function legacyAnswer(name:string,rows:Row[],args:Args){const period=`${String(args.date_from||'全期間')}〜${String(args.date_to||'現在')}`,method=name==='daily_family_log_aggregate'?'日単位集計':name==='quick_chore_stats'?'ちょこっと家事件数':name==='schedule_lookup'?'共有予定検索':name==='task_stats'?'共有タスク集計':'最新記録';if(!rows.length)return `該当する記録はありません。\n期間: ${period}`;if(name==='schedule_lookup')return rows.map(r=>`${String(r.start_at||r.due_at).slice(0,16)} ${r.title}`).join('\n')+`\n期間: ${period}`;const unit=unitFor(args);return rows.map(r=>`${r.day||r.label||String(r.occurred_at||'').slice(0,16)}: ${r.value??r.amount??r.value_text??''}${'value' in r?unit:''}`).join('\n')+`\n期間: ${period}\n集計方法: ${method}`;}

export async function familyAiQuery(request:Request,ctx:AppContext){
 if(!ctx.member)return json({ok:false,error:'ログインが必要です。'},401);if(request.method!=='POST')return json({ok:false,error:'POST only'},405);const body=await request.json().catch(()=>null) as any,q=String(body?.question||'').trim();if(!q||q.length>500)return json({ok:false,error:'質問を入力してください。'},400);if(!ctx.env.GEMINI_API_KEY)return json({ok:false,error:'Family AIは未設定です。'},503);
 try{const family=await ctx.env.DB.prepare('SELECT timezone FROM families WHERE id=?').bind(ctx.member.family_id).first<Row>(),timezone=String(family?.timezone||DEFAULT_FAMILY_TIMEZONE),tok=await tokenize(ctx.env.DB,ctx.member.family_id,q);if(tok.clarification)return json({ok:true,clarification:true,answer:tok.clarification});
  const model=ctx.env.GEMINI_MODEL||GEMINI_MODEL_DEFAULT,res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(ctx.env.GEMINI_API_KEY)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:`現在日時: ${familyNow(timezone)} (${timezone})。家族local wall clockの日付を使う。read-only functionを1つ呼ぶ。動的統計にはfamily_statisticsを使いqueryは最大3件。SQL、table名、column名、自然文回答は禁止。比較結果は生成せずCOMPAREを選ぶ。名前tokenをrefへ使う。`} ]},contents:[{role:'user',parts:[{text:tok.question}]}],tools:[{functionDeclarations:FAMILY_AI_FUNCTIONS}],toolConfig:{functionCallingConfig:{mode:'ANY',allowedFunctionNames:[...TOOLS]}}})});if(!res.ok)throw new Error('gemini unavailable');const data=await res.json() as any,call=data?.candidates?.[0]?.content?.parts?.find((p:any)=>p.functionCall)?.functionCall;if(!call)throw new Error('no function');const rows=await executeFamilyAiTool(ctx.env.DB,ctx.member.family_id,String(call.name),call.args||{},tok.refs),answer=String(call.name)==='family_statistics'?statisticsAnswer(call.args||{},rows as unknown as Row[][],tok.names):legacyAnswer(String(call.name),rows,call.args||{});return json({ok:true,answer,...(body?.debug===true&&['OWNER','ADMIN'].includes(String(ctx.member.role).toUpperCase())?{debug:{tool:String(call.name),args:call.args||{}}}:{})});
 }catch{return json({ok:false,error:FAILURE},503);}
}
/** Connectivity probe sends only a fixed synthetic prompt; no family row or user question is read. */
export async function familyAiConnectionTest(request:Request,ctx:AppContext){if(!ctx.member)return json({ok:false},401);if(!['OWNER','ADMIN'].includes(String(ctx.member.role||'').toUpperCase()))return json({ok:false},403);if(request.method!=='POST')return json({ok:false},405);const body=await request.json().catch(()=>({})) as any;if(String(body.csrf||'')!==String(ctx.session.csrfToken||''))return json({ok:false},403);if(!ctx.env.GEMINI_API_KEY)return json({ok:false,error:'not configured'},503);try{const model=ctx.env.GEMINI_MODEL||GEMINI_MODEL_DEFAULT,r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(ctx.env.GEMINI_API_KEY)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:'Reply with OK. This is a synthetic connectivity test; no user data is included.'}]}],generationConfig:{maxOutputTokens:8}})});return json({ok:r.ok},r.ok?200:503);}catch{return json({ok:false},503);}}
