import { json, html } from './response';
import { layout, type AppContext, AuthRequired, BadRequest, Forbidden } from './app';
import { FAMILY_LOG_IMPORT_CHUNK_SIZE as CHUNK_SIZE, validateChunkOffset, validateFinishCounts } from './family-log-import-protocol.js';
import { addWallClockMinutes, DEFAULT_FAMILY_TIMEZONE, familyNow, parseImportDateTime, timezoneOffsetMinutesAt } from './timezone';

type Row=Record<string,unknown>; type ImportRecord=Record<string,unknown>;
const FORMAT='familytodo-family-log-import-v1', MAX_RECORDS=5000, MAX_BODY_BYTES=3*1024*1024, LOOKUP_SIZE=90;
const TYPES:Record<string,{icon:string;label:string;units:string[]}>= {
  MILK:{icon:'🍼',label:'ミルク',units:['ml']},BREASTFEED:{icon:'🤱',label:'母乳',units:[]},MEAL:{icon:'🍚',label:'食事',units:[]},DIAPER:{icon:'🧷',label:'おむつ',units:[]},SLEEP:{icon:'😴',label:'睡眠',units:[]},BATH:{icon:'🛁',label:'お風呂',units:[]},TEMPERATURE:{icon:'🌡️',label:'体温',units:['°C','℃']},MEDICINE:{icon:'💊',label:'薬',units:[]},VACCINE:{icon:'💉',label:'予防接種',units:[]},CONDITION:{icon:'🙂',label:'体調',units:[]},WEIGHT:{icon:'⚖️',label:'体重',units:['kg']},HEIGHT:{icon:'📏',label:'身長',units:['cm']},BLOOD_PRESSURE:{icon:'🫀',label:'血圧',units:[]},EXERCISE:{icon:'🏃',label:'運動',units:[]},WATER:{icon:'💧',label:'水分',units:['ml']},TOILET:{icon:'🚻',label:'トイレ',units:[]},WALK:{icon:'🐕',label:'散歩',units:[]},MEMO:{icon:'📝',label:'メモ',units:[]}
};
const esc=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const nowJst=()=>familyNow(DEFAULT_FAMILY_TIMEZONE);
const member=(ctx:AppContext)=>{if(!ctx.member)throw new AuthRequired();return ctx.member;}; const admin=(m:unknown)=>['OWNER','ADMIN'].includes(String((m as Row)?.role||'').toUpperCase());
async function body(request:Request){const length=Number(request.headers.get('content-length')||0);if(length>MAX_BODY_BYTES)throw new BadRequest('JSONは3MB以内にしてください。');const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>MAX_BODY_BYTES)throw new BadRequest('JSONは3MB以内にしてください。');let x:unknown;try{x=JSON.parse(raw)}catch{x=null}if(!x||typeof x!=='object'||Array.isArray(x))throw new BadRequest('JSONが不正です。');return x as Record<string,unknown>;}
async function hash(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function text(v:unknown,max:number){if(v===null||v===undefined)return null;const x=String(v).trim();if(x.length>max)throw new Error(`${max}文字を超えています`);return x||null;}
function normalize(r:ImportRecord,timezone=DEFAULT_FAMILY_TIMEZONE){const type=String(r.log_type||'').toUpperCase();if(type==='UNSUPPORTED'||!TYPES[type])throw new Error(type==='UNSUPPORTED'?'未対応':'未対応の種類');const occurredAt=parseImportDateTime(r.occurred_at,timezone);const amount=r.amount==null?null:Number(r.amount);if(amount!==null&&!Number.isFinite(amount))throw new Error('数値が不正です');const duration=r.duration_minutes==null?null:Number(r.duration_minutes);if(duration!==null&&(!Number.isInteger(duration)||duration<0||duration>10080))throw new Error('時間が不正です');const unit=text(r.unit,40);if(unit&&TYPES[type].units.length&&!TYPES[type].units.includes(unit))throw new Error('単位が種類に適合しません');if(unit&&!TYPES[type].units.length)throw new Error('この種類に単位は指定できません');const page=r.source_page==null?null:Number(r.source_page);if(page!==null&&(!Number.isInteger(page)||page<1))throw new Error('ページ番号が不正です');return {external_id:text(r.external_id,255),occurred_at:occurredAt,log_type:type,detail_code:text(r.detail_code,40),amount,unit,duration_minutes:duration,value_text:text(r.value_text,255),note:text(r.note,2000),source_text:text(r.source_text,4000),source_page:page};}
const canonical=(familyId:number,subjectId:number,source:string,v:ReturnType<typeof normalize>)=>JSON.stringify([familyId,subjectId,source,v.occurred_at,v.log_type,v.detail_code,v.amount,v.unit,v.duration_minutes,v.value_text,v.source_text]);

async function inspect(ctx:AppContext,subjectId:number,doc:Record<string,unknown>){const m=member(ctx);const family=await ctx.env.DB.prepare('SELECT timezone FROM families WHERE id=?').bind(m.family_id).first<Row>();const timezone=String(family?.timezone||DEFAULT_FAMILY_TIMEZONE);if(JSON.stringify(doc).length>MAX_BODY_BYTES)throw new BadRequest('import documentが大きすぎます。');if(String(doc.format||'')!==FORMAT)throw new BadRequest('対応していないimport formatです。');const source=String(doc.source||'').trim().slice(0,80);if(!source)throw new BadRequest('sourceは必須です。');const records=doc.records;if(!Array.isArray(records)||records.length>MAX_RECORDS)throw new BadRequest(`recordsは${MAX_RECORDS}件以内の配列にしてください。`);const subject=await ctx.env.DB.prepare("SELECT id,name,subject_kind FROM family_log_subjects WHERE id=? AND family_id=? AND active=1 AND subject_kind IN ('BABY','CHILD','ADULT','PET','OTHER')").bind(subjectId,m.family_id).first<Row>();if(!subject)throw new BadRequest('取り込み先が見つかりません。');
  const rows:any[]=[],seen=new Set<string>(),typeCounts:Record<string,number>={};let errors=0,minDate='',maxDate='';
  const normalized=await Promise.all(records.map(async(r,i)=>{try{const value=normalize(r as ImportRecord,timezone);const key=await hash(canonical(Number(m.family_id),subjectId,source,value));let legacyKey=key;const rawDate=String((r as ImportRecord).occurred_at||'');if(/(?:Z|[+-]\d{2}:?\d{2})$/i.test(rawDate)){const legacy={...value,occurred_at:new Date(rawDate).toISOString().slice(0,19).replace('T',' ')};legacyKey=await hash(canonical(Number(m.family_id),subjectId,source,legacy));}typeCounts[value.log_type]=(typeCounts[value.log_type]||0)+1;const date=value.occurred_at.slice(0,10);minDate=!minDate||date<minDate?date:minDate;maxDate=!maxDate||date>maxDate?date:maxDate;return {index:i,key,legacyKey,value};}catch(e:any){errors++;return {index:i,status:'error',error:String(e?.message||e)};}}));
  const valid=normalized.filter((x:any)=>x.key),dbKeys=new Set<string>();for(let i=0;i<valid.length;i+=LOOKUP_SIZE){const part=valid.slice(i,i+LOOKUP_SIZE);const found=await ctx.env.DB.prepare(`SELECT import_source_key FROM family_logs WHERE family_id=? AND subject_id=? AND deleted_at IS NULL AND import_source_key IN (${part.flatMap(()=>['?','?']).join(',')})`).bind(m.family_id,subjectId,...part.flatMap((x:any)=>[x.key,x.legacyKey])).all<Row>();found.results.forEach(r=>dbKeys.add(String(r.import_source_key)));}
  let fresh=0,duplicate=0;for(const x of normalized as any[]){if(!x.key){rows.push(x);continue}const exists=seen.has(x.key)||dbKeys.has(x.key)||dbKeys.has(x.legacyKey);seen.add(x.key);exists?duplicate++:fresh++;rows.push({...x,status:exists?'duplicate':'new'});}return {format:FORMAT,source,source_exported_at:text(doc.source_exported_at,80),source_hash:await hash(JSON.stringify(doc)),subject,record_count:records.length,new_count:fresh,duplicate_count:duplicate,error_count:errors,type_counts:typeCounts,date_from:minDate,date_to:maxDate,rows};
}
async function getBatch(ctx:AppContext,id:number){const m=member(ctx);const b=await ctx.env.DB.prepare('SELECT * FROM family_log_import_batches WHERE id=? AND family_id=?').bind(id,m.family_id).first<Row>();if(!b)throw new BadRequest('インポート履歴が見つかりません。');return b;}
type ManifestEntry={offset:number;length:number;hash:string;error_count:number};
function manifestOf(batch:Row):ManifestEntry[]{try{const value=JSON.parse(String(batch.chunk_manifest_json||'[]'));return Array.isArray(value)?value:[];}catch{return [];}}
function publicBatch(batch:Row){return {batch_id:Number(batch.id),status:String(batch.status),processed_count:Number(batch.processed_count),record_count:Number(batch.record_count),imported_count:Number(batch.imported_count),skipped_count:Number(batch.skipped_count),error_count:Number(batch.error_count)};}
async function actualImported(ctx:AppContext,batch:Row){const m=member(ctx);const count=await ctx.env.DB.prepare('SELECT COUNT(*) c FROM family_logs WHERE import_batch_id=? AND family_id=? AND deleted_at IS NULL').bind(batch.id,m.family_id).first<Row>();return Number(count?.c||0);}
function errorsThrough(manifest:ManifestEntry[],processed:number){return manifest.filter(x=>x.offset+x.length<=processed).reduce((n,x)=>n+x.error_count,0);}

export async function familyLogImportApi(request:Request,ctx:AppContext):Promise<Response>{
  const m=member(ctx);if(!admin(m))throw new Forbidden('インポートはOWNER / ADMINのみ行えます。');if(request.method!=='POST')return json({ok:false,error:'POST only'},405);
  const b=await body(request);if(String(b.csrf||'')!==String(ctx.session.csrfToken||''))throw new Forbidden('CSRF検証に失敗しました。');const action=String(b.action||'preview');
  if(action==='status'){const batch=await getBatch(ctx,Number(b.batch_id||0));return json({ok:true,...publicBatch(batch)});}
  if(action==='repair_preview'||action==='repair_apply'||action==='repair_rollback'){
    const batch=await getBatch(ctx,Number(b.batch_id||0));if(String(batch.source).toLowerCase()!=='piyolog'||String(batch.status)!=='COMPLETED')throw new BadRequest('旧ぴよログの完了batchだけが時刻補正対象です。');
    const family=await ctx.env.DB.prepare('SELECT timezone FROM families WHERE id=?').bind(m.family_id).first<Row>(),timezone=String(family?.timezone||DEFAULT_FAMILY_TIMEZONE);
    const existing=await ctx.env.DB.prepare("SELECT * FROM family_log_time_repairs WHERE import_batch_id=? AND repair_type='WAVE88_90_UTC_NAIVE'").bind(batch.id).first<Row>();
    if(action==='repair_rollback'){
      if(!existing||existing.rolled_back_at)throw new BadRequest('適用済みで未rollbackの補正がありません。');const now=familyNow(timezone),offset=Number(existing.offset_minutes);
      await ctx.env.DB.prepare("UPDATE family_logs SET occurred_at=datetime(occurred_at,?),updated_at=? WHERE import_batch_id=? AND family_id=? AND deleted_at IS NULL AND updated_at=?").bind(`${-offset} minutes`,now,batch.id,m.family_id,String(existing.performed_at)).run();
      await ctx.env.DB.prepare('UPDATE family_log_time_repairs SET rolled_back_by=?,rolled_back_at=? WHERE id=? AND rolled_back_at IS NULL').bind(m.id,now,existing.id).run();return json({ok:true,rolled_back:true});
    }
    if(existing)throw new BadRequest(existing.rolled_back_at?'この補正は適用・rollback済みです。':'このbatchは補正済みです。');
    const samples=await ctx.env.DB.prepare('SELECT id,occurred_at,created_at,updated_at FROM family_logs WHERE import_batch_id=? AND family_id=? AND deleted_at IS NULL ORDER BY id LIMIT 5').bind(batch.id,m.family_id).all<Row>();
    const first=String(samples.results[0]?.occurred_at||'');if(!first)throw new BadRequest('補正対象がありません。');const offset=timezoneOffsetMinutesAt(first,timezone);
    const counts=await ctx.env.DB.prepare('SELECT COUNT(*) total,SUM(CASE WHEN updated_at<>created_at THEN 1 ELSE 0 END) edited FROM family_logs WHERE import_batch_id=? AND family_id=? AND deleted_at IS NULL').bind(batch.id,m.family_id).first<Row>();
    const preview={batch_id:Number(batch.id),source:String(batch.source),timezone,offset_minutes:offset,target_count:Number(counts?.total||0)-Number(counts?.edited||0),skipped_edited_count:Number(counts?.edited||0),samples:samples.results.filter(x=>x.updated_at===x.created_at).map(x=>({id:x.id,before:x.occurred_at,after:addWallClockMinutes(String(x.occurred_at),offset)}))};
    if(action==='repair_preview')return json({ok:true,...preview});
    const now=familyNow(timezone),result=await ctx.env.DB.prepare("UPDATE family_logs SET occurred_at=datetime(occurred_at,?),updated_at=? WHERE import_batch_id=? AND family_id=? AND deleted_at IS NULL AND updated_at=created_at").bind(`${offset} minutes`,now,batch.id,m.family_id).run();
    await ctx.env.DB.prepare("INSERT INTO family_log_time_repairs(family_id,import_batch_id,repair_type,repair_reason,offset_minutes,affected_count,skipped_edited_count,performed_by,performed_at) VALUES(?,?,'WAVE88_90_UTC_NAIVE','Wave88-90 importer stripped UTC designator after instant conversion',?,?,?,?,?)").bind(m.family_id,batch.id,offset,Number(result.meta.changes||0),preview.skipped_edited_count,m.id,now).run();return json({ok:true,...preview,affected_count:Number(result.meta.changes||0)});
  }
  if(action==='rollback'){
    const batchId=Number(b.batch_id||0),batch=await getBatch(ctx,batchId);if(batch.rolled_back_at)return json({ok:true,already_rolled_back:true,deleted_count:0,edited_count:0});
    const edited=await ctx.env.DB.prepare('SELECT COUNT(*) c FROM family_logs WHERE import_batch_id=? AND family_id=? AND deleted_at IS NULL AND updated_at<>created_at').bind(batchId,m.family_id).first<Row>();const now=nowJst();
    const result=await ctx.env.DB.prepare('UPDATE family_logs SET deleted_at=?,updated_at=? WHERE import_batch_id=? AND family_id=? AND deleted_at IS NULL AND updated_at=created_at').bind(now,now,batchId,m.family_id).run();
    await ctx.env.DB.prepare("UPDATE family_log_import_batches SET rolled_back_at=?,rolled_back_by=?,status='ROLLED_BACK' WHERE id=? AND family_id=? AND rolled_back_at IS NULL").bind(now,m.id,batchId,m.family_id).run();
    return json({ok:true,deleted_count:Number(result.meta.changes||0),edited_count:Number(edited?.c||0)});
  }
  if(action==='chunk'){
    const batch=await getBatch(ctx,Number(b.batch_id||0));if(batch.rolled_back_at||!['PREVIEWED','IMPORTING','FAILED'].includes(String(batch.status)))throw new BadRequest('このbatchは取り込めません。');
    const records=b.records;if(!Array.isArray(records)||records.length<1||records.length>CHUNK_SIZE)throw new BadRequest(`chunkは1〜${CHUNK_SIZE}件です。`);const offset=Number(b.offset);let transition;
    try{transition=validateChunkOffset(Number(batch.processed_count),Number(batch.record_count),offset,records.length);}catch{throw new BadRequest('chunk offsetは現在のprocessed_countと連続している必要があります。');}
    const manifest=manifestOf(batch),expected=manifest.find(x=>x.offset===offset);if(!expected||expected.length!==records.length||expected.hash!==await hash(JSON.stringify(records)))throw new BadRequest('chunkが開始時のdocumentと一致しません。');
    if(transition.retry)return json({ok:true,...publicBatch(batch),retried:true});
    const family=await ctx.env.DB.prepare('SELECT timezone FROM families WHERE id=?').bind(m.family_id).first<Row>(),timezone=String(family?.timezone||DEFAULT_FAMILY_TIMEZONE);const now=familyNow(timezone),statements:any[]=[];
    for(const raw of records){try{const v=normalize(raw as ImportRecord,timezone),key=await hash(canonical(Number(m.family_id),Number(batch.subject_id),String(batch.source),v));const rawDate=String((raw as ImportRecord).occurred_at||'');let legacyKey=key;if(/(?:Z|[+-]\d{2}:?\d{2})$/i.test(rawDate)){legacyKey=await hash(canonical(Number(m.family_id),Number(batch.subject_id),String(batch.source),{...v,occurred_at:new Date(rawDate).toISOString().slice(0,19).replace('T',' ')}));}statements.push(ctx.env.DB.prepare('INSERT OR IGNORE INTO family_logs(family_id,subject_id,log_type,occurred_at,detail_code,amount,unit,duration_minutes,value_text,note,linked_task_id,linked_occurrence_id,created_by,created_at,updated_at,import_batch_id,import_source_key,import_source_text,import_source_page,import_external_id) SELECT ?,?,?,?,?,?,?,?,?,?,NULL,NULL,?,?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM family_logs WHERE family_id=? AND subject_id=? AND import_source_key=? AND deleted_at IS NULL)').bind(m.family_id,batch.subject_id,v.log_type,v.occurred_at,v.detail_code,v.amount,v.unit,v.duration_minutes,v.value_text,v.note,m.id,now,now,batch.id,key,v.source_text,v.source_page,v.external_id,m.family_id,batch.subject_id,legacyKey));}catch{/* manifest accounts for preview validation errors */}}
    try{
      if(statements.length)await ctx.env.DB.batch(statements);
      const imported=await actualImported(ctx,batch),processed=transition.nextProcessedCount,processedErrors=errorsThrough(manifest,processed),skipped=processed-processedErrors-imported;
      if(skipped<0)throw new Error('import outcome count invariant failed');
      await ctx.env.DB.prepare("UPDATE family_log_import_batches SET status='IMPORTING',processed_count=?,imported_count=?,skipped_count=?,failed_at=NULL WHERE id=? AND family_id=? AND processed_count=?").bind(processed,imported,skipped,batch.id,m.family_id,offset).run();
      return json({ok:true,batch_id:Number(batch.id),status:'IMPORTING',processed_count:processed,record_count:Number(batch.record_count),imported_count:imported,skipped_count:skipped,error_count:Number(batch.error_count)});
    }catch(e){await ctx.env.DB.prepare("UPDATE family_log_import_batches SET status='FAILED',failed_at=? WHERE id=? AND family_id=?").bind(now,batch.id,m.family_id).run();throw e;}
  }
  if(action==='finish'){
    const batch=await getBatch(ctx,Number(b.batch_id||0)),imported=await actualImported(ctx,batch),manifest=manifestOf(batch),processed=Number(batch.processed_count),recordCount=Number(batch.record_count),errors=errorsThrough(manifest,processed),skipped=processed-errors-imported;
    try{validateFinishCounts(batch.status,Boolean(batch.rolled_back_at),processed,recordCount,imported,skipped,errors);if(errors!==Number(batch.error_count))throw new Error();}catch{throw new BadRequest(processed>recordCount?'processed_countが全件数を超えています。':'完了条件または件数整合性を満たしていません。');}
    const now=nowJst();await ctx.env.DB.prepare("UPDATE family_log_import_batches SET status='COMPLETED',imported_count=?,skipped_count=?,error_count=?,completed_at=?,failed_at=NULL WHERE id=? AND family_id=?").bind(imported,skipped,errors,now,batch.id,m.family_id).run();
    return json({ok:true,batch_id:Number(batch.id),status:'COMPLETED',processed_count:processed,record_count:recordCount,imported_count:imported,skipped_count:skipped,error_count:errors});
  }
  const subjectId=Number(b.subject_id||0),doc=b.document;if(!doc||typeof doc!=='object'||Array.isArray(doc))throw new BadRequest('import documentが不正です。');const preview=await inspect(ctx,subjectId,doc as Record<string,unknown>);
  if(action==='preview')return json({ok:true,...preview,rows:preview.rows.slice(0,50),chunk_size:CHUNK_SIZE});if(action!=='start'&&action!=='confirm')throw new BadRequest('操作が不正です。');
  const records=(doc as Record<string,unknown>).records as unknown[],manifest:ManifestEntry[]=[];for(let offset=0;offset<records.length;offset+=CHUNK_SIZE){const part=records.slice(offset,offset+CHUNK_SIZE);manifest.push({offset,length:part.length,hash:await hash(JSON.stringify(part)),error_count:preview.rows.slice(offset,offset+part.length).filter((x:any)=>x.status==='error').length});}
  const filename=text(b.source_filename,255),now=nowJst();const old=await ctx.env.DB.prepare("SELECT * FROM family_log_import_batches WHERE family_id=? AND subject_id=? AND source_hash=? AND status IN ('PREVIEWED','IMPORTING','FAILED') AND rolled_back_at IS NULL ORDER BY id DESC LIMIT 1").bind(m.family_id,subjectId,preview.source_hash).first<Row>();
  if(old)return json({ok:true,...publicBatch(old),chunk_size:CHUNK_SIZE,resumed:true});
  const result=await ctx.env.DB.prepare("INSERT INTO family_log_import_batches(family_id,subject_id,source,source_filename,source_hash,record_count,imported_count,skipped_count,error_count,created_by,created_at,status,processed_count,chunk_manifest_json) VALUES(?,?,?,?,?,?,0,0,?,?,?,'PREVIEWED',0,?)").bind(m.family_id,subjectId,preview.source,filename,preview.source_hash,preview.record_count,preview.error_count,m.id,now,JSON.stringify(manifest)).run();
  return json({ok:true,batch_id:Number(result.meta.last_row_id),status:'PREVIEWED',processed_count:0,record_count:preview.record_count,imported_count:0,skipped_count:0,error_count:preview.error_count,chunk_size:CHUNK_SIZE});
}
export async function familyLogImportPage(ctx:AppContext):Promise<Response>{
  const m=member(ctx);if(!admin(m))throw new Forbidden('インポートはOWNER / ADMINのみ行えます。');
  const [subjects,batches,repairs]=await Promise.all([
    ctx.env.DB.prepare("SELECT id,name,subject_kind FROM family_log_subjects WHERE family_id=? AND active=1 AND subject_kind IN ('BABY','CHILD','ADULT','PET','OTHER') ORDER BY id").bind(m.family_id).all<Row>(),
    ctx.env.DB.prepare('SELECT b.*,s.name subject_name,c.name creator_name FROM family_log_import_batches b LEFT JOIN family_log_subjects s ON s.id=b.subject_id LEFT JOIN members c ON c.id=b.created_by WHERE b.family_id=? ORDER BY b.id DESC LIMIT 50').bind(m.family_id).all<Row>(),
    ctx.env.DB.prepare("SELECT * FROM family_log_time_repairs WHERE family_id=? AND repair_type='WAVE88_90_UTC_NAIVE'").bind(m.family_id).all<Row>()
  ]);
  const incomplete=batches.results.filter(b=>['IMPORTING','FAILED','PREVIEWED'].includes(String(b.status))&&!b.rolled_back_at);
  const payload=JSON.stringify({csrf:ctx.session.csrfToken||'',types:TYPES,maxBytes:MAX_BODY_BYTES,subjects:Object.fromEntries(subjects.results.map(s=>[String(s.id),String(s.name)]))}).replaceAll('<','\\u003c');
  const repairByBatch=new Map(repairs.results.map(r=>[Number(r.import_batch_id),r]));
  const history=batches.results.map(b=>{const state=String(b.status||'COMPLETED'),progress=['IMPORTING','FAILED'].includes(state)?`・処理済: ${b.processed_count} / ${b.record_count}`:'';const resume=state==='FAILED'?'<strong class="is-error">再開可能（同じJSONファイルが必要）</strong>':'';return `<div class="import-history-row"><div><strong>${esc(b.source)} → ${esc(b.subject_name)}</strong><div class="meta">${esc(b.created_at)} / ${esc(b.creator_name)}</div><div class="small">${esc(state)}・全${b.record_count}・取込${b.imported_count}・重複${b.skipped_count}・エラー${b.error_count}${progress}</div>${resume}</div>${b.rolled_back_at?'':`<button class="btn danger small import-rollback" data-id="${b.id}">このインポートを取り消す</button>`}${String(b.source).toLowerCase()==='piyolog'&&state==='COMPLETED'?(repairByBatch.get(Number(b.id))?(!repairByBatch.get(Number(b.id))?.rolled_back_at?`<button class="btn gray small import-time-repair-rollback" data-id="${b.id}">時刻補正を戻す</button>`:''):`<button class="btn small import-time-repair" data-id="${b.id}">時刻補正</button>`):''}</div>`;}).join('');
  const pending=incomplete.length?'<div class="notice">未完了のインポートがあります。再開するには、同じ対象と同じJSONファイルを選択してください。source hash一致後に続きから処理します。</div>':'';
  const bodyHtml=`<div class="page-head"><div><div class="eyebrow">Family Log</div><h1>📥 データをインポート</h1></div><a class="btn gray" href="/app/family_log.php">戻る</a></div>${pending}<div class="notice">標準JSON（<code>${FORMAT}</code>、最大3MB / 5,000件）だけを受け付けます。原本JSONは保存しません。</div><div class="card import-wizard"><label>取り込み先</label><select id="importSubject"><option value="">選択してください</option>${subjects.results.map(s=>`<option value="${s.id}">${esc(s.name)} (${esc(s.subject_kind)})</option>`).join('')}</select><label>JSONファイル</label><input id="importFile" type="file" accept="application/json,.json"><button id="importPreview" type="button">解析してプレビュー</button><div id="importStatus" class="small"></div><div id="importPreviewOut"></div></div><div class="card"><h2>インポート履歴</h2>${history||'<p class="empty">履歴はありません。</p>'}</div><script type="application/json" id="familyLogImportPayload">${payload}</script><script src="/assets/family-log-import.js?v=12.118-wave99"></script>`;
  return html(layout('Family Logインポート',bodyHtml,'/app/family_log.php'));
}
