import { html, json, redirect } from './response';
import type { AppContext } from './app';
import { recordQuickChoreDomain, startDedicatedSleepDomain, stopDedicatedSleepDomain, layout } from './app';
import type { CurrentMember } from './types';

type Row=Record<string,unknown>;
const ACCESS_SECONDS=3600, CODE_SECONDS=300;
const SCENE_NAME_MAX=80;
const nowText=()=>new Date().toISOString().slice(0,19).replace('T',' ');
const escapeHtml=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const safeEqual=(a:string,b:string)=>{const aa=new TextEncoder().encode(a),bb=new TextEncoder().encode(b);if(aa.length!==bb.length)return false;let d=0;for(let i=0;i<aa.length;i++)d|=aa[i]^bb[i];return d===0;};
async function hash(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
const base64url=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
async function hmac(secret:string,value:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return base64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value))));}
async function refreshedAccessToken(env:Env,row:Row,now:number){const expires=Math.ceil(now/60)*60+ACCESS_SECONDS,payload=`${row.id}.${expires}`,signature=await hmac(String(env.APP_SECRET),`${payload}.${row.refresh_token_hash}`);return {token:`gh1.${payload}.${signature}`,expires};}
async function verifyRefreshedAccessToken(env:Env,token:string,now:number){const match=/^gh1\.(\d+)\.(\d+)\.([A-Za-z0-9_-]+)$/.exec(token);if(!match||Number(match[2])<now)return null;const row=await env.DB.prepare('SELECT * FROM google_home_tokens WHERE id=? AND revoked_at IS NULL LIMIT 1').bind(Number(match[1])).first<Row>();if(!row)return null;const expected=await hmac(String(env.APP_SECRET),`${match[1]}.${match[2]}.${row.refresh_token_hash}`);return safeEqual(match[3],expected)?row:null;}
async function form(request:Request){const fd=await request.formData(),out:Record<string,string>={};fd.forEach((v,k)=>{out[k]=String(v)});return out;}
function oauthError(error:string,description:string,status=400){return json({error,error_description:description},status,{'cache-control':'no-store','pragma':'no-cache'});}
export function allowedGoogleHomeRedirects(env:Env){const project=String(env.GOOGLE_HOME_PROJECT_ID||'').trim(),allowed=new Set<string>();if(project&&!/[/?#]/.test(project)){allowed.add(`https://oauth-redirect.googleusercontent.com/r/${project}`);allowed.add(`https://oauth-redirect-sandbox.googleusercontent.com/r/${project}`);}if(env.GOOGLE_HOME_REDIRECT_URI)allowed.add(String(env.GOOGLE_HOME_REDIRECT_URI).trim());return allowed;}
function configured(env:Env){return Boolean(env.GOOGLE_HOME_CLIENT_ID&&env.GOOGLE_HOME_CLIENT_SECRET&&(env.GOOGLE_HOME_PROJECT_ID||env.GOOGLE_HOME_REDIRECT_URI));}
function validRedirect(env:Env,redirectUri:string){return [...allowedGoogleHomeRedirects(env)].some(x=>safeEqual(redirectUri,x));}
function validAuthorize(env:Env,clientId:string,redirectUri:string,responseType:string){return configured(env)&&safeEqual(clientId,String(env.GOOGLE_HOME_CLIENT_ID))&&validRedirect(env,redirectUri)&&responseType==='code';}
async function audit(env:Env,familyId:unknown,memberId:unknown,action:string,stage:string,result='success'){await env.DB.prepare('INSERT INTO activity_logs(family_id,member_id,action,target_type,target_id,metadata,occurred_at) VALUES(?,?,?,?,?,?,?)').bind(familyId,memberId,action,'google_home',null,JSON.stringify({stage,result}),nowText()).run().catch(()=>{});}

export async function googleAuthorize(request:Request,ctx:AppContext):Promise<Response>{
  const input=request.method==='POST'?await form(request):(()=>{const out:Record<string,string>={};new URL(request.url).searchParams.forEach((v,k)=>{out[k]=v});return out;})();
  const clientId=String(input.client_id||''),redirectUri=String(input.redirect_uri||''),state=String(input.state||''),responseType=String(input.response_type||'');
  if(!validAuthorize(ctx.env,clientId,redirectUri,responseType))return html(layout('Google Home 連携','<div class="card"><h1>連携リクエストが無効です</h1><p>client_id、redirect_uri または response_type を確認してください。</p></div>'),400);
  if(!ctx.member){const next=new URL(request.url);return redirect(`/login.php?next=${encodeURIComponent(next.pathname+next.search)}`);}
  if(request.method==='GET'){
    await audit(ctx.env,ctx.member.family_id,ctx.member.id,'GOOGLE_HOME_AUTHORIZE_STARTED','authorize');
    const hidden=`<input type="hidden" name="client_id" value="${escapeHtml(clientId)}"><input type="hidden" name="redirect_uri" value="${escapeHtml(redirectUri)}"><input type="hidden" name="response_type" value="code"><input type="hidden" name="state" value="${escapeHtml(state)}"><input type="hidden" name="csrf" value="${escapeHtml(ctx.session.csrfToken||'')}">`;
    return html(layout('Google Home 連携',`<div class="card"><h1>GoogleとFamily TODOを連携します</h1><p>連携することで、GoogleによるFamily TODOの操作を許可します。</p><p>連携後は、Googleから${escapeHtml(ctx.member.name)} さんの操作として睡眠開始・終了やちょこっと家事を記録できます。</p><form method="post">${hidden}<div class="actions"><button class="btn" name="decision" value="allow">連携する</button><button class="btn gray" name="decision" value="cancel">キャンセル</button></div></form></div>`));
  }
  if(!ctx.session.csrfToken||!safeEqual(String(input.csrf||''),ctx.session.csrfToken))return html(layout('Google Home 連携','<div class="card"><h1>セッションを確認できません</h1></div>'),403);
  const destination=new URL(redirectUri);destination.searchParams.set('state',state);
  if(input.decision!=='allow'){destination.searchParams.set('error','access_denied');return redirect(destination.toString());}
  const code=randomToken(),now=Math.floor(Date.now()/1000);
  await ctx.env.DB.prepare('INSERT INTO google_home_authorization_codes(code_hash,family_id,member_id,client_id,redirect_uri,expires_at,created_at) VALUES(?,?,?,?,?,?,?)').bind(await hash(code),ctx.member.family_id,ctx.member.id,clientId,redirectUri,now+CODE_SECONDS,nowText()).run();
  await audit(ctx.env,ctx.member.family_id,ctx.member.id,'GOOGLE_HOME_AUTHORIZED','consent');
  destination.searchParams.set('code',code);return redirect(destination.toString());
}

function clientCredentials(request:Request,input:Record<string,string>){let id=input.client_id||'',secret=input.client_secret||'';const auth=request.headers.get('authorization')||'';if(auth.startsWith('Basic ')){try{const decoded=atob(auth.slice(6));const colon=decoded.indexOf(':');id=decodeURIComponent(decoded.slice(0,colon));secret=decodeURIComponent(decoded.slice(colon+1));}catch{/* invalid below */}}return {id,secret};}
export async function googleToken(request:Request,env:Env):Promise<Response>{
  if(request.method!=='POST')return oauthError('invalid_request','POST is required',405);
  const input=await form(request),credentials=clientCredentials(request,input);
  if(!configured(env)||!safeEqual(credentials.id,String(env.GOOGLE_HOME_CLIENT_ID||''))||!safeEqual(credentials.secret,String(env.GOOGLE_HOME_CLIENT_SECRET||'')))return oauthError('invalid_client','Client authentication failed',401);
  const now=Math.floor(Date.now()/1000),created=nowText();
  if(input.grant_type==='authorization_code'){
    if(!validRedirect(env,input.redirect_uri||''))return oauthError('invalid_grant','redirect_uri does not match');
    const codeHash=await hash(input.code||'');
    const code=await env.DB.prepare('SELECT * FROM google_home_authorization_codes WHERE code_hash=? AND client_id=? AND redirect_uri=? AND used_at IS NULL LIMIT 1').bind(codeHash,credentials.id,input.redirect_uri).first<Row>();
    if(!code||Number(code.expires_at)<now)return oauthError('invalid_grant','Code is invalid, expired, or already used');
    const used=await env.DB.prepare('UPDATE google_home_authorization_codes SET used_at=? WHERE id=? AND used_at IS NULL AND expires_at>=?').bind(now,code.id,now).run();if(!used.meta.changes)return oauthError('invalid_grant','Code is invalid, expired, or already used');
    const access=randomToken(),refresh=randomToken();
    await env.DB.prepare('INSERT INTO google_home_tokens(family_id,member_id,access_token_hash,refresh_token_hash,access_expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(code.family_id,code.member_id,await hash(access),await hash(refresh),now+ACCESS_SECONDS,created,created).run();
    await audit(env,code.family_id,code.member_id,'GOOGLE_HOME_TOKEN_ISSUED','token');
    return json({token_type:'Bearer',access_token:access,refresh_token:refresh,expires_in:ACCESS_SECONDS},200,{'cache-control':'no-store','pragma':'no-cache'});
  }
  if(input.grant_type==='refresh_token'){
    const row=await env.DB.prepare('SELECT * FROM google_home_tokens WHERE refresh_token_hash=? AND revoked_at IS NULL LIMIT 1').bind(await hash(input.refresh_token||'')).first<Row>();if(!row)return oauthError('invalid_grant','Refresh token is invalid or revoked');
    // Refresh tokens are deliberately not rotated. A signed, expiring access token
    // is deterministic for the current minute, so concurrent refreshes cannot
    // invalidate one another and no raw credential is persisted.
    const access=await refreshedAccessToken(env,row,now);console.log(JSON.stringify({category:'GOOGLE_HOME_TOKEN_REFRESHED',family_id:row.family_id,member_id:row.member_id,stage:'token',result:'success'}));
    return json({token_type:'Bearer',access_token:access.token,expires_in:access.expires-now},200,{'cache-control':'no-store','pragma':'no-cache'});
  }
  return oauthError('unsupported_grant_type','Only authorization_code and refresh_token are supported');
}

async function bearerMember(request:Request,env:Env){const header=request.headers.get('authorization')||'';if(!header.startsWith('Bearer '))return null;const token=header.slice(7).trim();if(!token)return null;const now=Math.floor(Date.now()/1000),refreshed=await verifyRefreshedAccessToken(env,token,now);const tokenId=refreshed?.id;return tokenId?env.DB.prepare(`SELECT t.id token_id,m.* FROM google_home_tokens t JOIN members m ON m.id=t.member_id AND m.family_id=t.family_id WHERE t.id=? AND t.revoked_at IS NULL AND m.active=1 AND m.deleted_at IS NULL LIMIT 1`).bind(tokenId).first<CurrentMember&{token_id:number}>():env.DB.prepare(`SELECT t.id token_id,m.* FROM google_home_tokens t JOIN members m ON m.id=t.member_id AND m.family_id=t.family_id WHERE t.access_token_hash=? AND t.revoked_at IS NULL AND t.access_expires_at>=? AND m.active=1 AND m.deleted_at IS NULL LIMIT 1`).bind(await hash(token),now).first<CurrentMember&{token_id:number}>();}
export function safeSceneName(value:unknown){return String(value??'').normalize('NFKC').replace(/[\u0000-\u001f\u007f]/g,'').replace(/\s+/g,' ').trim().slice(0,SCENE_NAME_MAX);}
function scene(id:string,name:string){const safe=safeSceneName(name)||'Family TODO 操作';return {id,type:'action.devices.types.SCENE',traits:['action.devices.traits.Scene'],name:{name:safe,nicknames:[safe]},willReportState:false,attributes:{sceneReversible:false}};}
async function sceneCatalog(env:Env,familyId:unknown){const [subjects,chores]=await Promise.all([env.DB.prepare("SELECT id,name FROM family_log_subjects WHERE family_id=? AND active=1 AND subject_kind IN ('BABY','CHILD') ORDER BY id").bind(familyId).all<Row>(),env.DB.prepare('SELECT id,name FROM family_quick_chores WHERE family_id=? AND active=1 ORDER BY sort_order,id').bind(familyId).all<Row>()]);const scenes:any[]=[];for(const s of subjects.results){scenes.push({...scene(`ft:sleep:start:${s.id}`,`${s.name}寝た`),category:'睡眠'},{...scene(`ft:sleep:stop:${s.id}`,`${s.name}起きた`),category:'睡眠'});}for(const c of chores.results)scenes.push({...scene(`ft:chore:${c.id}`,`${c.name}完了`),category:'ちょこっと家事'});return scenes;}
async function sync(env:Env,member:CurrentMember,requestId:string){const devices=await sceneCatalog(env,member.family_id);await audit(env,member.family_id,member.id,'GOOGLE_HOME_SYNCED','sync',`success:${devices.length}`);return json({requestId,payload:{agentUserId:`ft-member-${member.id}`,devices:devices.map(({category,...device})=>device)}});}
function executeResponse(requestId:string,ids:string[],status:string,errorCode?:string){return {requestId,payload:{commands:[{ids,status,...(errorCode?{errorCode}:{})}]}};}
async function execute(env:Env,member:CurrentMember,body:any,requestId:string){const commands=Array.isArray(body?.inputs?.[0]?.payload?.commands)?body.inputs[0].payload.commands:[];const responses:any[]=[];for(const group of commands){const ids=Array.isArray(group.devices)?group.devices.map((d:any)=>String(d.id||'')):[];for(const execution of Array.isArray(group.execution)?group.execution:[]){if(execution.command!=='action.devices.commands.ActivateScene'||execution.params?.deactivate===true){responses.push(...ids.map((id:string)=>executeResponse(requestId,[id],'ERROR','functionNotSupported').payload.commands));continue;}for(const id of ids){const key=`${id}:activate`;const inserted=await env.DB.prepare("INSERT OR IGNORE INTO external_command_receipts(provider,family_id,member_id,request_id,command_key,status,created_at,updated_at) VALUES('GOOGLE_HOME',?,?,?,?, 'PENDING',?,?)").bind(member.family_id,member.id,requestId,key,nowText(),nowText()).run();if(!inserted.meta.changes){const old=await env.DB.prepare("SELECT status,error_code FROM external_command_receipts WHERE provider='GOOGLE_HOME' AND request_id=? AND command_key=?").bind(requestId,key).first<Row>();responses.push({ids:[id],status:String(old?.status)==='ERROR'?'ERROR':'SUCCESS',...(old?.error_code?{errorCode:String(old.error_code)}:{})});continue;}let error='';try{let ok=false;if(/^ft:sleep:start:\d+$/.test(id))ok=(await startDedicatedSleepDomain(env,member,Number(id.split(':')[3]))).ok;else if(/^ft:sleep:stop:\d+$/.test(id))ok=(await stopDedicatedSleepDomain(env,member,Number(id.split(':')[3]))).ok;else if(/^ft:chore:\d+$/.test(id))ok=(await recordQuickChoreDomain(env,member,Number(id.split(':')[2]))).ok;else error='deviceNotFound';if(!ok&&!error)error='deviceNotFound';}catch{error='hardError';}await env.DB.prepare('UPDATE external_command_receipts SET status=?,error_code=?,updated_at=? WHERE provider=? AND request_id=? AND command_key=?').bind(error?'ERROR':'SUCCESS',error||null,nowText(),'GOOGLE_HOME',requestId,key).run();responses.push({ids:[id],status:error?'ERROR':'SUCCESS',...(error?{errorCode:error}:{})});}}}return json({requestId,payload:{commands:responses}});}
export async function googleFulfillment(request:Request,env:Env):Promise<Response>{if(request.method!=='POST')return json({error:'method_not_allowed'},405);const member=await bearerMember(request,env);if(!member)return json({error:'unauthorized'},401);const body=await request.json().catch(()=>null) as any;if(!body||!Array.isArray(body.inputs))return json({error:'invalid_request'},400);const requestId=String(body.requestId||crypto.randomUUID()),intent=String(body.inputs[0]?.intent||'');if(intent==='action.devices.SYNC')return sync(env,member,requestId);if(intent==='action.devices.EXECUTE')return execute(env,member,body,requestId);if(intent==='action.devices.DISCONNECT'){await env.DB.prepare('UPDATE google_home_tokens SET revoked_at=?,updated_at=? WHERE family_id=? AND member_id=? AND revoked_at IS NULL').bind(nowText(),nowText(),member.family_id,member.id).run();await audit(env,member.family_id,member.id,'GOOGLE_HOME_DISCONNECTED','disconnect');return json({});}if(intent==='action.devices.QUERY')return json({requestId,payload:{devices:{}}});return json({requestId,payload:{errorCode:'protocolError'}},400);}

export async function googleHomeSettings(request:Request,ctx:AppContext):Promise<Response>{
  if(!ctx.member)return redirect('/login.php');
  if(request.method==='POST'){const input=await form(request);if(!ctx.session.csrfToken||!safeEqual(input.csrf||'',ctx.session.csrfToken))return json({ok:false,error:'CSRF検証に失敗しました。'},403);await ctx.env.DB.prepare('UPDATE google_home_tokens SET revoked_at=?,updated_at=? WHERE family_id=? AND member_id=? AND revoked_at IS NULL').bind(nowText(),nowText(),ctx.member.family_id,ctx.member.id).run();await audit(ctx.env,ctx.member.family_id,ctx.member.id,'GOOGLE_HOME_DISCONNECTED','settings');return redirect('/app/settings_google_home.php');}
  const origin=new URL(request.url).origin,project=String(ctx.env.GOOGLE_HOME_PROJECT_ID||'').trim(),isAdmin=['OWNER','ADMIN'].includes(String(ctx.member.role||'').toUpperCase());
  const [link,recent,syncLog,scenes]=await Promise.all([
    ctx.env.DB.prepare('SELECT t.created_at,m.name FROM google_home_tokens t JOIN members m ON m.id=t.member_id WHERE t.family_id=? AND t.member_id=? AND t.revoked_at IS NULL ORDER BY t.id DESC LIMIT 1').bind(ctx.member.family_id,ctx.member.id).first<Row>(),
    ctx.env.DB.prepare("SELECT status,error_code,command_key,updated_at FROM external_command_receipts WHERE provider='GOOGLE_HOME' AND family_id=? ORDER BY updated_at DESC,id DESC LIMIT 1").bind(ctx.member.family_id).first<Row>(),
    ctx.env.DB.prepare("SELECT occurred_at,metadata FROM activity_logs WHERE family_id=? AND action='GOOGLE_HOME_SYNCED' ORDER BY occurred_at DESC,id DESC LIMIT 1").bind(ctx.member.family_id).first<Row>(),
    sceneCatalog(ctx.env,ctx.member.family_id)
  ]);
  const configuredAll=configured(ctx.env),counts=new Map<string,number>();for(const s of scenes){const key=String(s.name.name).toLocaleLowerCase('ja');counts.set(key,(counts.get(key)||0)+1);}const duplicates=[...counts.values()].some(n=>n>1);
  const operation=recent?String(recent.command_key||'').startsWith('ft:sleep:start:')?'睡眠開始':String(recent.command_key||'').startsWith('ft:sleep:stop:')?'睡眠終了':String(recent.command_key||'').startsWith('ft:chore:')?'ちょこっと家事':'不明':'—';
  let syncCount='—';try{const result=JSON.parse(String(syncLog?.metadata||'{}')).result;syncCount=String(result||'').startsWith('success:')?String(result).slice(8):'—';}catch{/* safe diagnostic fallback */}
  const preview=scenes.slice(0,10).map(s=>`<li>${escapeHtml(s.category)} ・ ${escapeHtml(s.name.name)}</li>`).join('')||'<li>公開対象はありません</li>';
  const adminDetails=isAdmin?`<details class="card"><summary>Developer Console 設定値</summary><dl><dt>Authorization URL</dt><dd><code>${escapeHtml(origin)}/oauth/google/authorize</code></dd><dt>Token URL</dt><dd><code>${escapeHtml(origin)}/oauth/google/token</code></dd><dt>Fulfillment URL</dt><dd><code>${escapeHtml(origin)}/api/google-home/fulfillment</code></dd><dt>Client ID / Client Secret</dt><dd>Cloudflareの GOOGLE_HOME_CLIENT_ID / GOOGLE_HOME_CLIENT_SECRET と同じ値（画面には表示しません）</dd><dt>Project ID</dt><dd>${project?escapeHtml(project):'未設定'}</dd><dt>本番callback</dt><dd><code>${project?`https://oauth-redirect.googleusercontent.com/r/${escapeHtml(project)}`:'未設定'}</code></dd><dt>テストcallback</dt><dd><code>${project?`https://oauth-redirect-sandbox.googleusercontent.com/r/${escapeHtml(project)}`:'未設定'}</code></dd></dl></details>`:'';
  return html(layout('Google Home',`<div class="page-head"><div><div class="eyebrow">管理 → 外部連携</div><h1>Google Home</h1></div><a class="btn gray" href="/app/settings_integrations.php">戻る</a></div><div class="card"><h2>設定確認</h2><ul><li>Client ID: ${ctx.env.GOOGLE_HOME_CLIENT_ID?'✓':'未設定'}</li><li>Client Secret: ${ctx.env.GOOGLE_HOME_CLIENT_SECRET?'✓':'未設定'}</li><li>Project ID: ${project?'✓':'未設定'}</li><li>OAuth: ${configuredAll?'準備完了':'要設定'}</li><li>Scene: ${scenes.length}件</li><li>Account link: ${link?'連携中':'未連携'}</li></ul><p>${configuredAll?'✓ Google Home連携準備ができています':'不足している環境変数を設定してください。'}</p>${duplicates?'<p class="notice error">Google Homeで同名の操作があります</p>':''}<p class="small">credential値は表示しません。設定確認は外部Googleへ通信しません。</p></div><div class="card"><h2>Google Homeへ公開される操作（${scenes.length}件）</h2><ul>${preview}</ul>${scenes.length>10?`<p class="small">先頭10件を表示（ほか${scenes.length-10}件）</p>`:''}</div><div class="card"><h2>Account link: ${link?'連携中':'未連携'}</h2>${link?`<p>連携メンバー: ${escapeHtml(link.name)} / ${escapeHtml(link.created_at)}</p><form method="post"><input type="hidden" name="csrf" value="${escapeHtml(ctx.session.csrfToken||'')}"><button class="btn danger">連携解除</button></form>`:'<p>Google Homeアプリから連携してください。</p>'}<p class="small">Google Homeからの記録は連携したメンバーの操作として記録されます。</p></div><div class="card"><h2>安全な実行診断</h2><p>最終SYNC: ${escapeHtml(syncLog?.occurred_at||'未確認')} / Scene count: ${escapeHtml(syncCount)}</p><p>最終Google Home実行: ${escapeHtml(recent?.updated_at||'未確認')} / ${recent?String(recent.status)==='SUCCESS'?'成功':'失敗':'—'} / ${escapeHtml(operation)}</p><p class="small">request payload・OAuth token・stateは保存/表示しません。</p></div>${adminDetails}`,'/app/settings.php'));
}
export async function googleHomeHealth(env:Env){const counts=await env.DB.prepare('SELECT SUM(CASE WHEN revoked_at IS NULL THEN 1 ELSE 0 END) active_links,SUM(CASE WHEN revoked_at IS NOT NULL THEN 1 ELSE 0 END) revoked_links FROM google_home_tokens').first<Row>();return json({ok:true,google_home:{configured:configured(env),active_links:Number(counts?.active_links||0),revoked_links:Number(counts?.revoked_links||0)}});}
