import { html, json, redirect } from './response';
import { layout, type AppContext } from './app';
import { DEFAULT_FAMILY_TIMEZONE, familyNow } from './timezone';
type Row=Record<string,unknown>; const PROVIDER='GOOGLE_CALENDAR';
const now=()=>familyNow(DEFAULT_FAMILY_TIMEZONE);
const b64=(b:ArrayBuffer|Uint8Array)=>btoa(String.fromCharCode(...new Uint8Array(b instanceof ArrayBuffer?b:b.buffer)));
const unb64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function key(secret:string){const raw=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret));return crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);}
export async function encryptRefreshToken(token:string,secret:string,version='v1'){const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(secret),new TextEncoder().encode(token));return `${version}.${b64(iv)}.${b64(cipher)}`;}
export async function decryptRefreshToken(value:string,secret:string){const [version,iv,cipher]=value.split('.');if(!version||!iv||!cipher)throw new Error('invalid ciphertext');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(iv)},await key(secret),unb64(cipher)));}
async function signState(payload:string,secret:string){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(payload))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
async function state(familyId:number,memberId:number,secret:string){const p=btoa(JSON.stringify({familyId,memberId,exp:Date.now()+600000})).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');return `${p}.${await signState(p,secret)}`;}
async function verifyState(v:string,secret:string){const [p,s]=v.split('.');if(!p||s!==await signState(p,secret))throw new Error('invalid state');const x=JSON.parse(atob(p.replaceAll('-','+').replaceAll('_','/'))) as {familyId:number;memberId:number;exp:number};if(x.exp<Date.now())throw new Error('expired state');return x;}
const configured=(e:Env)=>Boolean(e.GOOGLE_CALENDAR_CLIENT_ID&&e.GOOGLE_CALENDAR_CLIENT_SECRET&&e.GOOGLE_CALENDAR_REDIRECT_URI&&e.GOOGLE_CALENDAR_TOKEN_KEY);
export async function googleCalendarAuthorize(_r:Request,ctx:AppContext){if(!ctx.member)return redirect('/login.php');if(!configured(ctx.env))return json({ok:false,error:'Google Calendarが設定されていません。'},503);const s=await state(ctx.member.family_id,ctx.member.id,ctx.env.APP_SECRET);const u=new URL('https://accounts.google.com/o/oauth2/v2/auth');u.searchParams.set('client_id',ctx.env.GOOGLE_CALENDAR_CLIENT_ID!);u.searchParams.set('redirect_uri',ctx.env.GOOGLE_CALENDAR_REDIRECT_URI!);u.searchParams.set('response_type','code');u.searchParams.set('scope','https://www.googleapis.com/auth/calendar');u.searchParams.set('access_type','offline');u.searchParams.set('prompt','consent');u.searchParams.set('state',s);return redirect(u.toString());}
async function api(path:string,access:string,init?:RequestInit){const r=await fetch(`https://www.googleapis.com/calendar/v3${path}`,{...init,headers:{authorization:`Bearer ${access}`,'content-type':'application/json',...(init?.headers||{})}});if(!r.ok)throw new Error(`Google Calendar ${r.status}`);return r.status===204?{}:r.json();}
export async function googleCalendarCallback(request:Request,env:Env){try{if(!configured(env))throw new Error('not configured');const u=new URL(request.url),s=await verifyState(u.searchParams.get('state')||'',env.APP_SECRET),code=u.searchParams.get('code');if(!code)throw new Error('missing code');const tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:env.GOOGLE_CALENDAR_CLIENT_ID!,client_secret:env.GOOGLE_CALENDAR_CLIENT_SECRET!,redirect_uri:env.GOOGLE_CALENDAR_REDIRECT_URI!,grant_type:'authorization_code'})});if(!tr.ok)throw new Error('token exchange');const t=await tr.json() as any;if(!t.refresh_token)throw new Error('missing refresh token');const family=await env.DB.prepare('SELECT timezone FROM families WHERE id=?').bind(s.familyId).first<Row>(),timezone=String(family?.timezone||DEFAULT_FAMILY_TIMEZONE);const cal=await api('/calendars',t.access_token,{method:'POST',body:JSON.stringify({summary:'Family TODO',timeZone:timezone})}) as any,cipher=await encryptRefreshToken(t.refresh_token,env.GOOGLE_CALENDAR_TOKEN_KEY!);const n=now();await env.DB.prepare(`INSERT INTO external_calendar_accounts(family_id,member_id,provider,refresh_token_ciphertext,token_key_version,calendar_id,calendar_name,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'ACTIVE',?,?) ON CONFLICT(family_id,provider) DO UPDATE SET member_id=excluded.member_id,refresh_token_ciphertext=excluded.refresh_token_ciphertext,token_key_version=excluded.token_key_version,calendar_id=excluded.calendar_id,status='ACTIVE',last_error=NULL,updated_at=excluded.updated_at`).bind(s.familyId,s.memberId,PROVIDER,cipher,'v1',String(cal.id),'Family TODO',n,n).run();await env.DB.prepare('INSERT OR IGNORE INTO calendar_sync_state(family_id,provider,calendar_id,updated_at) VALUES(?,?,?,?)').bind(s.familyId,PROVIDER,String(cal.id),n).run();return redirect('/app/settings_integrations.php?calendar=linked');}catch{return redirect('/app/settings_integrations.php?calendar=error');}}
export function eligibleTask(t:Row){return String(t.visibility_scope||'FAMILY')==='FAMILY'&&Number(t.calendar_visible)===1&&['TASK','EVENT'].includes(String(t.task_kind||'TASK').toUpperCase())&&Boolean(t.start_at||t.due_at)&&!t.recurrence_rule;}
export async function enqueueCalendarSync(db:D1Database,familyId:number,taskId:number,operation:'CREATE'|'UPDATE'|'DELETE') {const n=now(),linked=await db.prepare('SELECT id FROM external_calendar_accounts WHERE family_id=? AND provider=? AND status=\'ACTIVE\' AND calendar_id IS NOT NULL').bind(familyId,PROVIDER).first();if(!linked)return;await db.prepare(`INSERT INTO calendar_sync_outbox(family_id,task_id,provider,operation,status,next_retry_at,created_at,updated_at) VALUES(?,?,?,?,'PENDING',?,?,?) ON CONFLICT(provider,task_id) DO UPDATE SET operation=CASE WHEN excluded.operation='DELETE' THEN 'DELETE' WHEN calendar_sync_outbox.operation='CREATE' THEN 'CREATE' ELSE 'UPDATE' END,status='PENDING',next_retry_at=excluded.next_retry_at,last_error=NULL,updated_at=excluded.updated_at`).bind(familyId,taskId,PROVIDER,operation,n,n,n).run();}
async function accessToken(env:Env,a:Row){const refresh=await decryptRefreshToken(String(a.refresh_token_ciphertext),env.GOOGLE_CALENDAR_TOKEN_KEY!);const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.GOOGLE_CALENDAR_CLIENT_ID!,client_secret:env.GOOGLE_CALENDAR_CLIENT_SECRET!,refresh_token:refresh,grant_type:'refresh_token'})});if(!r.ok)throw new Error('revoked account');return String((await r.json() as any).access_token);}
export async function processCalendarOutbox(env:Env,limit=10){if(!configured(env))return;const rows=await env.DB.prepare("SELECT o.*,a.refresh_token_ciphertext,a.calendar_id,f.timezone FROM calendar_sync_outbox o JOIN families f ON f.id=o.family_id JOIN external_calendar_accounts a ON a.family_id=o.family_id AND a.provider=o.provider AND a.status='ACTIVE' WHERE o.status IN ('PENDING','ERROR') AND o.next_retry_at<=? AND o.retry_count<8 ORDER BY o.id LIMIT ?").bind(now(),limit).all<Row>();for(const o of rows.results){try{const task=await env.DB.prepare('SELECT * FROM tasks WHERE id=? AND family_id=?').bind(o.task_id,o.family_id).first<Row>(),link=await env.DB.prepare('SELECT * FROM external_calendar_links WHERE provider=? AND task_id=? AND family_id=?').bind(PROVIDER,o.task_id,o.family_id).first<Row>(),token=await accessToken(env,o),op=String(o.operation);if(op==='DELETE'||!task||!eligibleTask(task)){if(link)await api(`/calendars/${encodeURIComponent(String(o.calendar_id))}/events/${encodeURIComponent(String(link.external_event_id))}`,token,{method:'DELETE'});if(link)await env.DB.prepare('UPDATE external_calendar_links SET deleted_at=? WHERE id=? AND family_id=?').bind(now(),link.id,o.family_id).run();}else{const start=String(task.start_at||task.due_at),allDay=Number(task.all_day)===1,payload={summary:String(task.title),description:String(task.description||''),location:String(task.location||''),start:allDay?{date:start.slice(0,10)}:{dateTime:start.replace(' ','T'),timeZone:String(o.timezone||DEFAULT_FAMILY_TIMEZONE)},end:allDay?{date:String(task.end_at||start).slice(0,10)}:{dateTime:String(task.end_at||start).replace(' ','T'),timeZone:String(o.timezone||DEFAULT_FAMILY_TIMEZONE)}};const ev=await api(`/calendars/${encodeURIComponent(String(o.calendar_id))}/events${link?'/'+encodeURIComponent(String(link.external_event_id)):''}`,token,{method:link?'PUT':'POST',body:JSON.stringify(payload)}) as any;await env.DB.prepare(`INSERT INTO external_calendar_links(family_id,task_id,provider,calendar_id,external_event_id,external_etag,last_synced_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(provider,task_id) DO UPDATE SET calendar_id=excluded.calendar_id,external_event_id=excluded.external_event_id,external_etag=excluded.external_etag,last_synced_at=excluded.last_synced_at,deleted_at=NULL`).bind(o.family_id,o.task_id,PROVIDER,o.calendar_id,String(ev.id),String(ev.etag||''),now()).run();}await env.DB.prepare("UPDATE calendar_sync_outbox SET status='DONE',last_error=NULL,updated_at=? WHERE id=?").bind(now(),o.id).run();}catch(e){const count=Number(o.retry_count)+1,next=new Date(Date.now()+Math.min(86400000,60000*2**count)).toISOString().slice(0,19).replace('T',' ');await env.DB.prepare("UPDATE calendar_sync_outbox SET status='ERROR',retry_count=?,next_retry_at=?,last_error=?,updated_at=? WHERE id=?").bind(count,next,String(e instanceof Error?e.message:e).slice(0,500),now(),o.id).run();}}}
export async function integrationsSettings(_r:Request,ctx:AppContext){if(!ctx.member)return redirect('/login.php');const a=await ctx.env.DB.prepare('SELECT calendar_name,status,last_synced_at,last_error FROM external_calendar_accounts WHERE family_id=? AND provider=?').bind(ctx.member.family_id,PROVIDER).first<Row>(),p=await ctx.env.DB.prepare("SELECT COUNT(*) c FROM calendar_sync_outbox WHERE family_id=? AND status IN ('PENDING','ERROR')").bind(ctx.member.family_id).first<Row>();return html(layout('外部連携',`<div class="page-head"><h1>🔗 外部連携</h1><a class="btn gray" href="/app/settings.php">戻る</a></div><div class="card"><h2>Google Home</h2><a class="btn gray" href="/app/settings_google_home.php">設定を開く</a></div><div class="card"><h2>Google Calendar</h2><p>${a?.status==='ACTIVE'?'連携中':'未連携'}</p>${a?`<p class="small">${String(a.calendar_name)} / last sync ${String(a.last_synced_at||'未実行')} / pending ${Number(p?.c||0)}${a.last_error?' / last errorあり':''}</p>`:''}<a class="btn" href="/oauth/google-calendar/authorize">Google Calendarと連携</a></div><div class="card"><h2>Family AI</h2><p>Gemini API: ${ctx.env.GEMINI_API_KEY?'configured':'not configured'}</p><p class="small">API key・token・質問本文は表示・保存しません。</p></div>`, '/app/settings.php'));}
