import { utcNow } from './timezone';
type Row=Record<string,unknown>;type ServiceAccount={client_email:string;private_key:string;token_uri?:string};
export type RequestSyncStatus='NOT_CONFIGURED'|'INVALID_SERVICE_ACCOUNT_JSON'|'JWT_SIGN_FAILED'|`TOKEN_HTTP_${number}`|'TOKEN_MISSING'|`HOMEGRAPH_HTTP_${number}`|'SUCCESS';
const SCOPE='https://www.googleapis.com/auth/homegraph',REQUEST_SYNC_URL='https://homegraph.googleapis.com/v1/devices:requestSync';
let cached:{token:string;expiresAt:number}|null=null;
const b64url=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const encoded=(value:unknown)=>b64url(new TextEncoder().encode(JSON.stringify(value)));
function credentials(env:Env):ServiceAccount|null{try{const value=JSON.parse(String(env.GOOGLE_HOME_SERVICE_ACCOUNT_JSON||''));return value?.client_email&&value?.private_key?value:null;}catch{return null;}}
export function googleHomeServiceAccountReadiness(env:Env){return {present:Boolean(env.GOOGLE_HOME_SERVICE_ACCOUNT_JSON),valid:Boolean(credentials(env))};}
function pemBytes(pem:string){return Uint8Array.from(atob(pem.replace(/-----[^-]+-----/g,'').replace(/\s/g,'')),c=>c.charCodeAt(0));}
export const googleHomeRequestSyncConfigured=(env:Env)=>Boolean(credentials(env));
export async function createHomeGraphJwt(env:Env,nowSeconds=Math.floor(Date.now()/1000)){const service=credentials(env);if(!service)throw new Error('NOT_CONFIGURED');const audience=service.token_uri||'https://oauth2.googleapis.com/token',unsigned=`${encoded({alg:'RS256',typ:'JWT'})}.${encoded({iss:service.client_email,scope:SCOPE,aud:audience,iat:nowSeconds,exp:nowSeconds+3600})}`,key=await crypto.subtle.importKey('pkcs8',pemBytes(service.private_key),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']),signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(unsigned));return `${unsigned}.${b64url(new Uint8Array(signature))}`;}
async function accessToken(env:Env){if(cached&&cached.expiresAt>Date.now()+60_000)return cached.token;const service=credentials(env);if(!service)throw new Error('NOT_CONFIGURED');const response=await fetch(service.token_uri||'https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:await createHomeGraphJwt(env)})});if(!response.ok)throw new Error(`TOKEN_HTTP_${response.status}`);const body=await response.json() as {access_token?:string;expires_in?:number};if(!body.access_token)throw new Error('TOKEN_MISSING');cached={token:body.access_token,expiresAt:Date.now()+Math.max(60,Number(body.expires_in||3600))*1000};return cached.token;}
async function audit(env:Env,familyId:number,memberId:number,status:'SUCCESS'|'FAILED',detail?:string){await env.DB.prepare("INSERT INTO activity_logs(family_id,member_id,action,target_type,target_id,metadata,occurred_at) VALUES(?,?,'GOOGLE_HOME_REQUEST_SYNC','google_home',NULL,?,?)").bind(familyId,memberId,JSON.stringify({provider:'GOOGLE_HOME',status,detail:detail?.slice(0,80)}),utcNow()).run().catch(()=>{});}
function safeStatus(error:unknown):RequestSyncStatus{const value=error instanceof Error?error.message:'';if(/^TOKEN_HTTP_\d+$/.test(value)||/^HOMEGRAPH_HTTP_\d+$/.test(value)||value==='TOKEN_MISSING'||value==='NOT_CONFIGURED')return value as RequestSyncStatus;return 'JWT_SIGN_FAILED';}
export async function requestGoogleHomeSync(env:Env,familyId:number,memberId:number){const ready=googleHomeServiceAccountReadiness(env);if(!ready.present)return {ok:false,status:'NOT_CONFIGURED' as const};if(!ready.valid)return {ok:false,status:'INVALID_SERVICE_ACCOUNT_JSON' as const};try{const response=await fetch(REQUEST_SYNC_URL,{method:'POST',headers:{authorization:`Bearer ${await accessToken(env)}`,'content-type':'application/json'},body:JSON.stringify({agentUserId:`ft-member-${memberId}`,async:false})});if(!response.ok)throw new Error(`HOMEGRAPH_HTTP_${response.status}`);await audit(env,familyId,memberId,'SUCCESS','SUCCESS');return {ok:true,status:'SUCCESS' as const};}catch(error){const status=safeStatus(error);await audit(env,familyId,memberId,'FAILED',status);return {ok:false,status};}}
export async function requestGoogleHomeSyncForFamily(env:Env,familyId:number){const links=await env.DB.prepare('SELECT DISTINCT member_id FROM google_home_tokens WHERE family_id=? AND revoked_at IS NULL').bind(familyId).all<Row>();return Promise.all(links.results.map(row=>requestGoogleHomeSync(env,familyId,Number(row.member_id))));}
