import { html, json, redirect } from './response';
import { layout, type AppContext } from './app';
import { DEFAULT_FAMILY_TIMEZONE, addWallClockMinutes, parseImportDateTime, utcNow } from './timezone';
type Row=Record<string,unknown>; const PROVIDER='GOOGLE_CALENDAR';
export const GOOGLE_CALENDAR_SCOPE='https://www.googleapis.com/auth/calendar.app.created';
const now=()=>utcNow();
export const CALENDAR_MAX_RETRIES=8;
export function calendarRetryAt(retryCount:number,at=new Date()){return utcNow(new Date(at.getTime()+Math.min(86400000,60000*2**Math.max(1,retryCount))));}
export function calendarRetryDue(status:unknown,retryCount:unknown,nextRetryAt:unknown,at=new Date()){const count=Number(retryCount||0);if(count>=CALENDAR_MAX_RETRIES)return false;if(String(status)==='PENDING'&&count===0)return true;return String(nextRetryAt||'')<=utcNow(at);}
const syncLeases=new Map<number,Promise<number>>();
const esc=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const b64=(b:ArrayBuffer|Uint8Array)=>btoa(String.fromCharCode(...new Uint8Array(b instanceof ArrayBuffer?b:b.buffer)));
const unb64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function key(secret:string){const raw=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret));return crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);}
export async function encryptRefreshToken(token:string,secret:string,version='v1'){const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(secret),new TextEncoder().encode(token));return `${version}.${b64(iv)}.${b64(cipher)}`;}
export async function decryptRefreshToken(value:string,secret:string){const [version,iv,cipher]=value.split('.');if(!version||!iv||!cipher)throw new Error('invalid ciphertext');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(iv)},await key(secret),unb64(cipher)));}
async function signState(payload:string,secret:string){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(payload))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
async function state(familyId:number,memberId:number,secret:string){const p=btoa(JSON.stringify({familyId,memberId,exp:Date.now()+600000,nonce:crypto.randomUUID()})).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');return `${p}.${await signState(p,secret)}`;}
async function verifyState(v:string,secret:string){const [p,s]=v.split('.');if(!p||!s||s!==await signState(p,secret))throw new Error('invalid state');const x=JSON.parse(atob(p.replaceAll('-','+').replaceAll('_','/'))) as {familyId:number;memberId:number;exp:number};if(!Number.isSafeInteger(x.familyId)||!Number.isSafeInteger(x.memberId)||x.exp<Date.now())throw new Error('expired state');return x;}
export const googleCalendarConfiguration=(e:Env)=>({clientId:Boolean(e.GOOGLE_CALENDAR_CLIENT_ID),clientSecret:Boolean(e.GOOGLE_CALENDAR_CLIENT_SECRET),redirectUri:Boolean(e.GOOGLE_CALENDAR_REDIRECT_URI),tokenKey:Boolean(e.GOOGLE_CALENDAR_TOKEN_KEY)});
const configured=(e:Env)=>Object.values(googleCalendarConfiguration(e)).every(Boolean);
export async function googleCalendarAuthorize(_r:Request,ctx:AppContext){if(!ctx.member)return redirect('/login.php');const role=String(ctx.member.role||'').toUpperCase();if(role!=='OWNER'&&role!=='ADMIN')return redirect('/app/settings_integrations.php?calendar=forbidden');if(!configured(ctx.env))return redirect('/app/settings_integrations.php?calendar=not-configured');const s=await state(ctx.member.family_id,ctx.member.id,ctx.env.APP_SECRET);const u=new URL('https://accounts.google.com/o/oauth2/v2/auth');u.searchParams.set('client_id',ctx.env.GOOGLE_CALENDAR_CLIENT_ID!);u.searchParams.set('redirect_uri',ctx.env.GOOGLE_CALENDAR_REDIRECT_URI!);u.searchParams.set('response_type','code');u.searchParams.set('scope',GOOGLE_CALENDAR_SCOPE);u.searchParams.set('access_type','offline');u.searchParams.set('prompt','consent');u.searchParams.set('include_granted_scopes','true');u.searchParams.set('state',s);return redirect(u.toString());}
class GoogleError extends Error{constructor(public status:number){super(`Google Calendar HTTP ${status}`);}}
async function api(path:string,access:string,init?:RequestInit){const r=await fetch(`https://www.googleapis.com/calendar/v3${path}`,{...init,headers:{authorization:`Bearer ${access}`,'content-type':'application/json',...(init?.headers||{})}});if(!r.ok)throw new GoogleError(r.status);return r.status===204?{}:r.json();}
export async function googleCalendarCallback(request:Request,env:Env){try{if(!configured(env))throw new Error('not configured');const u=new URL(request.url),s=await verifyState(u.searchParams.get('state')||'',env.APP_SECRET),code=u.searchParams.get('code');if(!code||u.searchParams.get('error'))throw new Error('missing code');const member=await env.DB.prepare('SELECT m.id,m.family_id,m.active,m.deleted_at,f.timezone FROM members m JOIN families f ON f.id=m.family_id WHERE m.id=? AND m.family_id=?').bind(s.memberId,s.familyId).first<Row>();if(!member||Number(member.active)!==1||member.deleted_at)throw new Error('member changed');const tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:env.GOOGLE_CALENDAR_CLIENT_ID!,client_secret:env.GOOGLE_CALENDAR_CLIENT_SECRET!,redirect_uri:env.GOOGLE_CALENDAR_REDIRECT_URI!,grant_type:'authorization_code'})});if(!tr.ok)throw new Error('token exchange');const t=await tr.json() as any;if(!t.refresh_token)throw new Error('missing refresh token');const existing=await env.DB.prepare('SELECT * FROM external_calendar_accounts WHERE family_id=? AND provider=?').bind(s.familyId,PROVIDER).first<Row>();let calendarId=String(existing?.calendar_id||'');if(calendarId){try{await api(`/calendars/${encodeURIComponent(calendarId)}`,t.access_token);}catch{calendarId='';}}
    if(!calendarId){const cal=await api('/calendars',t.access_token,{method:'POST',body:JSON.stringify({summary:'Family TODO',timeZone:String(member.timezone||DEFAULT_FAMILY_TIMEZONE)})}) as any;calendarId=String(cal.id);}
    const cipher=await encryptRefreshToken(t.refresh_token,env.GOOGLE_CALENDAR_TOKEN_KEY!),n=now();await env.DB.prepare(`INSERT INTO external_calendar_accounts(family_id,member_id,provider,refresh_token_ciphertext,token_key_version,calendar_id,calendar_name,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'ACTIVE',?,?) ON CONFLICT(family_id,provider) DO UPDATE SET member_id=excluded.member_id,refresh_token_ciphertext=excluded.refresh_token_ciphertext,token_key_version=excluded.token_key_version,calendar_id=excluded.calendar_id,status='ACTIVE',last_error=NULL,updated_at=excluded.updated_at`).bind(s.familyId,s.memberId,PROVIDER,cipher,'v1',calendarId,'Family TODO',n,n).run();await env.DB.prepare(`INSERT INTO calendar_sync_state(family_id,provider,calendar_id,sync_token,updated_at) VALUES(?,?,?,NULL,?) ON CONFLICT(family_id,provider,calendar_id) DO UPDATE SET sync_token=NULL,updated_at=excluded.updated_at`).bind(s.familyId,PROVIDER,calendarId,n).run();return redirect('/app/settings_integrations.php?calendar=linked');}catch(e){const category=e instanceof Error&&['missing code','token exchange','missing refresh token','member changed'].includes(e.message)?e.message.replaceAll(' ','-'):'calendar-create';console.error('google calendar callback failed:',category);return redirect('/app/settings_integrations.php?calendar=error&reason='+encodeURIComponent(category));}}
export function eligibleTask(t:Row){return String(t.visibility_scope||'FAMILY')==='FAMILY'&&Number(t.calendar_visible)===1&&['TASK','EVENT'].includes(String(t.task_kind||'TASK').toUpperCase())&&Boolean(t.start_at||t.due_at)&&!t.recurrence_rule;}
export async function enqueueCalendarSync(db:D1Database,familyId:number,taskId:number,operation:'CREATE'|'UPDATE'|'DELETE'){const n=now(),linked=await db.prepare("SELECT id FROM external_calendar_accounts WHERE family_id=? AND provider=? AND status='ACTIVE' AND calendar_id IS NOT NULL").bind(familyId,PROVIDER).first();if(!linked)return;await db.prepare(`INSERT INTO calendar_sync_outbox(family_id,task_id,provider,operation,status,next_retry_at,created_at,updated_at) VALUES(?,?,?,?,'PENDING',?,?,?) ON CONFLICT(provider,task_id) DO UPDATE SET operation=CASE WHEN excluded.operation='DELETE' THEN 'DELETE' WHEN calendar_sync_outbox.operation='CREATE' THEN 'CREATE' ELSE 'UPDATE' END,status='PENDING',next_retry_at=excluded.next_retry_at,last_error=NULL,updated_at=excluded.updated_at`).bind(familyId,taskId,PROVIDER,operation,n,n,n).run();}
async function accessToken(env:Env,a:Row){const refresh=await decryptRefreshToken(String(a.refresh_token_ciphertext),env.GOOGLE_CALENDAR_TOKEN_KEY!);const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.GOOGLE_CALENDAR_CLIENT_ID!,client_secret:env.GOOGLE_CALENDAR_CLIENT_SECRET!,refresh_token:refresh,grant_type:'refresh_token'})});if(!r.ok){const body=await r.text();if(r.status===400&&body.includes('invalid_grant'))throw new Error('REAUTH_REQUIRED');throw new Error('token refresh failed');}return String((await r.json() as any).access_token);}
function plusDay(date:string){return addWallClockMinutes(`${date} 00:00:00`,1440).slice(0,10)}
function minusDay(date:string){return addWallClockMinutes(`${date} 00:00:00`,-1440).slice(0,10)}
export function outboundEvent(t:Row,timezone:string){const start=String(t.start_at||t.due_at),allDay=Number(t.all_day)===1;return {summary:String(t.title),description:String(t.description||''),location:String(t.location||''),extendedProperties:{private:{familyTodoTaskId:String(t.id)}},start:allDay?{date:start.slice(0,10)}:{dateTime:start.replace(' ','T'),timeZone:timezone},end:allDay?{date:plusDay(String(t.end_at||start).slice(0,10))}:{dateTime:String(t.end_at||start).replace(' ','T'),timeZone:timezone}};}
export async function processCalendarOutbox(env:Env,limit=10,familyId?:number){const result={sent:0,errors:0};if(!configured(env))return result;const familyFilter=familyId?' AND o.family_id=?':'';const rows=await env.DB.prepare(`SELECT o.*,a.refresh_token_ciphertext,a.calendar_id,f.timezone FROM calendar_sync_outbox o JOIN families f ON f.id=o.family_id JOIN external_calendar_accounts a ON a.family_id=o.family_id AND a.provider=o.provider AND a.status='ACTIVE' WHERE o.status IN ('PENDING','ERROR') AND o.retry_count<${CALENDAR_MAX_RETRIES}${familyFilter} ORDER BY o.id LIMIT ?`).bind(...(familyId?[familyId,limit*4]:[limit*4])).all<Row>();for(const o of rows.results.filter(o=>calendarRetryDue(o.status,o.retry_count,o.next_retry_at)).slice(0,limit)){try{const task=await env.DB.prepare('SELECT * FROM tasks WHERE id=? AND family_id=?').bind(o.task_id,o.family_id).first<Row>(),link=await env.DB.prepare('SELECT * FROM external_calendar_links WHERE provider=? AND task_id=? AND family_id=?').bind(PROVIDER,o.task_id,o.family_id).first<Row>(),token=await accessToken(env,o),op=String(o.operation);if(op==='DELETE'||!task||!eligibleTask(task)){if(link)await api(`/calendars/${encodeURIComponent(String(o.calendar_id))}/events/${encodeURIComponent(String(link.external_event_id))}`,token,{method:'DELETE'});if(link)await env.DB.prepare('UPDATE external_calendar_links SET deleted_at=? WHERE id=?').bind(now(),link.id).run();}else{const ev=await api(`/calendars/${encodeURIComponent(String(o.calendar_id))}/events${link?'/'+encodeURIComponent(String(link.external_event_id)):''}`,token,{method:link?'PUT':'POST',body:JSON.stringify(outboundEvent(task,String(o.timezone||DEFAULT_FAMILY_TIMEZONE)))}) as any;await env.DB.prepare(`INSERT INTO external_calendar_links(family_id,task_id,provider,calendar_id,external_event_id,external_etag,last_synced_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(provider,task_id) DO UPDATE SET calendar_id=excluded.calendar_id,external_event_id=excluded.external_event_id,external_etag=excluded.external_etag,last_synced_at=excluded.last_synced_at,deleted_at=NULL`).bind(o.family_id,o.task_id,PROVIDER,o.calendar_id,String(ev.id),String(ev.etag||''),now()).run();}await env.DB.prepare("UPDATE calendar_sync_outbox SET status='DONE',last_error=NULL,updated_at=? WHERE id=?").bind(now(),o.id).run();result.sent++;}catch(e){result.errors++;const message=String(e instanceof Error?e.message:e);if(message==='REAUTH_REQUIRED')await env.DB.prepare("UPDATE external_calendar_accounts SET status='REVOKED',last_error='REAUTH_REQUIRED',updated_at=? WHERE family_id=? AND provider=?").bind(now(),o.family_id,PROVIDER).run();const count=Number(o.retry_count)+1,next=calendarRetryAt(count);await env.DB.prepare("UPDATE calendar_sync_outbox SET status='ERROR',retry_count=?,next_retry_at=?,last_error=?,updated_at=? WHERE id=?").bind(count,next,message.slice(0,500),now(),o.id).run();}}return result;}
export function inboundEventTimes(event:any,timezone:string){if(event.start?.date){return {allDay:1,start:`${event.start.date} 00:00:00`,end:`${minusDay(event.end?.date||plusDay(event.start.date))} 23:59:59`};}return {allDay:0,start:parseImportDateTime(event.start?.dateTime,timezone),end:parseImportDateTime(event.end?.dateTime||event.start?.dateTime,timezone)};}
export async function applyInbound(env:Env,a:Row,event:any){let link=await env.DB.prepare('SELECT * FROM external_calendar_links WHERE family_id=? AND provider=? AND external_event_id=?').bind(a.family_id,PROVIDER,String(event.id)).first<Row>();
 // An event returned immediately after outbound may be observed before an event-id lookup wins.
 // The private extended property is only a hint: both the task and link must belong to this family.
 if(!link){const hinted=Number(event?.extendedProperties?.private?.familyTodoTaskId||0);if(Number.isSafeInteger(hinted)&&hinted>0)link=await env.DB.prepare(`SELECT l.* FROM external_calendar_links l JOIN tasks t ON t.id=l.task_id AND t.family_id=l.family_id WHERE l.family_id=? AND l.provider=? AND l.task_id=? AND t.family_id=?`).bind(a.family_id,PROVIDER,hinted,a.family_id).first<Row>();}
 if(event.status==='cancelled'){if(link)await env.DB.batch([env.DB.prepare('UPDATE tasks SET calendar_visible=0,updated_at=? WHERE id=? AND family_id=?').bind(now(),link.task_id,a.family_id),env.DB.prepare('UPDATE external_calendar_links SET deleted_at=?,external_etag=?,last_synced_at=? WHERE id=? AND family_id=?').bind(now(),String(event.etag||''),now(),link.id,a.family_id)]);return link?1:0;}
 if(link&&String(link.external_etag||'')===String(event.etag||''))return 0;const times=inboundEventTimes(event,String(a.timezone||DEFAULT_FAMILY_TIMEZONE)),n=now();let taskId=Number(link?.task_id||0);
 if(taskId){
  // Calendar is authoritative only for its projection. In particular it must not
  // rewrite TASK/EVENT, completion_mode/status, completions, or assignees.
  const updated=await env.DB.prepare('UPDATE tasks SET title=?,description=?,start_at=?,end_at=?,due_at=?,location=?,all_day=?,calendar_visible=1,updated_at=? WHERE id=? AND family_id=?').bind(String(event.summary||'(無題)'),String(event.description||'')||null,times.start,times.end,times.start,String(event.location||'')||null,times.allDay,n,taskId,a.family_id).run();
  if(!Number(updated.meta.changes||0))return 0;
 }else{// New Google events are equivalent to visibility_scope='FAMILY' EVENT records only.
  const r=await env.DB.prepare("INSERT INTO tasks(family_id,title,description,due_at,status,completion_mode,created_by,created_at,updated_at,start_at,end_at,location,calendar_visible,task_kind,all_day,visibility_scope,private_owner_id) VALUES(?,?,?,?,'pending','ANY',?,?,?,?,?,?,1,'EVENT',?,'FAMILY',NULL)").bind(a.family_id,String(event.summary||'(無題)'),String(event.description||'')||null,times.start,a.member_id,n,n,times.start,times.end,String(event.location||'')||null,times.allDay).run();taskId=Number(r.meta.last_row_id);}
 await env.DB.prepare(`INSERT INTO external_calendar_links(family_id,task_id,provider,calendar_id,external_event_id,external_etag,last_synced_at,deleted_at) VALUES(?,?,?,?,?,?,?,NULL) ON CONFLICT(provider,task_id) DO UPDATE SET external_event_id=excluded.external_event_id,external_etag=excluded.external_etag,last_synced_at=excluded.last_synced_at,deleted_at=NULL`).bind(a.family_id,taskId,PROVIDER,a.calendar_id,String(event.id),String(event.etag||''),n).run();return 1;}
async function syncCalendarAccountUnlocked(env:Env,a:Row){let received=0,token=await accessToken(env,a),sync=await env.DB.prepare('SELECT sync_token FROM calendar_sync_state WHERE family_id=? AND provider=? AND calendar_id=?').bind(a.family_id,PROVIDER,a.calendar_id).first<Row>(),syncToken=String(sync?.sync_token||''),pageToken='';for(let page=0;page<10;page++){const q=new URLSearchParams({singleEvents:'true',showDeleted:'true',maxResults:'250'});if(syncToken)q.set('syncToken',syncToken);if(pageToken)q.set('pageToken',pageToken);let data:any;try{data=await api(`/calendars/${encodeURIComponent(String(a.calendar_id))}/events?${q}`,token);}catch(e){if(e instanceof GoogleError&&e.status===410&&syncToken){syncToken='';pageToken='';await env.DB.prepare('UPDATE calendar_sync_state SET sync_token=NULL,updated_at=? WHERE family_id=? AND provider=? AND calendar_id=?').bind(now(),a.family_id,PROVIDER,a.calendar_id).run();continue;}throw e;}for(const event of data.items||[])received+=await applyInbound(env,a,event);pageToken=String(data.nextPageToken||'');if(!pageToken){if(!data.nextSyncToken)throw new Error('missing nextSyncToken');await env.DB.prepare(`INSERT INTO calendar_sync_state(family_id,provider,calendar_id,sync_token,last_synced_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(family_id,provider,calendar_id) DO UPDATE SET sync_token=excluded.sync_token,last_synced_at=excluded.last_synced_at,updated_at=excluded.updated_at`).bind(a.family_id,PROVIDER,a.calendar_id,String(data.nextSyncToken),now(),now()).run();await env.DB.prepare('UPDATE external_calendar_accounts SET last_synced_at=?,last_error=NULL,updated_at=? WHERE id=?').bind(now(),now(),a.id).run();return received;}}throw new Error('calendar pagination limit exceeded');}
export async function syncCalendarAccount(env:Env,a:Row){const id=Number(a.family_id);const running=syncLeases.get(id);if(running)return running;const work=syncCalendarAccountUnlocked(env,a);syncLeases.set(id,work);try{return await work;}finally{if(syncLeases.get(id)===work)syncLeases.delete(id);}}
export async function processCalendarInbound(env:Env,limit=10){const result={received:0,errors:0};if(!configured(env))return result;const accounts=await env.DB.prepare("SELECT a.*,f.timezone FROM external_calendar_accounts a JOIN families f ON f.id=a.family_id WHERE a.provider=? AND a.status='ACTIVE' AND a.calendar_id IS NOT NULL ORDER BY COALESCE(a.last_synced_at,'') LIMIT ?").bind(PROVIDER,limit).all<Row>();for(const a of accounts.results){try{result.received+=await syncCalendarAccount(env,a);}catch(e){result.errors++;const message=String(e instanceof Error?e.message:e);await env.DB.prepare("UPDATE external_calendar_accounts SET status=CASE WHEN ?='REAUTH_REQUIRED' THEN 'REVOKED' ELSE status END,last_error=?,updated_at=? WHERE id=?").bind(message,message.slice(0,500),now(),a.id).run().catch(()=>{});}}return result;}
export async function calendarSyncNow(request:Request,ctx:AppContext){if(!ctx.member)return json({ok:false,error:'認証が必要です'},401);const role=String(ctx.member.role||'').toUpperCase();if(role!=='OWNER'&&role!=='ADMIN')return json({ok:false,error:'管理者権限が必要です'},403);if(request.method!=='POST')return json({ok:false,error:'POST only'},405);const b=await request.json().catch(()=>({})) as any;if(String(b.csrf||'')!==String(ctx.session.csrfToken||''))return json({ok:false,error:'CSRF検証に失敗しました'},403);const outgoing=await processCalendarOutbox(ctx.env,20,ctx.member.family_id),a=await ctx.env.DB.prepare("SELECT a.*,f.timezone FROM external_calendar_accounts a JOIN families f ON f.id=a.family_id WHERE a.family_id=? AND a.provider=? AND a.status='ACTIVE'").bind(ctx.member.family_id,PROVIDER).first<Row>();let received=0,errors=outgoing.errors;if(a)try{received=await syncCalendarAccount(ctx.env,a);}catch(e){errors++;await ctx.env.DB.prepare('UPDATE external_calendar_accounts SET last_error=?,updated_at=? WHERE id=?').bind(String(e),now(),a.id).run();}return json({ok:errors===0,sent:outgoing.sent,received,errors});}
export async function calendarDisconnect(request:Request,ctx:AppContext){if(!ctx.member)return json({ok:false},401);const role=String(ctx.member.role||'').toUpperCase();if(role!=='OWNER'&&role!=='ADMIN')return json({ok:false},403);if(request.method!=='POST')return json({ok:false},405);const b=await request.json().catch(()=>({})) as any;if(String(b.csrf||'')!==String(ctx.session.csrfToken||''))return json({ok:false},403);await ctx.env.DB.prepare("UPDATE external_calendar_accounts SET status='REVOKED',last_error=NULL,updated_at=? WHERE family_id=? AND provider=?").bind(now(),ctx.member.family_id,PROVIDER).run();return json({ok:true});}
export async function calendarRetryFailed(request:Request,ctx:AppContext){if(!ctx.member)return json({ok:false},401);const role=String(ctx.member.role||'').toUpperCase();if(role!=='OWNER'&&role!=='ADMIN')return json({ok:false},403);if(request.method!=='POST')return json({ok:false},405);const b=await request.json().catch(()=>({})) as any;if(String(b.csrf||'')!==String(ctx.session.csrfToken||''))return json({ok:false},403);const r=await ctx.env.DB.prepare("UPDATE calendar_sync_outbox SET status='PENDING',retry_count=0,next_retry_at=?,last_error=NULL,updated_at=? WHERE family_id=? AND provider=? AND retry_count>=?").bind(now(),now(),ctx.member.family_id,PROVIDER,CALENDAR_MAX_RETRIES).run();return json({ok:true,retried:Number(r.meta.changes||0)});}
export async function integrationsSettings(request:Request,ctx:AppContext){
 if(!ctx.member)return redirect('/login.php');
 const [a,p,f]=await Promise.all([
  ctx.env.DB.prepare('SELECT calendar_name,status,last_synced_at,last_error FROM external_calendar_accounts WHERE family_id=? AND provider=?').bind(ctx.member.family_id,PROVIDER).first<Row>(),
  ctx.env.DB.prepare("SELECT SUM(CASE WHEN status IN ('PENDING','ERROR') AND retry_count<8 THEN 1 ELSE 0 END) pending_count,SUM(CASE WHEN retry_count>=8 THEN 1 ELSE 0 END) failed_count FROM calendar_sync_outbox WHERE family_id=? AND provider=?").bind(ctx.member.family_id,PROVIDER).first<Row>(),
  ctx.env.DB.prepare('SELECT timezone FROM families WHERE id=?').bind(ctx.member.family_id).first<Row>()
 ]);
 const c=googleCalendarConfiguration(ctx.env),active=a?.status==='ACTIVE',notice=new URL(request.url).searchParams,reason=String(notice.get('reason')||''),safeReasons:Record<string,string>={'missing-code':'認可をキャンセルしました。','token-exchange':'token exchangeに失敗しました。','missing-refresh-token':'refresh tokenを取得できませんでした。','member-changed':'メンバー状態が変更されました。','calendar-create':'カレンダー作成に失敗しました。'};
 const checks=[['Client ID',c.clientId],['Client Secret',c.clientSecret],['Redirect URI',c.redirectUri],['Token key',c.tokenKey],['OAuth scope: calendar.app.created',true],['Family timezone: '+String(f?.timezone||DEFAULT_FAMILY_TIMEZONE),true],['scheduled sync: 有効',true]].map(([k,v])=>`<div class="diagnostic-row"><span>${k}</span><strong>${v?'✓':'missing'}</strong></div>`).join('');
 const failed=Number(p?.failed_count||0),action=active?`<button id="calendarSync">今すぐ同期</button> <button class="btn gray" id="calendarDisconnect">連携解除</button><pre id="calendarResult"></pre>`:`<a class="btn" href="/oauth/google-calendar/authorize">${a?.last_error==='REAUTH_REQUIRED'?'再連携':'Googleアカウントと連携'}</a>`;
 const script=`<script>const csrf=${JSON.stringify(String(ctx.session.csrfToken||''))};async function act(url){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({csrf})}),d=await r.json();(url.includes('family-ai')?document.getElementById('aiResult'):document.getElementById('calendarResult')).textContent=d.retried!==undefined?'再試行 '+d.retried+'件':d.sent===undefined?(d.ok?'完了':'失敗'):'送信 '+d.sent+'件 / 受信 '+d.received+'件 / エラー '+d.errors+'件';if(url.includes('disconnect')&&d.ok)location.reload()}document.getElementById('calendarSync')?.addEventListener('click',()=>act('/api/google-calendar/sync'));document.getElementById('calendarDisconnect')?.addEventListener('click',()=>act('/api/google-calendar/disconnect'));document.getElementById('calendarRetry')?.addEventListener('click',()=>act('/api/google-calendar/retry-failed'));document.getElementById('aiTest')?.addEventListener('click',()=>act('/api/family-ai/connection-test'));</script>`;
 const callbackNotice=notice.get('calendar')==='linked'?'<div class="notice">Google Calendarと連携しました。</div>':notice.get('calendar')==='error'?`<div class="notice">${esc(safeReasons[reason]||'Google Calendar連携に失敗しました。')}</div>`:notice.get('calendar')==='not-configured'?'<div class="notice">Cloudflare Worker Secretsの設定が必要です。</div>':a?.last_error==='REAUTH_REQUIRED'?'<div class="notice">Googleの再認証が必要です。</div>':'';
 return html(layout('外部連携',`<div class="page-head"><h1>🔗 外部連携</h1><a class="btn gray" href="/app/settings.php">戻る</a></div>${callbackNotice}<div class="card"><h2>Google Calendar設定</h2>${checks}<p>${active?'連携中':'未連携'}</p>${a?`<p class="small">${esc(a.calendar_name)} / 最終同期 ${esc(a.last_synced_at||'未実行')} / pending ${Number(p?.pending_count||0)} / error ${failed}</p>`:''}${failed?`<p><strong>同期失敗 ${failed}件</strong> <button id="calendarRetry">再試行</button></p>`:''}${configured(ctx.env)?action:'<p>Cloudflare Worker Secretsの設定が必要です。</p>'}</div><div class="card"><h2>Google Home</h2><a class="btn gray" href="/app/settings_google_home.php">設定を開く</a></div><div class="card"><h2>Family AI</h2><p>Gemini API: ${ctx.env.GEMINI_API_KEY?'configured':'not configured'}</p>${ctx.env.GEMINI_API_KEY?'<button id="aiTest">接続確認</button> <pre id="aiResult"></pre>':''}<p class="small">secret値・実ユーザーデータは表示・送信しません。</p></div>${script}`, '/app/settings.php'));
}
