import { html, json, redirect } from './response';
import type { AppContext } from './app';
import { recordQuickChoreDomain, startDedicatedSleepDomain, stopDedicatedSleepDomain, layout } from './app';
import type { CurrentMember } from './types';

type Row=Record<string,unknown>;
const ACCESS_SECONDS=3600, CODE_SECONDS=300;
const nowText=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date());
const escapeHtml=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const safeEqual=(a:string,b:string)=>{const aa=new TextEncoder().encode(a),bb=new TextEncoder().encode(b);if(aa.length!==bb.length)return false;let d=0;for(let i=0;i<aa.length;i++)d|=aa[i]^bb[i];return d===0;};
async function hash(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
async function form(request:Request){const fd=await request.formData(),out:Record<string,string>={};fd.forEach((v,k)=>{out[k]=String(v)});return out;}
function oauthError(error:string,description:string,status=400){return json({error,error_description:description},status,{'cache-control':'no-store','pragma':'no-cache'});}
function configured(env:Env){return Boolean(env.GOOGLE_HOME_CLIENT_ID&&env.GOOGLE_HOME_CLIENT_SECRET&&env.GOOGLE_HOME_REDIRECT_URI);}
function validAuthorize(env:Env,clientId:string,redirectUri:string,responseType:string){return configured(env)&&safeEqual(clientId,String(env.GOOGLE_HOME_CLIENT_ID))&&safeEqual(redirectUri,String(env.GOOGLE_HOME_REDIRECT_URI))&&responseType==='code';}

export async function googleAuthorize(request:Request,ctx:AppContext):Promise<Response>{
  const input=request.method==='POST'?await form(request):(()=>{const out:Record<string,string>={};new URL(request.url).searchParams.forEach((v,k)=>{out[k]=v});return out;})();
  const clientId=String(input.client_id||''),redirectUri=String(input.redirect_uri||''),state=String(input.state||''),responseType=String(input.response_type||'');
  if(!validAuthorize(ctx.env,clientId,redirectUri,responseType))return html(layout('Google Home 連携','<div class="card"><h1>連携リクエストが無効です</h1><p>client_id、redirect_uri または response_type を確認してください。</p></div>'),400);
  if(!ctx.member){const next=new URL(request.url);return redirect(`/login.php?next=${encodeURIComponent(next.pathname+next.search)}`);}
  if(request.method==='GET'){
    const hidden=`<input type="hidden" name="client_id" value="${escapeHtml(clientId)}"><input type="hidden" name="redirect_uri" value="${escapeHtml(redirectUri)}"><input type="hidden" name="response_type" value="code"><input type="hidden" name="state" value="${escapeHtml(state)}"><input type="hidden" name="csrf" value="${escapeHtml(ctx.session.csrfToken||'')}">`;
    return html(layout('Google Home 連携',`<div class="card"><h1>Google HomeとFamily TODOを連携します</h1><p>${escapeHtml(ctx.member.name)} さんの操作として、睡眠とちょこっと家事を記録します。</p><form method="post">${hidden}<div class="actions"><button class="btn" name="decision" value="allow">連携する</button><button class="btn gray" name="decision" value="cancel">キャンセル</button></div></form></div>`));
  }
  if(!ctx.session.csrfToken||!safeEqual(String(input.csrf||''),ctx.session.csrfToken))return html(layout('Google Home 連携','<div class="card"><h1>セッションを確認できません</h1></div>'),403);
  const destination=new URL(redirectUri);destination.searchParams.set('state',state);
  if(input.decision!=='allow'){destination.searchParams.set('error','access_denied');return redirect(destination.toString());}
  const code=randomToken(),now=Math.floor(Date.now()/1000);
  await ctx.env.DB.prepare('INSERT INTO google_home_authorization_codes(code_hash,family_id,member_id,client_id,redirect_uri,expires_at,created_at) VALUES(?,?,?,?,?,?,?)').bind(await hash(code),ctx.member.family_id,ctx.member.id,clientId,redirectUri,now+CODE_SECONDS,nowText()).run();
  destination.searchParams.set('code',code);return redirect(destination.toString());
}

function clientCredentials(request:Request,input:Record<string,string>){let id=input.client_id||'',secret=input.client_secret||'';const auth=request.headers.get('authorization')||'';if(auth.startsWith('Basic ')){try{const decoded=atob(auth.slice(6));const colon=decoded.indexOf(':');id=decodeURIComponent(decoded.slice(0,colon));secret=decodeURIComponent(decoded.slice(colon+1));}catch{/* invalid below */}}return {id,secret};}
export async function googleToken(request:Request,env:Env):Promise<Response>{
  if(request.method!=='POST')return oauthError('invalid_request','POST is required',405);
  const input=await form(request),credentials=clientCredentials(request,input);
  if(!configured(env)||!safeEqual(credentials.id,String(env.GOOGLE_HOME_CLIENT_ID||''))||!safeEqual(credentials.secret,String(env.GOOGLE_HOME_CLIENT_SECRET||'')))return oauthError('invalid_client','Client authentication failed',401);
  const now=Math.floor(Date.now()/1000),created=nowText();
  if(input.grant_type==='authorization_code'){
    if(!safeEqual(input.redirect_uri||'',String(env.GOOGLE_HOME_REDIRECT_URI||'')))return oauthError('invalid_grant','redirect_uri does not match');
    const codeHash=await hash(input.code||'');
    const code=await env.DB.prepare('SELECT * FROM google_home_authorization_codes WHERE code_hash=? AND client_id=? AND redirect_uri=? AND used_at IS NULL LIMIT 1').bind(codeHash,credentials.id,input.redirect_uri).first<Row>();
    if(!code||Number(code.expires_at)<now)return oauthError('invalid_grant','Code is invalid, expired, or already used');
    const used=await env.DB.prepare('UPDATE google_home_authorization_codes SET used_at=? WHERE id=? AND used_at IS NULL AND expires_at>=?').bind(now,code.id,now).run();if(!used.meta.changes)return oauthError('invalid_grant','Code is invalid, expired, or already used');
    const access=randomToken(),refresh=randomToken();
    await env.DB.prepare('INSERT INTO google_home_tokens(family_id,member_id,access_token_hash,refresh_token_hash,access_expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(code.family_id,code.member_id,await hash(access),await hash(refresh),now+ACCESS_SECONDS,created,created).run();
    return json({token_type:'Bearer',access_token:access,refresh_token:refresh,expires_in:ACCESS_SECONDS},200,{'cache-control':'no-store','pragma':'no-cache'});
  }
  if(input.grant_type==='refresh_token'){
    const row=await env.DB.prepare('SELECT * FROM google_home_tokens WHERE refresh_token_hash=? AND revoked_at IS NULL LIMIT 1').bind(await hash(input.refresh_token||'')).first<Row>();if(!row)return oauthError('invalid_grant','Refresh token is invalid or revoked');
    const access=randomToken();await env.DB.prepare('UPDATE google_home_tokens SET access_token_hash=?,access_expires_at=?,updated_at=? WHERE id=? AND revoked_at IS NULL').bind(await hash(access),now+ACCESS_SECONDS,created,row.id).run();
    return json({token_type:'Bearer',access_token:access,expires_in:ACCESS_SECONDS},200,{'cache-control':'no-store','pragma':'no-cache'});
  }
  return oauthError('unsupported_grant_type','Only authorization_code and refresh_token are supported');
}

async function bearerMember(request:Request,env:Env){const header=request.headers.get('authorization')||'';if(!header.startsWith('Bearer '))return null;const token=header.slice(7).trim();if(!token)return null;return env.DB.prepare(`SELECT t.id token_id,m.* FROM google_home_tokens t JOIN members m ON m.id=t.member_id AND m.family_id=t.family_id WHERE t.access_token_hash=? AND t.revoked_at IS NULL AND t.access_expires_at>=? AND m.active=1 AND m.deleted_at IS NULL LIMIT 1`).bind(await hash(token),Math.floor(Date.now()/1000)).first<CurrentMember&{token_id:number}>();}
function scene(id:string,name:string){return {id,type:'action.devices.types.SCENE',traits:['action.devices.traits.Scene'],name:{name,nicknames:[name]},willReportState:false,attributes:{sceneReversible:false}};}
async function sync(env:Env,member:CurrentMember,requestId:string){const [subjects,chores]=await Promise.all([env.DB.prepare("SELECT id,name FROM family_log_subjects WHERE family_id=? AND active=1 AND subject_kind IN ('BABY','CHILD') ORDER BY id").bind(member.family_id).all<Row>(),env.DB.prepare('SELECT id,name FROM family_quick_chores WHERE family_id=? AND active=1 ORDER BY sort_order,id').bind(member.family_id).all<Row>()]);const devices:any[]=[];for(const s of subjects.results){devices.push(scene(`ft:sleep:start:${s.id}`,`${s.name}寝た`),scene(`ft:sleep:stop:${s.id}`,`${s.name}起きた`));}for(const c of chores.results)devices.push(scene(`ft:chore:${c.id}`,`${c.name}完了`));return json({requestId,payload:{agentUserId:`ft-member-${member.id}`,devices}});}
function executeResponse(requestId:string,ids:string[],status:string,errorCode?:string){return {requestId,payload:{commands:[{ids,status,...(errorCode?{errorCode}:{})}]}};}
async function execute(env:Env,member:CurrentMember,body:any,requestId:string){const commands=Array.isArray(body?.inputs?.[0]?.payload?.commands)?body.inputs[0].payload.commands:[];const responses:any[]=[];for(const group of commands){const ids=Array.isArray(group.devices)?group.devices.map((d:any)=>String(d.id||'')):[];for(const execution of Array.isArray(group.execution)?group.execution:[]){if(execution.command!=='action.devices.commands.ActivateScene'||execution.params?.deactivate===true){responses.push(...ids.map((id:string)=>executeResponse(requestId,[id],'ERROR','functionNotSupported').payload.commands));continue;}for(const id of ids){const key=`${id}:activate`;const inserted=await env.DB.prepare("INSERT OR IGNORE INTO external_command_receipts(provider,family_id,member_id,request_id,command_key,status,created_at,updated_at) VALUES('GOOGLE_HOME',?,?,?,?, 'PENDING',?,?)").bind(member.family_id,member.id,requestId,key,nowText(),nowText()).run();if(!inserted.meta.changes){const old=await env.DB.prepare("SELECT status,error_code FROM external_command_receipts WHERE provider='GOOGLE_HOME' AND request_id=? AND command_key=?").bind(requestId,key).first<Row>();responses.push({ids:[id],status:String(old?.status)==='ERROR'?'ERROR':'SUCCESS',...(old?.error_code?{errorCode:String(old.error_code)}:{})});continue;}let error='';try{let ok=false;if(/^ft:sleep:start:\d+$/.test(id))ok=(await startDedicatedSleepDomain(env,member,Number(id.split(':')[3]))).ok;else if(/^ft:sleep:stop:\d+$/.test(id))ok=(await stopDedicatedSleepDomain(env,member,Number(id.split(':')[3]))).ok;else if(/^ft:chore:\d+$/.test(id))ok=(await recordQuickChoreDomain(env,member,Number(id.split(':')[2]))).ok;else error='deviceNotFound';if(!ok&&!error)error='deviceNotFound';}catch{error='hardError';}await env.DB.prepare('UPDATE external_command_receipts SET status=?,error_code=?,updated_at=? WHERE provider=? AND request_id=? AND command_key=?').bind(error?'ERROR':'SUCCESS',error||null,nowText(),'GOOGLE_HOME',requestId,key).run();responses.push({ids:[id],status:error?'ERROR':'SUCCESS',...(error?{errorCode:error}:{})});}}}return json({requestId,payload:{commands:responses}});}
export async function googleFulfillment(request:Request,env:Env):Promise<Response>{if(request.method!=='POST')return json({error:'method_not_allowed'},405);const member=await bearerMember(request,env);if(!member)return json({error:'unauthorized'},401);const body=await request.json().catch(()=>null) as any;if(!body||!Array.isArray(body.inputs))return json({error:'invalid_request'},400);const requestId=String(body.requestId||crypto.randomUUID()),intent=String(body.inputs[0]?.intent||'');if(intent==='action.devices.SYNC')return sync(env,member,requestId);if(intent==='action.devices.EXECUTE')return execute(env,member,body,requestId);if(intent==='action.devices.DISCONNECT'){await env.DB.prepare('UPDATE google_home_tokens SET revoked_at=?,updated_at=? WHERE family_id=? AND member_id=? AND revoked_at IS NULL').bind(nowText(),nowText(),member.family_id,member.id).run();return json({});}if(intent==='action.devices.QUERY')return json({requestId,payload:{devices:{}}});return json({requestId,payload:{errorCode:'protocolError'}},400);}

export async function googleHomeSettings(request:Request,ctx:AppContext):Promise<Response>{if(!ctx.member)return redirect('/login.php');if(request.method==='POST'){const input=await form(request);if(!ctx.session.csrfToken||!safeEqual(input.csrf||'',ctx.session.csrfToken))return json({ok:false,error:'CSRF検証に失敗しました。'},403);await ctx.env.DB.prepare('UPDATE google_home_tokens SET revoked_at=?,updated_at=? WHERE family_id=? AND member_id=? AND revoked_at IS NULL').bind(nowText(),nowText(),ctx.member.family_id,ctx.member.id).run();return redirect('/app/settings_google_home.php');}const link=await ctx.env.DB.prepare('SELECT t.created_at,m.name FROM google_home_tokens t JOIN members m ON m.id=t.member_id WHERE t.family_id=? AND t.member_id=? AND t.revoked_at IS NULL ORDER BY t.id DESC LIMIT 1').bind(ctx.member.family_id,ctx.member.id).first<Row>();return html(layout('Google Home',`<div class="page-head"><div><div class="eyebrow">管理 → 外部連携</div><h1>Google Home</h1></div><a class="btn gray" href="/app/settings.php">戻る</a></div><div class="card"><h2>Google Home連携: ${link?'連携中':'未連携'}</h2>${link?`<p>linked member: ${escapeHtml(link.name)}</p><p>連携日時: ${escapeHtml(link.created_at)}</p><form method="post"><input type="hidden" name="csrf" value="${escapeHtml(ctx.session.csrfToken||'')}"><button class="btn danger">連携解除</button></form>`:'<p>Google Homeアプリの「Works with Google Home」からFamily TODOを追加して連携してください。</p>'}<p class="small">共有端末では、実際に話した人と linked member が一致しない場合があります。</p></div>`,'/app/settings.php'));}
export async function googleHomeHealth(env:Env){const counts=await env.DB.prepare('SELECT SUM(CASE WHEN revoked_at IS NULL THEN 1 ELSE 0 END) active_links,SUM(CASE WHEN revoked_at IS NOT NULL THEN 1 ELSE 0 END) revoked_links FROM google_home_tokens').first<Row>();return json({ok:true,google_home:{configured:configured(env),active_links:Number(counts?.active_links||0),revoked_links:Number(counts?.revoked_links||0)}});}
