import { html } from './response';

const shell=(title:string,body:string)=>html(`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${title} | 家族TODO LINE</title><style>body{margin:0;background:#f6f7f9;color:#202124;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.7}.wrap{max-width:760px;margin:0 auto;padding:32px 20px 56px}.card{background:#fff;border:1px solid #e2e5e9;border-radius:16px;padding:28px;box-shadow:0 2px 10px rgba(0,0,0,.04)}h1{font-size:1.8rem;margin:0 0 8px}h2{font-size:1.15rem;margin:28px 0 8px}p,li{font-size:.98rem}.muted{color:#5f6368}.links{margin-top:32px;padding-top:18px;border-top:1px solid #e8eaed}.links a{margin-right:18px;color:#1769aa}</style></head><body><main class="wrap"><article class="card">${body}<div class="links"><a href="/privacy">プライバシーポリシー</a><a href="/terms">利用規約</a></div></article></main></body></html>`);

export function privacyPage():Response{
  return shell('プライバシーポリシー',`<h1>プライバシーポリシー</h1><p class="muted">家族TODO LINE における情報の取扱いについて説明します。</p><h2>取得・利用する情報</h2><p>本サービスは、ログインと家族内の本人識別のために LINE の認証情報および、LINE から提供される範囲のプロフィール情報を利用します。タスク、予定、買い物、伝言、家族ログなど、利用者が本サービスへ登録した情報は、選択された公開範囲と家族単位のアクセス制御に従って処理されます。</p><h2>Google 連携</h2><p>利用者が Google 連携を有効にした場合、本サービスは Google OAuth を用いて Google Calendar または Google Tasks と連携します。連携の実行に必要な認証情報、同期状態、対応関係などを保存・処理することがあります。Google から取得した情報は、連携機能を提供する目的で利用します。</p><h2>位置情報</h2><p>位置情報機能を有効にした家族については、OwnTracks などの位置提供元から受信した位置データを FamilyToDo の位置情報基盤で処理します。位置共有は端末単位で有効・無効化でき、無効化・失効した端末からの新しい位置情報は受け付けません。位置情報は家族の範囲を越えて表示しないようアクセス制御されます。位置情報は緊急通報・救命・常時監視を目的とするサービスではありません。</p><h2>画像・メディア</h2><p>カレンダーや伝言等で利用するアップロード済みメディアは、Cloudflare R2 の本サービス用ストレージに保存される場合があります。表示時は本サービスの認証・公開範囲に沿った経路から取り扱います。</p><h2>保存期間、削除、連携解除</h2><p>データは各機能を提供するために必要な範囲で保存されます。本サービスには機能ごとの削除、共有停止、端末失効などの操作がありますが、このページでは全データに共通する固定保存期間を約束しません。削除操作の対象外となる履歴・同期状態・メディア等は、対応する削除または保持期間処理が行われるまで保存される場合があります。Google 連携は FamilyToDo 側の連携操作に加え、Google アカウント側でもアクセス権を取り消せます。</p><h2>安全管理</h2><p>本サービスは家族単位のアクセス制御、認証、端末秘密情報のハッシュ化など、現在の実装に応じた保護を行います。ただし、インターネット上の通信・保存に絶対的な安全性を保証するものではありません。</p><h2>変更</h2><p>機能や連携内容の変更に伴い、このポリシーを更新することがあります。重要な取扱いは、その時点の公開ページに反映します。</p>`);
}

export function termsPage():Response{
  return shell('利用規約',`<h1>利用規約</h1><p class="muted">家族TODO LINE の利用条件です。</p><h2>サービスの目的</h2><p>本サービスは、家族内のタスク、予定、買い物、伝言、家族ログ、位置情報および外部サービス連携をまとめて扱うための家庭向け支援サービスです。</p><h2>利用者の責任</h2><p>利用者は、自分が利用権限を持つ LINE・Google 等のアカウントを接続し、家族内で共有する情報について必要な同意を得たうえで利用してください。第三者の情報や位置情報を、本人の意思に反して登録・共有してはいけません。</p><h2>外部サービス</h2><p>LINE、Google、Cloudflare その他の外部サービスを利用する機能は、それぞれの提供条件、仕様変更、障害、利用制限の影響を受けます。本サービスは外部サービスの継続提供を保証しません。</p><h2>位置情報の注意</h2><p>表示される位置には端末の測位精度、通信状況、更新間隔による誤差や遅延があり得ます。位置情報や到着予測を、生命・身体の安全に関わる判断、緊急通報、厳密な出退勤証明などの唯一の根拠として使用しないでください。</p><h2>禁止事項</h2><p>不正アクセス、認証情報の不正利用、他の家族領域へのアクセス試行、サービスや外部サービスへ過度な負荷を与える行為、法令または第三者の権利を侵害する行為は禁止します。</p><h2>変更・停止</h2><p>機能、安全性、外部サービスの仕様などに応じて、本サービスの内容を変更または停止する場合があります。本サービスは、特定の機能、保存期間、可用性、完全性または将来の提供を恒久的に保証するものではありません。</p><h2>本規約の変更</h2><p>本サービスの構成や取扱いの変更に応じて、本規約を更新することがあります。更新後の内容はこの公開ページに掲載します。</p>`);
}
