import type { AppContext } from './app-context';
import { layout } from './app-shell';
import { html,redirect } from './response';
import { APP_VERSION } from './version';

type Row=Record<string,unknown>;
const PAGE_SIZE=40;
const esc=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const nowJst=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date());
const dayLabel=(value:unknown)=>{const s=String(value||'');return /^\d{4}-\d{2}-\d{2}/.test(s)?s.slice(0,10):'';};
const timeLabel=(value:unknown)=>String(value||'').slice(11,16);

export async function messagesChatPage(request:Request,ctx:AppContext):Promise<Response>{
  const m=ctx.member;if(!m)return redirect('/login.php?next=%2Fapp%2Fmessages.php');
  const url=new URL(request.url),before=Math.max(0,Number(url.searchParams.get('before')||0)||0),now=nowJst();
  const query=`SELECT msg.id,msg.sender_id,msg.image_upload_id,msg.text,msg.reminder_at,msg.created_at,msg.updated_at,msg.converted_to_shopping_id,msg.converted_to_task_id,s.name sender_name,s.line_picture_url,
    EXISTS(SELECT 1 FROM message_stamp_attachments a JOIN calendar_stamp_assets asset ON asset.id=a.asset_id AND asset.family_id=a.family_id AND asset.active=1 WHERE a.family_id=msg.family_id AND a.message_id=msg.id) has_stamp,
    (SELECT COUNT(*) FROM message_reads r JOIN members reader ON reader.id=r.member_id AND reader.family_id=r.family_id AND reader.active=1 AND reader.deleted_at IS NULL WHERE r.family_id=msg.family_id AND r.message_id=msg.id) read_count
    FROM messages msg JOIN members s ON s.id=msg.sender_id AND s.family_id=msg.family_id
    WHERE msg.family_id=? ${before?'AND msg.id<?':''} AND (msg.target_member_id IS NULL OR msg.target_member_id IN (?,msg.sender_id)) AND (msg.reminder_at IS NULL OR msg.reminder_at<=? OR msg.sender_id=?)
    ORDER BY msg.id DESC LIMIT ${PAGE_SIZE+1}`;
  const rows=before?await ctx.env.DB.prepare(query).bind(m.family_id,before,m.id,now,m.id).all<Row>():await ctx.env.DB.prepare(query).bind(m.family_id,m.id,now,m.id).all<Row>();
  const hasOlder=rows.results.length>PAGE_SIZE,visible=rows.results.slice(0,PAGE_SIZE),oldest=visible.length?Number(visible[visible.length-1].id):0;
  const messages=visible.map((r,index)=>{const day=dayLabel(r.created_at),separator=day&&day!==dayLabel(visible[index+1]?.created_at)?`<div class="chat-day"><span>${esc(day)}</span></div>`:'';const mine=Number(r.sender_id)===Number(m.id),scheduled=String(r.reminder_at||'')>now;const avatar=String(r.line_picture_url||'');const avatarMarkup=`<div class="chat-avatar" aria-hidden="true">${/^https:\/\//i.test(avatar)?`<img src="${esc(avatar)}" alt="" loading="lazy" onerror="this.remove()">`:''}<span>${esc(String(r.sender_name||'?').slice(0,1))}</span></div>`;return `<article class="chat-message ${mine?'mine':'theirs'}${Number(r.has_stamp)?' has-stamp':''}" data-message-id="${Number(r.id)}" data-message-type="${Number(r.has_stamp)?'stamp':r.image_upload_id?'image':'text'}" data-text="${esc(r.text)}" data-updated-at="${esc(r.updated_at)}" data-created-at="${esc(r.created_at)}" data-mine="${mine?'1':'0'}">${mine?'':avatarMarkup}<div class="chat-stack">${mine?'':`<div class="chat-sender">${esc(r.sender_name)}</div>`}<div class="chat-bubble">${r.image_upload_id?`<img class="chat-photo" src="/api/messages?photo=${Number(r.id)}" alt="伝言の写真" loading="lazy" decoding="async" data-photo-share="1">`:''}${esc(r.text)}</div><div class="chat-meta">${scheduled?`<span class="chat-scheduled">予約 ${esc(String(r.reminder_at).slice(5,16))}</span> ・ `:''}${esc(timeLabel(r.created_at))}${mine?`<span class="chat-read-count" data-read-count="${Number(r.read_count)||0}">${Number(r.read_count)?` ・ 既読${Number(r.read_count)}`:' ・ 未読'}</span>`:''}</div></div>${mine?avatarMarkup:''}</article>${separator}`;}).join('');
  const role=String(m.role||'').toUpperCase(),canModerate=role==='OWNER'||role==='ADMIN';
  const payload=JSON.stringify({csrf:ctx.session.csrfToken||'',memberId:m.id,canModerate,now}).replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026');
  const archive=before?'<div class="chat-archive-label">過去のメッセージ</div>':'',older=hasOlder&&oldest?`<a class="chat-archive-link" href="/app/messages.php?before=${oldest}">さらに以前のメッセージ</a>`:'',back=before?'<a class="chat-latest-link" href="/app/messages.php">最新のメッセージに戻る</a>':'',initialClass=before?'':' chat-messages-reversed';
  const body=`<script src="/assets/message-photo-upload.js?v=${APP_VERSION}-photo3" defer></script><script src="/assets/mitenya-photo-share.js?v=1" defer></script><link rel="stylesheet" href="/assets/messages-chat.css?v=${APP_VERSION}-chat12"><main class="messages-chat-page"><header class="messages-chat-head"><h1>家族</h1><div class="sub">家族グループ</div></header><section id="chatMessages" class="${initialClass.trim()}">${back}${messages||'<div class="chat-empty">まだメッセージはありません</div>'}${older}${archive}</section></main>
  <form class="chat-composer" id="chatComposer"><input type="hidden" name="csrf" value="${esc(ctx.session.csrfToken||'')}"><button class="chat-icon-btn" type="button" id="chatPlus" aria-label="メニュー">＋</button><textarea name="text" rows="1" maxlength="5000" placeholder="メッセージ" aria-label="メッセージ"></textarea><button class="chat-media-btn" type="button" id="chatImage" aria-label="写真を選択">▧</button><button class="chat-send-btn" type="submit" aria-label="送信">➤</button></form>
  <div class="chat-tools" id="chatTools"><div class="chat-tools-grid"><button type="button" id="chatStamp" aria-label="スタンプ"><span class="chat-tool-icon">☺</span><span>スタンプ</span></button><button type="button" id="chatSchedule" aria-label="送信予約"><span class="chat-tool-icon">◷</span><span>送信予約</span></button><button type="button" id="chatToolImage" aria-label="写真を選択"><span class="chat-tool-icon">▧</span><span>写真</span></button></div><div class="chat-schedule-row" id="chatScheduleRow"><input type="datetime-local" id="chatScheduleAt"><div class="chat-image-note">予約時刻までは他の家族には表示されません</div></div></div>
  <div class="chat-stamp-picker" id="chatStampPicker" aria-label="スタンプ"></div><div class="chat-menu-backdrop" id="chatMenuBackdrop" aria-hidden="true"><div class="chat-menu" id="chatMenu"></div></div>
  <script type="application/json" id="messagesChatPayload">${payload}</script><script src="/assets/messages-chat-diagnostics.js?v=${APP_VERSION}-chatdiag1" data-family="${Number(m.family_id)}"></script><script src="/assets/messages-chat.js?v=${APP_VERSION}-chat12"></script><script src="/assets/messages-reactions.js?v=${APP_VERSION}-1"></script><script src="/assets/messages-composer-ui.js?v=${APP_VERSION}-1"></script><script src="/assets/messages-admin-delete.js?v=${APP_VERSION}-admin-delete1"></script>`;
  return html(layout('伝言',body,'/app/messages.php'));
}
