const nowJst = () => new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date()).replace(' ',' ');

export async function cleanupNotificationLifecycle(env: Env): Promise<void> {
  const now=nowJst();
  // Operational activity audit is retained for 31 JST calendar days. Domain
  // completion histories and Family Log are intentionally untouched.
  await env.DB.prepare("DELETE FROM activity_logs WHERE occurred_at < datetime(?,'-31 days')").bind(now).run();
  // Disable pending work for members who opted out/deactivated, or whose family no longer matches the notification.
  await env.DB.prepare("UPDATE notifications SET status='cancelled',updated_at=? WHERE status IN ('pending','retry') AND (member_id IN (SELECT id FROM members WHERE active=0 OR notification_enabled=0) OR NOT EXISTS (SELECT 1 FROM members m WHERE m.id=notifications.member_id AND m.family_id=notifications.family_id))").bind(now).run();
  await env.DB.prepare("UPDATE web_push_subscriptions SET enabled=0,last_error='member inactive or deleted',updated_at=? WHERE enabled=1 AND (NOT EXISTS(SELECT 1 FROM members m WHERE m.id=web_push_subscriptions.member_id AND m.family_id=web_push_subscriptions.family_id) OR EXISTS(SELECT 1 FROM members m WHERE m.id=web_push_subscriptions.member_id AND (m.active=0 OR m.deleted_at IS NOT NULL)))").bind(now).run();
  // Remove operational reminders whose task is gone/completed. Recurring-template reminders are also cancelled when the series is stopped/deleted.
  await env.DB.prepare("UPDATE notifications SET status='cancelled',updated_at=? WHERE status IN ('pending','retry') AND target_type='task' AND (target_id IS NULL OR NOT EXISTS (SELECT 1 FROM tasks t WHERE t.id=notifications.target_id AND t.family_id=notifications.family_id) OR EXISTS (SELECT 1 FROM tasks t WHERE t.id=notifications.target_id AND t.family_id=notifications.family_id AND t.status='completed') OR EXISTS (SELECT 1 FROM tasks t LEFT JOIN recurrence_rules r ON r.task_id=t.id AND r.family_id=t.family_id WHERE t.id=notifications.target_id AND t.family_id=notifications.family_id AND lower(COALESCE(t.task_kind,'')) IN ('recurring','recurrence_template') AND (r.id IS NULL OR r.active=0 OR r.deleted_at IS NOT NULL)))").bind(now).run();
  await env.DB.prepare("UPDATE notifications SET status='cancelled',updated_at=? WHERE status IN ('pending','retry') AND target_type='task' AND EXISTS(SELECT 1 FROM tasks t WHERE t.id=notifications.target_id AND t.family_id=notifications.family_id AND t.visibility_scope='PRIVATE' AND (t.private_owner_id IS NULL OR t.private_owner_id<>notifications.member_id))").bind(now).run();
  await env.DB.prepare("UPDATE notifications SET status='cancelled',updated_at=? WHERE status IN ('pending','retry') AND target_type='message' AND (target_id IS NULL OR NOT EXISTS (SELECT 1 FROM messages x WHERE x.id=notifications.target_id AND x.family_id=notifications.family_id))").bind(now).run();

  // Clear stale conversion pointers when their converted destination has already been deleted.
  await env.DB.prepare("UPDATE messages SET converted_to_task_id=NULL,updated_at=? WHERE converted_to_task_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM tasks t WHERE t.id=messages.converted_to_task_id AND t.family_id=messages.family_id)").bind(now).run();
  await env.DB.prepare("UPDATE messages SET converted_to_shopping_id=NULL,updated_at=? WHERE converted_to_shopping_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM shopping_items s WHERE s.id=messages.converted_to_shopping_id AND s.family_id=messages.family_id)").bind(now).run();

  // Standalone shopping/items are valid, so detach only impossible cross-family/deleted task links instead of deleting the child record.
  await env.DB.prepare("UPDATE shopping_items SET task_id=NULL,updated_at=? WHERE task_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM tasks t WHERE t.id=shopping_items.task_id AND t.family_id=shopping_items.family_id)").bind(now).run();
  await env.DB.prepare("UPDATE items SET task_id=NULL,updated_at=? WHERE task_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM tasks t WHERE t.id=items.task_id AND t.family_id=items.family_id)").bind(now).run();

  // If legacy/import data somehow bypassed the partial unique index, keep the oldest active reminder and cancel the rest before send.
  await env.DB.prepare("UPDATE notifications SET status='cancelled',updated_at=? WHERE status IN ('pending','retry') AND EXISTS (SELECT 1 FROM notifications keep WHERE keep.id<notifications.id AND keep.family_id=notifications.family_id AND keep.member_id=notifications.member_id AND keep.target_type=notifications.target_type AND COALESCE(keep.target_id,-1)=COALESCE(notifications.target_id,-1) AND keep.notify_at=notifications.notify_at AND keep.status IN ('pending','retry'))").bind(now).run();

  const [dup,orphan,orphanExceptions,orphanRules,staleMessageLinks,staleTaskChildren,orphanOperationalRows,archiveDuplicates,archiveMemberMismatch,familyLogLinkIssues,promotionInviteIssues,taskFamilyLogTemplateIssues]=await Promise.all([
    env.DB.prepare("SELECT COUNT(*) c FROM (SELECT family_id,member_id,target_type,target_id,notify_at,COUNT(*) n FROM notifications WHERE status IN ('pending','retry') GROUP BY family_id,member_id,target_type,target_id,notify_at HAVING COUNT(*)>1)").first<any>(),
    env.DB.prepare("SELECT COUNT(*) c FROM notifications n WHERE n.status IN ('pending','retry') AND ((n.target_type='task' AND NOT EXISTS(SELECT 1 FROM tasks t WHERE t.id=n.target_id AND t.family_id=n.family_id)) OR (n.target_type='message' AND NOT EXISTS(SELECT 1 FROM messages m WHERE m.id=n.target_id AND m.family_id=n.family_id)))").first<any>(),
    env.DB.prepare("SELECT COUNT(*) c FROM recurrence_occurrences o WHERE o.exception_task_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM tasks t WHERE t.id=o.exception_task_id AND t.family_id=o.family_id)").first<any>(),
    env.DB.prepare("SELECT COUNT(*) c FROM recurrence_rules r WHERE NOT EXISTS (SELECT 1 FROM tasks t WHERE t.id=r.task_id AND t.family_id=r.family_id)").first<any>(),
    env.DB.prepare("SELECT COUNT(*) c FROM messages m WHERE (m.converted_to_task_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM tasks t WHERE t.id=m.converted_to_task_id AND t.family_id=m.family_id)) OR (m.converted_to_shopping_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM shopping_items s WHERE s.id=m.converted_to_shopping_id AND s.family_id=m.family_id))").first<any>(),
    env.DB.prepare("SELECT (SELECT COUNT(*) FROM shopping_items s WHERE s.task_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM tasks t WHERE t.id=s.task_id AND t.family_id=s.family_id)) + (SELECT COUNT(*) FROM items i WHERE i.task_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM tasks t WHERE t.id=i.task_id AND t.family_id=i.family_id)) c").first<any>(),
    env.DB.prepare("SELECT (SELECT COUNT(*) FROM task_assignees a WHERE NOT EXISTS(SELECT 1 FROM tasks t WHERE t.id=a.task_id) OR NOT EXISTS(SELECT 1 FROM members m WHERE m.id=a.member_id)) + (SELECT COUNT(*) FROM item_assignees a WHERE NOT EXISTS(SELECT 1 FROM items i WHERE i.id=a.item_id) OR NOT EXISTS(SELECT 1 FROM members m WHERE m.id=a.member_id)) + (SELECT COUNT(*) FROM shopping_assignees a WHERE NOT EXISTS(SELECT 1 FROM shopping_items s WHERE s.id=a.shopping_item_id) OR NOT EXISTS(SELECT 1 FROM members m WHERE m.id=a.member_id)) + (SELECT COUNT(*) FROM task_completion_history h WHERE NOT EXISTS(SELECT 1 FROM tasks t WHERE t.id=h.task_id) OR NOT EXISTS(SELECT 1 FROM members m WHERE m.id=h.member_id)) + (SELECT COUNT(*) FROM item_completion_history h WHERE NOT EXISTS(SELECT 1 FROM items i WHERE i.id=h.item_id) OR NOT EXISTS(SELECT 1 FROM members m WHERE m.id=h.member_id)) + (SELECT COUNT(*) FROM shopping_completion_history h WHERE NOT EXISTS(SELECT 1 FROM shopping_items s WHERE s.id=h.shopping_item_id) OR NOT EXISTS(SELECT 1 FROM members m WHERE m.id=h.member_id)) c").first<any>(),
    env.DB.prepare("SELECT COUNT(*) c FROM (SELECT family_id,entity_type,entity_id,COALESCE(member_id,-1) member_key,action,occurred_at,COALESCE(source_type,''),COALESCE(source_id,-1),COUNT(*) n FROM deleted_completion_history GROUP BY family_id,entity_type,entity_id,member_key,action,occurred_at,COALESCE(source_type,''),COALESCE(source_id,-1) HAVING COUNT(*)>1)").first<any>(),
    env.DB.prepare("SELECT COUNT(*) c FROM deleted_completion_history h WHERE h.member_id IS NOT NULL AND EXISTS(SELECT 1 FROM members m WHERE m.id=h.member_id AND m.family_id<>h.family_id)").first<any>(),
    env.DB.prepare("SELECT (SELECT COUNT(*) FROM family_log_subjects s WHERE s.member_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM members m WHERE m.id=s.member_id AND m.family_id=s.family_id)) + (SELECT COUNT(*) FROM family_logs l WHERE l.subject_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM family_log_subjects s WHERE s.id=l.subject_id AND s.family_id=l.family_id)) + (SELECT COUNT(*) FROM family_log_timers x WHERE x.subject_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM family_log_subjects s WHERE s.id=x.subject_id AND s.family_id=x.family_id)) + (SELECT COUNT(*) FROM family_logs l WHERE l.quick_chore_id IS NOT NULL AND (l.log_type<>'HOUSEWORK' OR NOT EXISTS(SELECT 1 FROM family_quick_chores q WHERE q.id=l.quick_chore_id AND q.family_id=l.family_id))) c").first<any>(),
    env.DB.prepare("SELECT COUNT(*) c FROM family_invitations i WHERE i.family_log_subject_id IS NOT NULL AND i.used_at IS NULL AND i.expires_at>? AND (NOT EXISTS(SELECT 1 FROM family_log_subjects s WHERE s.id=i.family_log_subject_id AND s.family_id=i.family_id AND s.active=1) OR EXISTS(SELECT 1 FROM family_log_subjects s WHERE s.id=i.family_log_subject_id AND s.family_id=i.family_id AND s.active=1 AND s.member_id IS NOT NULL))").bind(now).first<any>(),
    env.DB.prepare("SELECT (SELECT COUNT(*) FROM task_family_log_templates ft WHERE NOT EXISTS(SELECT 1 FROM tasks t WHERE t.id=ft.task_id AND t.family_id=ft.family_id) OR (ft.subject_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM family_log_subjects s WHERE s.id=ft.subject_id AND s.family_id=ft.family_id AND s.active=1)) OR ft.log_type NOT IN ('MILK','BREASTFEED','MEAL','DIAPER','SLEEP','BATH','TEMPERATURE','MEDICINE','CONDITION','WEIGHT','HEIGHT','BLOOD_PRESSURE','EXERCISE','WATER','TOILET','WALK','HOUSEWORK','MEMO') OR (ft.log_type='HOUSEWORK' AND ft.subject_id IS NOT NULL)) + (SELECT COUNT(*) FROM family_logs l WHERE l.task_family_log_template_id IS NOT NULL AND (l.linked_occurrence_id IS NULL OR NOT EXISTS(SELECT 1 FROM task_family_log_templates ft WHERE ft.id=l.task_family_log_template_id AND ft.family_id=l.family_id) OR NOT EXISTS(SELECT 1 FROM recurrence_occurrences o WHERE o.id=l.linked_occurrence_id AND o.family_id=l.family_id) OR NOT EXISTS(SELECT 1 FROM task_family_log_templates ft JOIN recurrence_occurrences o ON o.id=l.linked_occurrence_id JOIN recurrence_rules r ON r.id=o.recurrence_rule_id WHERE ft.id=l.task_family_log_template_id AND ft.task_id=r.task_id AND ft.family_id=o.family_id))) c").first<any>()
  ]);
  const audit={duplicate_groups:Number(dup?.c||0),orphan_pending:Number(orphan?.c||0),orphan_exception_links:Number(orphanExceptions?.c||0),orphan_recurrence_rules:Number(orphanRules?.c||0),stale_message_conversion_links:Number(staleMessageLinks?.c||0),stale_task_child_links:Number(staleTaskChildren?.c||0),orphan_operational_rows:Number(orphanOperationalRows?.c||0),deleted_archive_duplicate_groups:Number(archiveDuplicates?.c||0),deleted_archive_member_family_mismatch:Number(archiveMemberMismatch?.c||0),family_log_link_issues:Number(familyLogLinkIssues?.c||0),promotion_invite_issues:Number(promotionInviteIssues?.c||0),task_family_log_template_issues:Number(taskFamilyLogTemplateIssues?.c||0)};
  if(Object.values(audit).some(v=>v>0)) console.warn('[Family TODO LINE] lifecycle audit',audit);
}
