import { makeContext, liffEntryPage } from './app';
const COOKIE='family_google_home_continue';
export const GOOGLE_HOME_CONTINUATION_SECONDS=600;
type Payload={path:string;exp:number};
const b64=(v:Uint8Array)=>{let s='';for(const n of v)s+=String.fromCharCode(n);return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');};
const unb64=(v:string)=>Uint8Array.from(atob(v.replaceAll('-','+').replaceAll('_','/').padEnd(Math.ceil(v.length/4)*4,'=')),c=>c.charCodeAt(0));
const safePath=(v:unknown)=>{const p=String(v??'');return p.length<=2048&&/^\/oauth\/google\/authorize(?:\?|$)/.test(p)&&/^\/(?!\/)[^\r\n\\]*$/.test(p)?p:null;};
const key=async(s:string)=>crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`wave117-google-home:${s}`)),'AES-GCM',false,['encrypt','decrypt']);
export async function sealGoogleHomeContinuation(path:string,secret:string){const valid=safePath(path);if(!valid||!secret)throw new Error('Invalid OAuth continuation');const iv=crypto.getRandomValues(new Uint8Array(12)),body=new TextEncoder().encode(JSON.stringify({path:valid,exp:Date.now()+600000} satisfies Payload));return `${b64(iv)}.${b64(new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(secret),body)))}`;}
export async function openGoogleHomeContinuation(token:string,secret:string):Promise<string|null>{try{if(!secret)return null;const[a,b]=String(token||'').split('.',2);if(!a||!b)return null;const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(a)},await key(secret),unb64(b));const p=JSON.parse(new TextDecoder().decode(raw)) as Payload;return p.exp>=Date.now()?safePath(p.path):null;}catch{return null;}}
const cookie=(r:Request)=>{for(const p of(r.headers.get('cookie')||'').split(';')){const[k,...v]=p.trim().split('=');if(k===COOKIE)return v.join('=');}return '';};
const setCookie=(t:string,age=600)=>`${COOKIE}=${t}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;
const go=(r:Request,p:string,c?:string)=>new Response(null,{status:302,headers:{Location:new URL(p,r.url).toString(),'Cache-Control':'no-store',...(c?{'Set-Cookie':c}:{})}});
async function tokenFor(r:Request,e:Env){const q=new URL(r.url).searchParams.get('resume')||'';if(q&&await openGoogleHomeContinuation(q,e.APP_SECRET))return q;const c=cookie(r);return c&&await openGoogleHomeContinuation(c,e.APP_SECRET)?c:'';}
export async function preserveGoogleHomeLogin(r:Request,e:Env,response:Response){if(response.status!==302)return response;const here=new URL(r.url),login=new URL(response.headers.get('location')||'/login.php',r.url);if(login.origin!==here.origin||login.pathname!=='/login.php')return response;const path=safePath(login.searchParams.get('next'));if(!path)return response;const token=await sealGoogleHomeContinuation(path,e.APP_SECRET);console.log(JSON.stringify({stage:'CONTINUATION_STORED',provider:'GOOGLE_HOME'}));return go(r,`/liff?resume=${encodeURIComponent(token)}`,setCookie(token));}
export async function googleHomeLiff(r:Request,e:Env){const token=await tokenFor(r,e),ctx=await makeContext(r,e);if(ctx.member)return go(r,token?`/oauth/google/continue?resume=${encodeURIComponent(token)}`:'/app/index.php');return liffEntryPage(e,token?`/oauth/google/continue?resume=${encodeURIComponent(token)}`:'/app/index.php');}
export async function resumeGoogleHome(r:Request,e:Env){const token=await tokenFor(r,e),path=token?await openGoogleHomeContinuation(token,e.APP_SECRET):null,ctx=await makeContext(r,e);if(!ctx.member)return go(r,token?`/liff?resume=${encodeURIComponent(token)}`:'/liff');if(!path)return go(r,'/app/index.php',setCookie('',0));console.log(JSON.stringify({stage:'CONTINUATION_RESUMED',provider:'GOOGLE_HOME',family_id:ctx.member.family_id,member_id:ctx.member.id}));return go(r,path,setCookie('',0));}
