import { json } from './response';
type Row=Record<string,unknown>;
const now=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date()).replace(' ',' ');
const bad=(error:string,status=400)=>json({ok:false,error},status);
const ids=(v:unknown)=>[...new Set((Array.isArray(v)?v:[]).map(Number).filter(n=>Number.isInteger(n)&&n>0))];
export async function readShoppingReusableSets(ctx:any,m:any):Promise<Response>{
 const s=await ctx.env.DB.prepare('SELECT id,name,created_by_member_id,updated_at FROM shopping_reusable_sets WHERE family_id=? ORDER BY updated_at DESC,id DESC').bind(m.family_id).all();
 const e=await ctx.env.DB.prepare('SELECT e.* FROM shopping_reusable_set_entries e JOIN shopping_reusable_sets s ON s.id=e.set_id WHERE s.family_id=? ORDER BY e.set_id,e.position,e.id').bind(m.family_id).all();
 const by=new Map<number,Row[]>();for(const x of (e.results||[]) as Row[]){const a=by.get(Number(x.set_id))||[];a.push(x);by.set(Number(x.set_id),a)}
 return json({ok:true,sets:((s.results||[]) as Row[]).map(x=>({id:Number(x.id),name:String(x.name||''),item_count:(by.get(Number(x.id))||[]).length,entries:by.get(Number(x.id))||[],can_edit:Number(x.created_by_member_id)===Number(m.id)||['OWNER','ADMIN'].includes(String(m.role||'').toUpperCase()),can_delete:Number(x.created_by_member_id)===Number(m.id)||['OWNER','ADMIN'].includes(String(m.role||'').toUpperCase())}))});
}
export async function handleShoppingReusableSetAction(ctx:any,m:any,b:Record<string,unknown>):Promise<Response|null>{
 const action=String(b.action||'');if(!action.startsWith('reusable_set_'))return null;
 if(action==='reusable_set_create'){const name=String(b.name||'').trim(),source=ids(b.source_item_ids);if(!name||!source.length)return bad('セット名と買い物を指定してください。');if(source.length>100)return bad('1つのセットは100件までです。');const ph=source.map(()=>'?').join(','),q=await ctx.env.DB.prepare(`SELECT id,name,quantity,category,memo,url FROM shopping_items WHERE family_id=? AND id IN (${ph})`).bind(m.family_id,...source).all(),rows=(q.results||[]) as Row[];if(rows.length!==source.length)return bad('表示中の買い物が更新されています。',409);const map=new Map(rows.map(x=>[Number(x.id),x])),ordered=source.map(id=>map.get(id)!);const t=now();try{const r=await ctx.env.DB.prepare('INSERT INTO shopping_reusable_sets(family_id,name,created_by_member_id,created_at,updated_at) VALUES(?,?,?,?,?)').bind(m.family_id,name,m.id,t,t).run(),setId=Number(r.meta.last_row_id);await ctx.env.DB.batch(ordered.map((x,i)=>ctx.env.DB.prepare('INSERT INTO shopping_reusable_set_entries(set_id,position,name,quantity,category,memo,url) VALUES(?,?,?,?,?,?,?)').bind(setId,i,String(x.name||''),String(x.quantity||'1'),String(x.category||'')||null,String(x.memo||'')||null,String(x.url||'')||null)));return json({ok:true,id:setId,name,item_count:ordered.length},201)}catch{return bad('同じ名前のセットがあるか、保存に失敗しました。',409)}}
 const setId=Number(b.set_id||0),set=await ctx.env.DB.prepare('SELECT id,created_by_member_id,name FROM shopping_reusable_sets WHERE id=? AND family_id=?').bind(setId,m.family_id).first<Row>();if(!set)return bad('セットが見つかりません。',404);const manage=Number(set.created_by_member_id)===Number(m.id)||['OWNER','ADMIN'].includes(String(m.role||'').toUpperCase());
 if(action==='reusable_set_delete'){if(!manage)return bad('このセットを削除する権限がありません。',403);await ctx.env.DB.prepare('DELETE FROM shopping_reusable_sets WHERE id=? AND family_id=?').bind(setId,m.family_id).run();return json({ok:true,id:setId})}
 if(action==='reusable_set_invoke'){const date=String(b.date||''),rid=String(b.client_request_id||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!rid)return bad('日付またはリクエストIDが不正です。');const old=await ctx.env.DB.prepare('SELECT created_item_ids FROM shopping_reusable_set_invocations WHERE family_id=? AND client_request_id=?').bind(m.family_id,rid).first<Row>();if(old){let a:number[]=[];try{a=JSON.parse(String(old.created_item_ids||'[]'))}catch{}return json({ok:true,set_id:setId,date,item_ids:a,deduplicated:true})}const e=await ctx.env.DB.prepare('SELECT * FROM shopping_reusable_set_entries WHERE set_id=? ORDER BY position,id').bind(setId).all(),rows=(e.results||[]) as Row[];if(!rows.length)return bad('このセットには買い物がありません。',409);const t=now();await ctx.env.DB.prepare("INSERT INTO shopping_reusable_set_invocations(family_id,set_id_snapshot,due_date,client_request_id,created_by_member_id,created_item_ids,created_at,updated_at) VALUES(?,?,?,?,?,'[]',?,?)").bind(m.family_id,setId,date,rid,m.id,t,t).run();const out=[];for(const x of rows){const r=await ctx.env.DB.prepare("INSERT INTO shopping_items(family_id,name,quantity,category,memo,due_date,status,created_by,created_at,updated_at,task_id,url) VALUES(?,?,?,?,?,?,'pending',?,?,?,?,?)").bind(m.family_id,String(x.name||''),String(x.quantity||'1'),String(x.category||'')||null,String(x.memo||'')||null,date,m.id,t,t,null,String(x.url||'')||null).run();out.push(Number(r.meta.last_row_id))}await ctx.env.DB.prepare('UPDATE shopping_reusable_set_invocations SET created_item_ids=?,updated_at=? WHERE family_id=? AND client_request_id=?').bind(JSON.stringify(out),now(),m.family_id,rid).run();return json({ok:true,set_id:setId,date,item_ids:out,deduplicated:false},201)}
 return bad('未対応のセット操作です。');
}